### PR TITLE
[PM-2664] Hide Owners column below desktop viewports

### PR DESCRIPTION
**Pull request by nick-livefront**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Make the vault table a little more responsive by hiding certain columns based on the viewport.
- I believe "Owner" is the only column that needs hiding as a part of this ticket. The designs have Folder and Last Edited columns shown but those will be added as a part of a separate ticket.
- The Organization vault uses the same component but doesn't show the Owner column 

The ticket has https://github.com/bitwarden/clients/pull/8899 as a dependency to free up more horizontal space. The code changes weren't dependent on one another so I didn't stack the pull requests but I can if that is preferred! 

## Code changes

- **vault-cipher-row.component.html:** 
  - Hide owner `td` on viewports below desktop
- **vault-items.component.html:**
  - Hide owner `th` on viewports below desktop
  - Apply `lg` media query for `name` column to persist the current layout

## Screenshots

responsive-table

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by gbubemismith** [comment]
Excellent work, @nick-livefront. I have a question: does it make sense to have this ticket https://bitwarden.atlassian.net/browse/PM-2353 addressed first, and the column can be hidden based on the change because the logic of hiding a column is currently tied to the `owner` column and introducing the `last edited` column would mean an update on this code

**Comment by nick-livefront** [comment]
> Does it make sense to have this ticket https://bitwarden.atlassian.net/browse/PM-2353 addressed first?

I think I have a couple conflicting tickets in flight. I would agree that accomplishing PM-2353 makes sense, but best case scenario I think https://github.com/bitwarden/clients/pull/8899 would be merged first, which would free up more horizontal space. Adding two more columns with the cards on the right will be very tight. 

At the very least, PM-2353 includes the logic to show/hide the columns as well. Very overlapped tickets.

**Review by gbubemismith — APPROVED** [review]
LGTM

**Comment by nick-livefront** [comment]
@gbubemismith Brad just tested this one, it's been around awhile! I missed the collections table on the first pass: [PM-8754](https://bitwarden.atlassian.net/browse/PM-8754).

Screen Recording 2024-06-10 at 8 52 13 AM

**Review by LRNcardozoWDF — APPROVED** [review]

**Review by Jingo88 — APPROVED** [review]

**Pull request merged**
