### PR TITLE
[PS-1478] Fix #3169 - The Title value in Identity-type vault items does not carry over to clients using different languages

### LINKED ISSUE #3169: The Title value in Identity-type vault items does not carry over to clients using different languages.
### Steps To Reproduce

1. Log into a Bitwarden via Web Vault with German UI.
2. Create a new Identity-type vault item, select Herr in Title, and save.
3. Log into the same Bitwarden account via the Web Vault in a new tab with English UI.
4. Open the same Identity-type vault item.

### Expected Result

To see 'Mr' in the Title.

### Actual Result

The Title is empty.

### Screenshots or Videos

image

image

### Additional Context

In the browser extension, the vault item displays Herr when viewed, but the Title value appears empty when edited.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 21H2.

### Web Browser

Firefox

### Browser Version

102.0.1.

### Build Version

2022.6.2.

### PR DESCRIPTION
**Pull request by schang1146**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix for #3169 where an identity's "Title" field isn't being respected if language preference changes.

## Code changes

- **libs/angular/src/components/add-edit.component.ts**
I changed the values of the options to be the title's key values ("mr", "mrs", "ms", "dr") so that the field would always be able to grab an option regardless of language preference change.

**IMPORTANT:** One concern I had with this implementation is that it'd break **ALL** current identities to show blank (regardless of language) until a user updates it. Not sure if there is the option to update all currently saved values with their corresponding key values ("mr", "mrs", "ms", "dr") or if another fix would be preferred. Just thought this solution would be the simplest in the long run.

## Screenshots

(Sorry for awkward window cropping lol first time trying this out)
https://user-images.githubusercontent.com/20074034/190029456-486a3dc8-7420-4cfc-9f2b-a80fd56a56ed.mp4

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by djsmith85** [comment]
FYI/mental-note: The same issue is present in the mobile app -> [CipherAddEditPageViewModel.cs](https://github.com/bitwarden/mobile/blob/b7048de2a16e72e301ae4582d69ccc4c405ea248/src/App/Pages/Vault/CipherAddEditPageViewModel.cs#L132)

**Review by djsmith85 — COMMENTED** [review]
@schang1146 Using fixed keys for the dropdown is the way to go. 

Converting the values could be implemented in the `add-edit.component.ts` in the load()-method after decryption and in the `view.component.ts`.

````
// Stuck into \libs\common\src\misc\utils.ts
static fixIdentityTitle(i18nService: I18nService, cipher: CipherView): CipherView {
    if (cipher.type !== CipherType.Identity) {
      return cipher;
    }
    if (Utils.isNullOrEmpty(cipher.identity.title)) {
      return cipher;
    }

    if (cipher.identity.title == i18nService.t("mr")) {
      cipher.identity.title = "mr";
      return cipher;
    }

    if (cipher.identity.title == i18nService.t("mrs")) {
      cipher.identity.title = "mrs";
      return cipher;
    }

    if (cipher.identity.title == i18nService.t("ms")) {
      cipher.identity.title = "ms";
      return cipher;
    }

    if (cipher.identity.title == i18nService.t("dr")) {
      cipher.identity.title = "dr";
      return cipher;
    }

    return cipher;
  }
```
Above is something I came up with while thinking about how to possibly convert without a common method for migrating cipher items.

The next issue that will come up, though, is that the `view.component.html` uses a getter on the `libs\common\src\models\view\identityView.ts` to grab the `subtitle` of an `identityView`. This is currently unaware of the i18nService and would need to be changed.

Your approach is definitely do-able and the way we should proceed, but involves a bit more work than currently in this PR.

**Comment by schang1146** [comment]
I think I understand the ask but not sure about the suggested code block.


Say a user already created an Identity object with the title "Srta" (while their language was set to Español).

If we are trying to convert that `CipherView` property value in the `load()`-method in `add-edit.component.ts` to the global "ms" **after** the user has switched their language preference to say English for example, none of the if-statement matches would ever be hit.
In the example, the `cipher.identity.title` would be "Srta" but `i18nService.t("ms")` would be "Ms" since it doesn't know what the user had as their language preference when setting the Title property.

I'll keep thinking about it but was a bit blocked when trying to get that `fixIdentityTitle` util function to work.

**Comment by djsmith85** [comment]
> I think I understand the ask but I think I'm confused about the suggested code block.
> 
> Say a user already created an Identity object with the title "Srta" (while their language was set to Español). If we are trying to convert that `CipherView` property value in the `load()`-method in `add-edit.component.ts` to the global "ms" **after** the user has switched their language preference to say English for example, none of the if-statement matches would ever be hit. In my example, the `cipher.identity.title` would be "Srta" but `i18nService.t("ms")` would be "Ms" since it doesn't know what the user had as their language preference when setting the Title property.
> 
> I'll keep thinking about it but was a bit blocked when trying to get that `fixIdentityTitle` util function to work.

The code-block I came up with was not intended as a catch-all. I was assuming a user was still in the selected language they originally saved the entry in and this would fix the saved value ("Srta" to "Ms"(untranslated key)). The majority case. If a user already changed languages then there won't be much we can do to fix this, as we don't know what the previously selected user-language was. In this case the originally reported bug (#3169)  of it showing up empty would occur, but would be easy to fix by the user.

I'll close this PR for now, as there is no work to review, but feel free to update the PR and we'll re-open it.

**Pull request closed without merging**
