### PR TITLE
[PS-1333] Fixing formal/informal address inconsistencies (German translation)

### PR DESCRIPTION
**Pull request by paksnuk**
The translations for German used the informal (Du) and formal (Sie) addressing of the user inconsistently. This patch fixes a lot of messages towards the previously predominant formal address and also some other spelling mistakes.

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other (translation)
```

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Comment by djsmith85** [comment]
Hi @paksnuk, thank you for submitting a PR.

We use a translation tool called Crowdin to help manage our localization efforts across many different languages. Our translations can only be updated using Crowdin, so this PR will be closed.

If you are interested in helping translate a Bitwarden client into another language (or make a translation correction), please register an account at Crowdin and join our project here: https://crowdin.com/project/bitwarden-web

If the language that you are interested in translating is not already listed, create a new account on Crowdin, join the project, and contact one of the project managers.

You can read Crowdin's getting started guide for translators here: https://support.crowdin.com/crowdin-intro/

If the translations on Crowdin do not match the translations on Github, please let us know and we will investigate.

**Comment by djsmith85** [comment]
@paksnuk: I (German native speaker) have also previously noticed some inconsistencies within the German translations regarding this (e.g. Duzen vs Siezen). I imagine this is also true for other languages. 

I'd ask you to please create a topic over on our [Community Forums](https://community.bitwarden.com/c/support/6). Maybe we can get a discussion going on what users prefer and once a decision has been made, we can communicate that on our [Contribution Guidelines](https://community.bitwarden.com/c/support/6) and on Crowdin. If you create a thread, please feel free to tag me on it.

This [thread ](https://community.bitwarden.com/t/small-mistake-in-german-translation/43609) also mentioned some wrong German translation. 

Kind regards,
Daniel

**Comment by paksnuk** [comment]
Thanks for the quick reply on the issue. I don't know whether I'll have the capacity to look into another platform soon so I encourage anyone to take (parts of) my contribution and just apply them there themselves!

**Comment by paksnuk** [comment]
Moving the discussion to https://community.bitwarden.com/t/discussion-about-reworking-the-german-translation/43802 in hope for interested community members!

**Pull request closed without merging**
