### PR TITLE
[PS-2253] Fix Password & Username generator wrapper

### PR DESCRIPTION
**Pull request by 0x1AE7F**
Changed width to 80% and added `word-wrap: break-word`

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fixing issue  #4469 by changing the `generated-wrapper` class

## Code changes

Changed width from `100%` to `80%` and added `word-wrap: break-word;`
to the `generated-wrapper` class in `misc.scss`

### Before:
Screenshot 2023-01-13 at 18 09 05

### After:
Screenshot 2023-01-13 at 18 17 30

### CODE REVIEW

**Comment by patrickhlauke** [comment]
I've actually been trying to submit a PR to fix this (but been blocked by https://github.com/bitwarden/clients/issues/4475). The way I tackled it was to just borrow the relevant styles from the browser extension:

```css
.generated-wrapper {
    text-align: left;
    width: 100%;
    min-width: 0;
    white-space: pre-wrap;
    word-break: break-all;
    padding: 15px;
}
```

(interestingly, the browser extension also has an additional border around the `.generated-block`, which may be worth porting over?)

I'd suggest going for this approach, to keep the styles mostly the same between desktop and browser?

**Comment by 0x1AE7F** [comment]
That looks great! Should I change my PR with the code you just sent above? Or do you want to do your own PR?

**Comment by patrickhlauke** [comment]
@0x1AE7F i actually went a slightly different design route ... https://github.com/bitwarden/clients/pull/4480

(though feel bad as this would supersede your PR...didn't mean to barge in and steal your contribution)

**Comment by 0x1AE7F** [comment]
Absolutely no problem.. We are all here to fix bugs and it does not matter who does it first; The quality matters and I would say what you have the better solution.
Im going to close this PR

**Comment by patrickhlauke** [comment]
thank you @0x1AE7F, glad to hear you're not cross about it :)

**Pull request closed without merging**
