### PR TITLE
[PM-6853] Stop Caching Empty Ciphers List

### PR DESCRIPTION
**Pull request by justindbaur**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Occasionally we may attempt to cache an empty cipher array and that could have been from an attempt to decrypt the vault a bit to early, this will keep it from making it to the cache and allow for the next time ciphers are requested for it to do the work instead of trusting the cache which might be wrong.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by MGibson1 — APPROVED** [review]

**Review by MGibson1 — COMMENTED** [review]
Why cache null?

**Comment by justindbaur** [comment]
@MGibson1 Sent this to you off GitHub but for posterity, it's just the behavior they rely on. 

They set it to null to make sure the next time `getAllDecrypted` is called it will get the fresh cipher list. 

https://github.com/bitwarden/clients/blob/72402852bb790a0a8272b72b79b462fbcc80806f/libs/common/src/vault/services/cipher.service.ts#L1305-L1308

https://github.com/bitwarden/clients/blob/72402852bb790a0a8272b72b79b462fbcc80806f/libs/common/src/vault/services/cipher.service.ts#L289-L292

**Comment by MGibson1** [comment]
Again for posterity, we've decided that the right place for this is actually in the cipher service helper function `setDecryptedCipherCache` rather than state service at all.

What's nice about that is that the clean methods go directly to state service, which clean up the concern about leaving cached values for incorrectly wiped out values.

**Review by shane-melton — APPROVED** [review]
This looks good to me!

cc: @LRNcardozoWDF just so you're aware of this with you current `CipherService` state provider work.

**Pull request merged**
