### PR TITLE
[PS-1656] Deduplicate ciphers on import

### PR DESCRIPTION
**Pull request by konradbartecki**
## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adds deduplication of ciphers on import.

See requests from other users:
 - https://community.bitwarden.com/t/duplicate-removal-tool-report/648/43
 - https://community.bitwarden.com/t/how-can-i-delete-multiple-duplicates-of-account-data/5359
 - https://gitlab.com/sundbp/bitwarden-deduplicate
 - https://www.reddit.com/r/Bitwarden/comments/eymrxz/bitwarden_duplicates_after_import_data/

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by micahblut** [comment]
@konradbartecki can you provide a human readable definition of what constitutes a duplicate according to this change? This will be helpful for our QA and documentation teams. Thanks!

**Comment by konradbartecki** [comment]
@micahblut hey sorry for a slow response, basically before this PR it was possible to import passwords from another provider few times which results in saved passwords being duplicated, for example:
1 google.com : mypassword
2 google.com : mypassword

it does not make sense to import the same item again thus this PR introduces a flow where all the exact duplicates are skipped on import.

If the passwords that are being imported vary even slightly, then both of then will be imported.

Import tool is available on the web.

**Comment by konradbartecki** [comment]
Just an update, I won't be updating this PR due to lack of time. If anyone else want to pick it up and test it again then that would be super cool. If not I think this can be closed as I am not even sure if the issue that this PR was fixing long time ago is still valid.

**Comment by djsmith85** [comment]
The proposed solution would only deduplicate, if the source file already contained exact duplicates. This would clean on import, but isn't really solving the issue users are facing. It would need to check for duplicates within the existing ciphers.

Closing this now.

**Pull request closed without merging**
