### PR TITLE
[AC-2102] [AC-2263] [AC-2264] Consolidated Secrets Manager Trial Updates

### PR DESCRIPTION
**Pull request by amorask-bitwarden**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Simple trial updates that point the "Get Started" button to Secrets Manager instead of Password Manager as well as update some of the copy based on marketing feedback. 

## Code changes

- **file.ext:** Description of what was changed and why

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by ike-kottlowski — COMMENTED** [review]
Is there reason for not using the `i18n` pipes and `messages.json` locale for the html bits?

**Comment by amorask-bitwarden** [comment]
> Is there reason for not using the `i18n` pipes and `messages.json` locale for the html bits?

It's all trial content, [none of which is currently translated](https://github.com/bitwarden/clients/tree/72fb5f50e7b3c6401bde9e5063be0bfbfc3aa3de/apps/web/src/app/auth/trial-initiation/content) for any other trial pages so my understanding was that it's not a requirement.

**Review by ike-kottlowski — APPROVED** [review]
LGTM.

non-blocking: I do think however we should use the `i18n` pipes for all text, but that request is out of scope.

**Comment by amorask-bitwarden** [comment]
@ike-kottlowski Can I get a restamp here when you have a sec? Just missed some copy updates.

**Review by ike-kottlowski — APPROVED** [review]

**Pull request merged**
