### PR TITLE
[PS-1512] Desktop: Fix inconsistent line height in cipher box footer

### LINKED ISSUE #3559: Minor: uneven spacing for "Password history" in cypher view
### Steps To Reproduce

1. Go to an entry that has a password history
2. Look at the spacing in the last three lines ("Updated", "Password updated", "Password history")

### Expected Result

The spacing between those three lines should be equal.

### Actual Result

The "Password history" line is slightly taller than the other two. Line height is `17.1429px` on all of them, but the last line has a button with a height of `20px` that pushed the overall line height to `20px`. Nothing dramatic, but to a keen design eye, it just visibly looks slightly "off".

### Screenshots or Videos

Screenshot showing the "Updated", "Password updated", "Password history" lines, with the button element in the last line visually highlighted and showing that it's 20px high

### Additional Context

_No response_

### Operating System

Windows

### Operating System Version

10 Build 19044

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.1

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes #3559

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

In the box footer for a cipher in desktop - which contains "Updated", "Password updated", "Password history" - the "Password history" line is slightly taller than the other two. Line height is `17.1429px` on all of them, but the last line has a button with a height of `20px` that pushed the overall line height to `20px`. Nothing dramatic, but to a keen design eye, it just visibly looks slightly "off".

This PR forces the line height for buttons to match the parent container. For consistency, applying the same style also to `.box-footer a` elements, even though currently (e.g. in the equivalent browser popup) there's no problem just now. This just makes sure that if in future things change, there won't be a visual regression.

## Code changes

- **apps/browser/src/popup/scss/misc.scss** and **apps/desktop/src/scss/misc.scss**: add specific style rule to set explicit `line-height: 1`

## Screenshots

Before - note the slightly uneven line spacing (with the last line being slightly too high)

before screenshot

After - with the line heights evened out

after screenshot

(note that the difference is admittedly very subtle...change from `20px` to `17.1429px` height on the last line)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by jtouchstonebw** [comment]
@patrickhlauke Could we instead increase the line height of all of these to 20px? 

Also, this might not be what you were working on with this but I noticed that the <span> that launches the password history modal/popup doesn't seem to be keyboard focusable currently, do you have any thoughts on how we could improve that?

**Comment by patrickhlauke** [comment]
> @patrickhlauke Could we instead increase the line height of all of these to 20px?

That's a larger design decision that I'll leave up to you/the team. If/when you do that, the `line-height: 1` here will adapt the buttons to whatever you set.

> Also, this might not be what you were working on with this but I noticed that the that launches the password history modal/popup doesn't seem to be keyboard focusable currently, do you have any thoughts on how we could improve that?

works for me. it's a button that takes focus (that `<span>` you highlighted is inside the button)

password history number button, with a visible default outline

**Comment by jtouchstonebw** [comment]
> > @patrickhlauke Could we instead increase the line height of all of these to 20px?
> 
> That's a larger design decision that I'll leave up to you/the team. If/when you do that, the `line-height: 1` here will adapt the buttons to whatever you set.
> 
> > Also, this might not be what you were working on with this but I noticed that the that launches the password history modal/popup doesn't seem to be keyboard focusable currently, do you have any thoughts on how we could improve that?
> 
> works for me. it's a button that takes focus (that `<span>` you highlighted is inside the button)
> 
> password history number button, with a visible default outline

To clarify, if the row height for each line of text could be the equivalent of 20px so the text is more readable that would be awesome. Thanks!

**Comment by patrickhlauke** [comment]
> To clarify, if the row height for each line of text could be the equivalent of 20px so the text is more readable that would be awesome. Thanks!

again, i think that's a larger design decision that should be made globally throughout the app / by design team. i'll leave that out of this PR (but when/if that's done, the change here in the PR will adapt to the new line height)

**Comment by jtouchstonebw** [comment]
> but when/if that's done, the change here in the PR will adapt to the new line height)

Gotcha, I understand you now.

**Review by danielleflinn — APPROVED** [review]

**Review by djsmith85 — APPROVED** [review]
Changes are looking good. Verified locally and ready to merge.

**Comment by patrickhlauke** [comment]
my design-obsessed eyes thank you (one of those "once i've seen it, I can't unsee it" things) :)

**Pull request merged**
