### PR TITLE
[PM-7560] fix wrong buffer conversion for Uint8Array

### PR DESCRIPTION
**Pull request by m-baertschi**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

If the BufferSource is already an Uint8Array which is a view of a subset of the underlying ArrayBuffer then accessing .buffer caused the whole backing buffer to be returned. 

## Code changes

Fix this by just returning the original Uint8Array as-is.

### CODE REVIEW

**Comment by m-baertschi** [comment]
Ping @shane-melton @justindbaur

**Comment by m-baertschi** [comment]
Is there a problem with this pr? @justindbaur @gbubemismith @merissaacosta

**Comment by justindbaur** [comment]
@m-baertschi What I am missing from this is what bug is not having this code causing? I don't see a linked issue.

**Comment by m-baertschi** [comment]
Your Extension is intercepting the Webauth credentials Create and Get functions (`navigator.credentials.create`). Normally this call is forwarded to the browser and the data that is passed as a argument is interpreted by the browser. But if you intercept it and process the date yourself, you need to be very careful to convert the data properly. Which your extension is not doing. 

If the client application passes a [BufferSource](https://devdoc.net/web/developer.mozilla.org/en-US/docs/Web/API/BufferSource.html) that is already of the expected type Uint8Array the function in question will call `.buffer` [(Doc)](https://nodejs.org/docs/latest/api/buffer.html#bufbuffer) on this object. Calling `.buffer` on a BufferSource that is a view of a underlying ArrayBuffer causes the whole underlaying ArrayBuffer to be returned. This underlying buffer can have other date in it as it is not intended to be used by you extension and only the data that is passed as a argument should be used. 

There is no linked issue as i have spent hours debugging this problem for you and the resulting fix is not that complicated. It just adds a additional check to see of the input data is already in the correct format and returns it unmodified.

**Comment by justindbaur** [comment]
@m-baertschi I get the theory behind the bug and I agree it looks quite simple but I would like to have an example of the bug so I can validate the pre-fix behavior and the post-fix behavior. Then I would want a test added somewhere to validate that as well. But I would need an example of a site that does it this way so I can do that.

**Review by justindbaur — APPROVED** [review]

**Pull request merged**
