### PR TITLE
[PM-2866] - Update color variables for better contrast

### PR DESCRIPTION
**Pull request by danielleflinn**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Resolves https://github.com/bitwarden/clients/issues/5026 and internal issue [PM-2866](https://bitwarden.atlassian.net/browse/PM-2866)
Since the migration to the Bitwarden Component Library is taking longer than originally anticipated, this PR resolves the majority of the legacy color contrast issues across web clients. 

## Code changes

- **/browser/src/popup/scss/variables.scss** update hex codes for brand colors and updated toast-text color
- **/desktop/src/scss/variables.scss** update hex codes for brand colors and updated toast-text color
- **/web/src/scss/variables.scss** update hex codes for brand colors
- **/libs/components/src/tw-theme.css** update the Solarize theme's text-contrast color to have better contrast with theme colors
- **//components/src/variables.scss** updated variables to be consistent with other client variables files. 

## Screenshots
Light
Screenshot 2023-08-21 at 12 31 22 PM
Screenshot 2023-08-21 at 12 31 14 PM

Nord
Screenshot 2023-08-21 at 12 30 39 PM
Screenshot 2023-08-21 at 12 30 50 PM

Solarize Dark (browser only)
Screenshot 2023-08-21 at 12 32 22 PM
Screenshot 2023-08-21 at 12 32 14 PM

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

[PM-2866]: https://bitwarden.atlassian.net/browse/PM-2866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by differsthecat — COMMENTED** [review]
I think these need to be updated in the component library colors as well, located at `libs/components/src/variables.scss`; is that correct @willmartian ?

**Comment by willmartian** [comment]
> I think these need to be updated in the component library colors as well, located at `libs/components/src/variables.scss`; is that correct @willmartian ?

Yes, and in `libs/components/src/tw-theme.css` if we want those new colors to propogate to Tailwind: `tw-bg-success-500` etc

**Comment by danielleflinn** [comment]
Thanks; the 3 sources should be in sync now. 

This PR primarily updates the Light brand colors in each client's `variables.css ` file to to match those already defined in `tw-theme.css` (these have already been check for WCAG contrast in Light/Dark and most of the Nord/Solarize dark are less of a priority). 

Then in the dark themes, I've updated the toast text color to be darker since the toast background colors are often less saturated in dark themes.

**Review by differsthecat — APPROVED** [review]
looks good, thanks @danielleflinn !

**Review by willmartian — APPROVED** [review]
lgtm 🥳 🦜

**Comment by patrickhlauke** [comment]
👍

**Pull request merged**
