### PR TITLE
[PS-1768] Remove DDG forwarder from SH

### LINKED ISSUE #3798: DuckDuckGo not working on Self-Hosted environments (CORS Protected like FireFox)
### Steps To Reproduce

1. Go to a self-hosted environment using some private hostname, not something with bitwarden.com
2. Go to `Tools` > `Generator` > `Forwarded Email Alias`
3. Select `DuckDuckGo`, just enter random string, or an actual correct API key of course.
4. Try to generate.

It will respond with a CORS error. 

### Expected Result

Either:
1. A valid response from DuckDuckGo
2. DuckDuckGo not available for self-hosted environments, the same currently is for the FireFox Relay.

### Actual Result

DuckDuckGo option is available but not working.

### Screenshots or Videos

image

### Additional Context

I also tried this via cURL by using the the request send by `vault.bitwarden.com`, which does work, and if i change it to anything else, it will not respond with the needed headers. So it looks like DuckDuckGo is CORS protected same as FireFox.

### Operating System

Windows, macOS, Linux

### Operating System Version

_No response_

### Web Browser

Chrome, Firefox

### Browser Version

_No response_

### Build Version

2022.10.0

### PR DESCRIPTION
**Pull request by justindbaur**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Resolve #3798 by removing it as an option on web self hosted. In the same way firefox relay has to be disabled. 

## Code changes

- **apps/web/src/app/tools/generator.component.ts:** Remove DDG by it's value.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by trmartin4** [comment]
@justindbaur, when I was initially looking at this, I was thinking we could build a model to represent the email forwarder entity and store the name, value, as well as whether it was valid for self-hosted.  Where I struggled was that somewhere we'd need to do that filtering.  @differsthecat had brought up the point that if we build that in, it would make it less likely that the next email forwarded with CORS issues would cause this same problem again (since we'd have to explicitly set it to be allowed on self-hosted, it should trigger that in the dev's mind).

What are your thoughts on patching this with another filter in the `generator.component.ts` in the web vs. a solution where we add a property in the base `generator.component.ts` and filter on that property instead in the component?

**Review by trmartin4 — APPROVED** [review]
I agree that this is a good fix to make sure that the change surface is small in order to get this in the `2022.11` release.  I've created a tech debt task on our backlog to refactor this to be more clear when the list of forwarders is defined.

**Comment by justindbaur** [comment]
@trmartin4 I agree that 2 is a pattern now and we can handle it better. I am down to do the larger changeset here if you want. It would still be pretty minor, adding a type for that array, defining that extra property, and filtering on that instead. I have the code locally that I could push up or we can merge this and I can make a follow up PR that we sit on until after `rc` cutoff.

**Comment by trmartin4** [comment]
> 

I'm sorry for not responding earlier - this got lost in my inbox.  I think it makes sense to keep this as-is, and then we can do a follow-up PR.  I've created another issue in Jira for the cleanup as well so we can keep that separate.

**Pull request merged**
