### PR TITLE
[PS-1111] Added prefix "Vault:" for accessibility on vault selector items

### PR DESCRIPTION
**Pull request by aj-rosado**
## Type of change

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Improve the accessibility message when selecting an item from the vault selector on Browser Extension

## Code changes

- **vault-select.component.html:** Added accessibility attributes

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Review by fedemkr — COMMENTED** [review]
I'd approve it but I'm not that well versed on the clients app, maybe there is something I'm missing so I'd wait for someone else to review it

**Comment by dgoodman-bw** [comment]
Although not mentioned in the ticket, would there be value in applying the same or similar fix to the vault selector items in the other client apps (desktop and web) as well?

**Comment by patrickhlauke** [comment]
Closes one aspect of https://github.com/bitwarden/clients/issues/3078

**Review by MGibson1 — CHANGES_REQUESTED** [review]
Please implement similar accessibility changes on the desktop and web clients (or create tickets to do so)

**Review by patrickhlauke — DISMISSED** [review]

**Review by patrickhlauke — COMMENTED** [review]
actually, small nitpick: you don't need to set *both* `attr.aria-label` and `appA11yTitle`. the latter already does the job of adding both a `title` and an `aria-label` attribute if not already present. so just go with setting `appA11yTitle`

**Review by MGibson1 — APPROVED** [review]

**Review by djsmith85 — APPROVED** [review]

**Pull request merged**
