### PR TITLE
[PS-2159] import/apply changes from https://github.com/bitwarden/web/pull/1277

### PR DESCRIPTION
**Pull request by tamsky**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Not the original author here -- simply trying to capture and apply changes that were in an open PR:
- https://github.com/bitwarden/web/pull/1277

Hoping to faithfully track repo+filename changes, and compensate for any changes made to the UI since Feb 2022.
---

Original Objective from web/pull/1277:
> This feature adds sorting of the ciphers. It is possible to sort by `name`, `owner` (organization), and `lastEdited` by selecting the desired sorting method or clicking the header `Name`. Reverse sorting is also supported for all methods by pressing the arrow or clicking on the header again. Sorting by `dateCreated` is not yet implemented.
> 
> The addition of this feature has been frequently asked for on the community forum.

Examples:
- https://community.bitwarden.com/t/sort-all-items-in-types-based-on-name-date-created-last-modified-used-and-more/33444
- https://community.bitwarden.com/t/sort-items-by-date-of-modification-addition-last-use-etc/2484

## Code changes

- apps/web/src/app/vault/vault-items.component.html: a new column has been added with a sorting option in the header and the respective sorting information in the column. A select all button has also been added above the name of the cipher in the header of the table.

- apps/web/src/app/vault/vault-items.component.ts: the functionality for the sorting has been added. I've tried to write as good typescript as I can but of course this might need improvement. Here, the sort by dateCreated has not been implemented yet.

- apps/web/src/app/vault/bulk-actions.component.html: the select all option has been removed since it now resides in the table. [ this may be a stale comment ]

- apps/web/src/locales/en/messages.json: added three english translations for the sorting methods.

- apps/web/src/scss/tables.scss: some specific CSS has been added to match the provided Figma design.

## Screenshots

[ images are from the original pull request ]

## Testing requirements
- All sorting methods needs to be tested. Both normal order and reverse.
- Ciphers with empty or no data might need to be tested.
- Testing with a user that has several organizations and ciphers would be good.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

## Todo for PR author:
- [ ] review and respond to all PR review comments and suggestions in original PR, there was a batch of comments at the end that do not appear to have been addressed.

### CODE REVIEW

**Comment by tamsky** [comment]
Pinging original authors that contributed to original PR for full disclosure:
/cc @eliykat @fredrikburmester

**Comment by tamsky** [comment]
I have not linted, compiled or tested this commit yet.
Will report back when I have.

**Comment by djsmith85** [comment]
@tamsky Thank you! We really appreciate you willing to pick this up.

As the original [PR](https://github.com/bitwarden/web/pull/1277) and concept have aged, I'd like to ask you to wait for an approval from @bitwarden/dept-design. 
Our component library has also progressed since then, and we'd probably like to use the [Table](https://components.bitwarden.com/?path=/docs/component-library-table--default) component.

We might have other plans to add sorting capabilities. There is also work being done by @Hinton with https://github.com/bitwarden/clients/pull/4079 to support sorting via a TableDataSource, which might also be used in other clients.

Thank you again, for your help with this, we just want to make sure you have guidance on the preferred approach, before writing any further code.

Kind regards,
Daniel

**Comment by tamsky** [comment]
@djsmith85 any thoughts on how this should proceed, or if it's obsoleted?

**Comment by danielleflinn** [comment]
Hi @tamsky, our internal team will be adding the sorting features which will leverage the new table sort functionality that @djsmith85 mentioned above from https://github.com/bitwarden/clients/pull/4079. At this time I don't think it is worth your time to pursue this contribution. Thank you for your interest though!

**Pull request closed without merging**
