### PR TITLE
[PS-1693] feat(browser): implement theming for notification bar

### PR DESCRIPTION
**Pull request by RafaelKr**
## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently the notification bar for adding or updating passwords is unthemed.
This PR implements theming for that notification bar.

In firefox this can be tested by loading the plugin and calling:
`moz-extension://{bitwarden-extension-id}/notification/bar.html?type=add&isVaultLocked=false&theme=light`

`{bitwarden-extension-id}` must be replaced with the internal UUID of the temporarily loaded bitwarden extension you find at `about:debugging#/runtime/this-firefox`

You can play with the following parameters to see every possible state and test hovers:
- **type:** `add` / `change`
- **isVaultLocked:** `true` / `false`
- **theme:** `light` / `dark` / `solarizedDark` / `nord`

## Code changes

- **notification.background.ts:** Get theme from StateService and pass it to notification bar
- **notificationBar.ts:**
	- Build query string from object
	- Use `type=add` or `type=change` parameter instead of `add=1` or `change=1`
	- Pass theme as query parameter
- **bar.html:** I replaced the close img with an SVG. The SVG was created as follows
	- I took the SVG from [apps/desktop/src/images/close-button-white.svg](https://github.com/bitwarden/clients/blob/0189401a069eab4af68a1081a13021833fe19fae/apps/desktop/src/images/close-button-white.svg)
	- I modified it in Inkscape to fill the viewbox
	- I compressed it with https://vecta.io/nano
- **bar.js:**
	- Set theme class on `html` from query variable
	- Remove setting of close button which is now an SVG
	- Replace query variables `add` and `change` with `type`
	- Refactor: Extract handling for different types `add` and `change` in own function
- ***.scss:** Implement theming based on theming in popup
- **close.png** and **manifest:** Remove close.png

## Screenshots
Edit: Latest screenshots in https://github.com/bitwarden/clients/pull/3805#issuecomment-1286655962

**Light**
light

**Dark**
dark

**Solarized Dark**
solarized-dark

**Nord**
nord

### CODE REVIEW

**Comment by sukhleenb** [comment]
Hey @RafaelKr , this looks great! If possible, could you add your svg file to this PR? That way we'll have something to reference in the future.

**Comment by RafaelKr** [comment]
BTW are the maintainers interested in a migration of bar.js to TypeScript? Not sure if I'll have the time for it, but if I know there's interest in it it's something I could do if I find some spare time.

**Comment by RafaelKr** [comment]
@sukhleenb I added the SVG now also as file asset

**Comment by sukhleenb** [comment]
Thanks, @RafaelKr ! One minor UI suggestion, for all the darker themes would you mind updating the contained button text color from white to the notification bar background color? This will provide better contrast. After those updates, @djsmith85 will review the code.

**Comment by RafaelKr** [comment]
I updated it as suggested (except for the light theme, there I also changed it to use the background color).

And indeed, it looks much better! Also I experimented with using textColor for the close button instead of currentColor (inheriting it from the button text color).

**light**
light-currentColor
light-textColor

**dark**
dark-currentColor
dark-textColor

**nord**
nord-currentColor
nord-textColor

**solarizedDark**
solarizedDark-currentColor
solarizedDark-textColor

Please decide for yourself first, before you have a look at my preferences! :)

<details>
<summary>Show my design preferences</summary>

For the light theme I prefer the second version (textColor). This is also how it looks in the currently published version.

For the 3 other themes I like the currentColor more.
</details>

What do you think?

**Comment by sukhleenb** [comment]
Thank you for these iterations! All of these are great options :) I would agree, I prefer the textColor version for the light theme. For simplicity's sake and consistency, I would recommend we follow the same pattern for all 4 themes. Whether that's textColor or currentColor, I don't have that much of a preference. Since we currently follow the textColor pattern for the light theme, that makes me suggest we follow the textColor pattern for all other themes as well. What are your thoughts on that approach?

**Comment by RafaelKr** [comment]
@sukhleenb It's very simple with one new variable to set light to textColor and the others to currentColor, so I would go with that :)

But you also added your design team as reviewers. I'd be happy if they decide.

**Comment by danielleflinn** [comment]
I agree with @sukhleenb assessment in keeping all themes consistent with the variables they use. I have a slight preference for the textColor version, as it seems to be consistent with how close buttons are styled in other Bitwarden clients.

**Comment by RafaelKr** [comment]
> I agree with @sukhleenb assessment in keeping all themes consistent with the variables they use. I have a slight preference for the textColor version, as it seems to be consistent with how close buttons are styled in other Bitwarden clients. 

It would be the same variable, e.g. closeButtonColor, but for light theme the value would be set to the same value as the textColor variable and for the other 3 it would be `currentColor` which is an actual CSS color value which inherits it's color from the current text color. In this case this is the color of the "button" which contains the close icon (always the same color as the button containing the text "Nie")

> > What I'm currently not happy with is the styling of the select field...But there's still an open PR where these are adjusted in their padding, don't know if we should use that new style which I would prefer or go with the old one and restyle it when that other PR is merged.
> 
> It makes sense to include the styling from the other PR; but I would wait until it is merged in case there are other changes added prior to it being merged. 

Okay, after some more thought I came to the conclusion that for the notification bar the select field and the primary button should have the same height. Currently I'm on my mobile phone and can't quickly look up if we'll get this result  when we take the styles from the other PR. Maybe you know if it's also a goal of that PR that buttons and select fields have the same heights everywhere?
I think it would make sense to go even further and unify the height of all input fields and buttons throughout all Bitwarden clients, so when you have them in a row they all nicely align.

**Comment by sukhleenb** [comment]
Thanks @RafaelKr ! The design team thinks the close button should be the same color as the text color. If we get that updated then this should be good to merge.

**Comment by RafaelKr** [comment]
@sukhleenb Implemented.

I still was not happy, because I felt something was missing, gave it another iteration. I now did the following 2 things:

1. The close button now has a hover effect, I used `rgba(themed("textColor"), 0.2)` for that. All the buttons now share the same base styling (padding; border-radius; 1px border, transparent by default). This also makes it look better when using tab to cycle through them.
> One thing I noticed is, that in the solarizedDark theme both the backgroundColor and the inputBorderColor have the same color. This means it looks like the select field has no border and thus is 1px on each side smaller in height than the button.
2. I now also used `rgba($solarizedDarkBase2, 0.2)` (`$solarizedDarkBase2` is the textColor) as the border.

I currently have no time to create new Screenshots, I will post them later.

**Comment by RafaelKr** [comment]
@djsmith85 from my side this is ready for review now, waiting for the go or change requests from @danielleflinn :)

**Review by djsmith85 — APPROVED** [review]
@RafaelKr This looks awesome, and thank you for your work on this.

Most of the codebase has been converted to typescript, and we are still in the process of adding more types. I'm not sure though, if this is currently necessary for the save prompt (`bar.js`). 

We are currently in the process of getting the browser extension migrated to [MV3](https://developer.chrome.com/docs/extensions/mv3/intro/) and once this is done we have some other improvements planned for the save prompt.

FYI : You mentioned/linked to some tailwind stuff. The team has been working on a component library which uses tailwind. Currently, the usage of the components is limited to the web vault, but we are also planning to use those components across clients.

Passing this on to QA and once they give the green light, this can be merged.

**Comment by djsmith85** [comment]
@RafaelKr Just received approval from QA and this is now ready to get merged. Thank you, your contribution will be included in the upcoming 2022.11 release.

**Comment by RafaelKr** [comment]
Awesome! Looking forward to the release :)

**Pull request merged**
