### PR TITLE
[PM-12617] native-messaging: Add chromium support

### PR DESCRIPTION
**Pull request by alexyao2015**
## Tracking
https://bitwarden.atlassian.net/browse/PM-12617

## 📔 Objective

Add support for system authentication support in Chromium on linux.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by quexten** [comment]
Changes look good, though I feel follow-up work is needed so that no PR is needed for every single browser. Thank you for the PR!

**Comment by alexyao2015** [comment]
I don't see a way to automatically support every chromium based browser because they all have their profile in different directories.

**Comment by quexten** [comment]
Seems the CLAassistant was broken for a while, @alexyao2015 could you sign the CLA? Then I can hand this off to QA and get it merged.

**Review by quexten — APPROVED** [review]
Looks good, just needs QA now.

**Comment by quexten** [comment]
QA passed; merging. Thanks again for the PR!

**Pull request merged**
