### PR TITLE
[PM-2311] Allow empty passphrase separator

### LINKED ISSUE #5437: Passphrase generation enforces non-empty word separator
### Steps To Reproduce

1. Create new item by pressing +
2. Click the "generate password" button
3. Choose options
4. Choose "Passphrase"
5. Check the "Word Separator" field content. It should be empty. If it is not empty, remove any content from it.

### Expected Result

When the "word separator" field is empty, I'd expect the generated passphrase to have no whitespace or other separator.

### Actual Result

The generated passphrase has whitespace as a word separator.

### Screenshots or Videos

screenshot

### Additional Context

There seems to be no way to remove the standard whitespace. As tedious as it is, I can still find a lot of websites that don't accept passwords with whitespace in it, so my way-to-go is usually to generate a CamelCasePasswordWith1NumberInIt .

But I cannot remove the whitespace when generating the password with bitwarden.

NOTE: This is a total copy/paste of an issue created by @alanfranz, https://github.com/bitwarden/desktop/issues/1099

### Operating System

macOS

### Operating System Version

10.14.6

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.3 (535)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by joseph082**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Closes #5437
Allow empty passphrase word separator in passphrase generator

## Code changes

- **password-generation.service.ts:** Removed the check for an empty wordSeparator where it currently would get changed to a space. This PR changes it so that an empty wordSeparator will remain as the empty string.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by dbosompem** [comment]
Thank you once again for your contribution! This has been vetted by the Product team and passed off to engineering! We will continue to provide updates as we work through this. Thanks!

**Comment by audrey-jensen** [comment]
@joseph082 - Hi Joseph! I've been doing quite a bit of work on the password generator lately, and it seems that your fix may be out of date. The passphrase generator now replaces missing configurations with a "-", which will clobber your work.

You'll need to adjust this line:
https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/passphrase-generator-options-evaluator.ts#L98

And also tweak the unit test here:
https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/passphrase-generator-options-evaluator.spec.ts#L196-L204

Since sanitize is called when generating a passphrase here:
https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/password-generation.service.ts#L145

You should also be able to remove the comparison you edited entirely.

**Comment by joseph082** [comment]
Hi Audrey, I changed the default separator to the empty string. Is that what you wanted? I think that is the most simple way to allow an empty string.

Because of this, the initial passphrase separator in the browser extension is now the empty string instead of `-` since the initial separator uses the default. Maybe the initial separator should be set to `-` because most users probably want a non-empty separator.

I'm not sure how this affects the CLI or other apps.

It looks like there's no way to generate a passphrase with an empty separator in the CLI. I tried running `node build/bw.js generate --passphrase --separator  `, but it says the argument is missing. Maybe `empty` or some other text could be added as an alias for the empty string here: https://github.com/bitwarden/clients/blob/main/apps/cli/src/tools/generate.command.ts#L84

**Comment by joseph082** [comment]
In the same file: https://github.com/bitwarden/clients/blob/main/apps/cli/src/tools/generate.command.ts#L68, it shows that the CLI uses `-` as the default separator. Maybe a better option is to leave `-` as the default separator and let the empty separator remain as the empty separator

**Comment by audrey-jensen** [comment]
Hey Joseph, thank you for being patient with me as I tracked down a few things. Before I dive into answering your specific questions, I wanted to let you know that a PR landed that moves `PassphraseOptionsEvaluator` into its own folder. We're moving quick on state migrations, and your work got caught in the middle of that. 

The cool part is your PR is definitely helping refine my thinking on the system as a whole. You're working on code I am actively changing, and the whole thing gets better because we're co-creating. I appreciate that, too.

There's a few different things to cover. 

First up: There's [a bug in the service layer](https://github.com/bitwarden/clients/pull/7791) that could be affecting your code. The fix should land on main soon.

Next up is **defaults**:

> Maybe a better option is to leave - as the default separator and to not override the empty separator with the default...

I agree with your approach, and would like to carry it a bit further. The new design centralizes defaults into frozen partials. You can see an example of this in [password-generation-options.ts](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/password-generation-options.ts#L73-L83). You could do the same for [passphrase-generation-options.ts](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/passphrase/passphrase-generation-options.ts), re-export it in [passphrase/index.ts](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/passphrase/index.ts), and then pull it into the CLI using:

```
import { DefaultPassphraseGenerationOptions } from "@bitwarden/common/tools/generator/passphrase";
```

The passphrase options evaluator just requires a tweak to the [existing import](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/passphrase/passphrase-generator-options-evaluator.ts#L3).

```
import { 
  DefaultPassphraseGenerationOptions,
  PassphraseGenerationOptions
} from "./passphrase-generation-options";
```

This way, if the default ever changes, everything stays consistent!

With regard to **calculating `wordSeparator` in the evaluator**, special-casing the empty string seems like the right approach. With the default, the line gets pretty long so I'd probably break it up. How is totally up to you.

Last but not least is **the CLI**. I brought your idea for an `empty` alias to our product designer. They think it's a great idea and said "Thanks for raising this improvement!"

**Comment by joseph082** [comment]
For the `empty` alias, my friend pointed out that you can run `node build/bw.js generate --passphrase --separator ""`, if that changes anything.

**Comment by joseph082** [comment]
Sorry about the automatic review requests.. I ran `git merge master` (I forked this repo when it was master instead of main), and it resulted in a huge diff. My upstream master repo was synced to main, but my downstream repo wasn't. I ran `git pull` when I wasn't on the master branch, and I instead should've ran `git pull origin master`. So I merged an outdated branch..

**Comment by audrey-jensen** [comment]
My guess is the merge explosion happened because of a prettier or linter change?

Assuming so, you should be able to get a clean commit if on your local, you:

1. get latest on `main`, 
2. run `npm ci`,
3. switch to `joseph082:feature/allow-empty-passphrase-separator`
4. perform the merge. 🙂 

> For the `empty` alias, my friend pointed out that you can run `node build/bw.js generate --passphrase --separator ""` which would work once this PR is merged, if that changes anything.

Since you're writing the code, I'll leave that decision to you. If you still want it, we're on board!

**Comment by joseph082** [comment]
I changed the default `wordSeparator` back to `-` using `DefaultPassphraseGenerationOptions` and added the empty string check.

Right now, I think the default `numWords` is 3: [libs password-generation.service.ts](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/password-generation.service.ts#L28) and [CLI](https://github.com/bitwarden/clients/blob/main/apps/cli/src/tools/generate.command.ts#L69), but [this comment](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/passphrase/passphrase-generation-options.ts#L7) says it's four. I'm not sure about web/desktop.

Should `numWords` be 3 or 4? (Later, I'll use `DefaultPassphraseGenerationOptions.numWords` and possibly other defaults in more places, so it's more standardized.

Also, the `DefaultOptions` [in the same libs password-generation.service.ts file](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/password-generation.service.ts#L15) can probably be changed to use `DefaultPassphraseGenerationOptions` and `DefaultPasswordGenerationOptions`.

----------

I realized that the `space` alias is probably there for the same reason as `empty` (the separator is whitespace), so I added the `empty` alias and an example when you run `node build/bw.js generate -h`. I can remove/change the example command if you want.

**Comment by audrey-jensen** [comment]
> But I couldn't find any other PR with the same CODEOWNERS spam after merging with master after the branch name change.

The switch to main and bulk of the prettier updates happened back in December, I think. A lot of that has merged since then. (A smaller update snagged me a week or two ago? Something like that...) Anyway, hopefully we can get this through the pipeline fast enough that you don't run into it again.

> Right now, I think the default numWords is 3: [libs password-generation.service.ts](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/password-generation.service.ts#L28) and [CLI](https://github.com/bitwarden/clients/blob/main/apps/cli/src/tools/generate.command.ts#L69), but [this comment](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/passphrase/passphrase-generation-options.ts#L7) says it's four.

The comment is wrong. The default should be `3`. I must have made a typo when I wrote the comment.

> Also, the DefaultOptions [in the same libs password-generation.service.ts file](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/password/password-generation.service.ts#L15) can probably be changed to use DefaultPassphraseGenerationOptions and DefaultPasswordGenerationOptions.

Keep that as-is. The service model is changing to be based on [default-generator.service.ts](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/generator/default-generator.service.ts), so that entire data structure is deprecated and will be eliminated.

Your changes LGTM. I'll set up a branch to get this to QA!

**Comment by audrey-jensen** [comment]
@joseph082 - The test coverage report identified that you're missing a unit test covering these lines: https://github.com/bitwarden/clients/pull/5473/files#diff-0cbc68b0a5cb67bcaa7162e5dc53b4a9be272ef73c771773a762107183737b8fR116-R117

The test belongs in this describe block:

https://github.com/bitwarden/clients/blob/6c97183e7e3c087b87a73508181066bbce58472e/libs/common/src/tools/generator/passphrase/passphrase-generator-options-evaluator.spec.ts#L219-L254

**Comment by joseph082** [comment]
I changed the default numWords to 3.

I added the test for the empty `wordSeparator`. The commit message is weird because I ran ```git commit -m "Add test for allowing an empty `wordSeparator` during passphrase gen"```, and the backticks escaped `wordSeparator`.

I also made `DefaultPassphraseGenerationOptions.numWords` be used in the CLI's passphrase generation. I couldn't find a test for the CLI's generator defaults

**Comment by audrey-jensen** [comment]
Could you merge the latest from main into your branch?

**Comment by joseph082** [comment]
> Could you merge the latest from main into your branch?

Should I continually keep it up to date with main?

**Comment by audrey-jensen** [comment]
> Should I continually keep it up to date with main?

That shouldn't be necessary. I needed you to merge main so your code includes the service layer bugfix [I mentioned above](https://github.com/bitwarden/clients/pull/5473#issuecomment-1924775152).

**Review by audrey-jensen — APPROVED** [review]

**Comment by joseph082** [comment]
Thanks for your help Audrey 

I made a [similar PR for mobile](https://github.com/bitwarden/mobile/pull/2526) if you could get anyone from mobile to take a look

**Pull request merged**
