### PR TITLE
[PM-4881]: Added userName to fido2credential

### PR DESCRIPTION
**Pull request by abergs**
## Type of change

```
- [X] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Store the fido2credential username field.

## Code changes

I've added the `username`-field in all places where userHandle is present (except in places where we generate assertions)

## Related PR

* https://github.com/bitwarden/server/pull/3459

### CODE REVIEW

**Review by coroiu — CHANGES_REQUESTED** [review]
Field is `null` when sent to the server (reviewing to stop notifications)

**Comment by abergs** [comment]
@coroiu Fixed in latest commit.

**Review by coroiu — CHANGES_REQUESTED** [review]
Failing tests

**Comment by abergs** [comment]
@coroiu Tests are now passing!

**Review by coroiu — APPROVED** [review]

**Review by coroiu — APPROVED** [review]
Approving again to make `vault-dev` go away

**Review by aj-rosado — APPROVED** [review]
Changes are looking good! 🎉

**Pull request merged**
