### PR TITLE
[PS-1222] Remove `appBlurClick` throughout the popup and web code

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

`appBlurClick` leads to focus being lost/reset for assistive technology users. It should not be necessary in any case - if focus does need to move after an action, explicitly set it somewhere programmatically using `focus()` rather than relying on browser heuristics. in cases where the view completely changes as a result of an action, focus is reset automatically anyway.

this is a follow-up to similar previous PRs (both in the browser extension and desktop app) https://github.com/bitwarden/clients/pull/2662 / https://github.com/bitwarden/clients/pull/2654

## Code changes

- removed `appBlurClick` throughout the entirety of the codebase (too many files to list explicitly here)
- removed **libs/angular/src/directives/blur-click.directive.ts** and the related entry in **libs/angular/src/jslib.module.ts** (as `appBlurClick` is now not used anywhere in the code base)

## Screenshots

No discernible change in UI, nor - from my testing - in behaviour.

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Recommend thoroughly testing all functionality of the popup after this change. From my own testing, I have not noticed any negative behaviours.

**Comment by patrickhlauke** [comment]
After merging master branch back into this, it now seems to only be touching on two straggler `appBlurClick`s ... seems the other files have already been fixed/have removed it, which is nice to see

**Review by djsmith85 — CHANGES_REQUESTED** [review]
Thank you @patrickhlauke 
This is looking good and removes the last instances of `appBlurClick`

As we are no longer using it, we should also remove the [directive](https://github.com/bitwarden/clients/blob/master/libs/angular/src/directives/blur-click.directive.ts)

**Comment by patrickhlauke** [comment]
> As we are no longer using it, we should also remove the [directive](https://github.com/bitwarden/clients/blob/master/libs/angular/src/directives/blur-click.directive.ts)

Is it enough to remove that file, or are there deeper ties anywhere else for it? (I'll have a little search, as sadly I'm still not really an angular guy, I just poke it from the side and see what happens)

**Comment by djsmith85** [comment]
> > As we are no longer using it, we should also remove the [directive](https://github.com/bitwarden/clients/blob/master/libs/angular/src/directives/blur-click.directive.ts)
> 
> Is it enough to remove that file, or are there deeper ties anywhere else for it? (I'll have a little search, as sadly I'm still not really an angular guy, I just poke it from the side and see what happens)

After removing the file with the directive, the registration of that directive needs to be removed from `jslib.module.ts`

**Comment by patrickhlauke** [comment]
@djsmith85 okidoki, i'll give it a go and add it to this PR

**Comment by patrickhlauke** [comment]
@djsmith85 done I think

**Comment by djsmith85** [comment]
> @djsmith85 done I think

Almost..., you've removed the import for the directive but it's still used in `jslib.module.ts` (twice)

**Comment by patrickhlauke** [comment]
serves me right for not testing...should be fixed now

**Review by djsmith85 — APPROVED** [review]
No worries, it's looking good now.

@patrickhlauke Thank you for your work on this 👍

**Comment by patrickhlauke** [comment]
wunderbar, thank you @djsmith85 (and sorry for the flood of PRs ... was clearly on a roll/bored recently)

**Comment by djsmith85** [comment]
No problem at all and every contribution is appreciated. Keep up the great work, seems you'll be leading community efforts again for 2022.09 😉

**Pull request merged**
