### PR TITLE
Add renovate config

### PR DESCRIPTION
**Pull request by michalchecinski**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Configure a dependency update using Renovate to run 1 time per month, creating a single PR with everything available to be updated. This PR includes a minimal sensible config for me -- @michalchecinski. Later down the road, we can fine-tune Renovate by updating the config.

Example PR created on`clients` fork by Renovate:
image

## Code changes

- **renovate.json**: Add config for Renovate to create a single PR once a month to update NuGet packages.

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Review by joseph-flinn — COMMENTED** [review]
It looks like Prettier is having an issue with the current format.

Everything else looks good to me.

**Comment by michalchecinski** [comment]
Thanks for pointing out! 😃

**Review by Hinton — COMMENTED** [review]
This looks good to me, I'm somewhat wondering if dependency dashboard would be useful. You will want to run prettier though.

**Comment by michalchecinski** [comment]
@Hinton Linter ran :)

**Pull request merged**
