### PR TITLE
[AC-958] Remove web worker timeout

### PR DESCRIPTION
**Pull request by eliykat**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Remove the timeout (TTL) that would periodically terminate the web worker used by `multithreadEncryptService`.

This is for several reasons:
* we just set 3 minutes as an arbitrary TTL, and notably this is 3 minutes from the last _request_ sent to the worker, not from the last _response_. No decryption should exceed anywhere near 3 minutes, but we don't know that. This is kind of an arbitrary limit that could cause unexpected behaviour
* if the worker is terminated while decryption is ongoing, an empty array will be returned. This is indistinguishable from an empty vault and could cause "empty vault" issues (particularly an issue for key rotation - no evidence of this to date, but let's be safe)
* I was previously unsure whether an idle worker would tie up any memory or CPU resources; this was the reason for the timeout in the first place. After inspecting the worker thread with the Chrome performance tool, the answer is that it uses almost no CPU when idle, and it cleans up its own memory pretty aggressively given that it has very little persistent data (really just the few services it uses). So I don't think the TTL is required generally.

Screenshot 2023-06-01 at 2 30 31 pm
(Spikes in memory and CPU tasks coincide with decryption requests, then they drop off rapidly afterwards. The final drop in the memory line graph is a GC run.)

On the other hand, I do think we should more aggressively terminate the worker on lock or logout, to make sure any ongoing operations are wound up asap.

One unsolved issue is what to return if the worker is terminated early. Here I'm returning `null` instead of an empty array, because it's less likely to be confused for an empty vault. At the moment, callers generally do not expect `null`, so it results in errors being thrown up the call chain; not ideal, but a guaranteed way to abort any operation on lock/logout. Perhaps it would be better practice to have the method signature return `Promise<T[] | void>` to force callers to handle the void/null result, but I haven't done this yet because it propagates through ~100 different call locations all over our codebase. And they would just handle it via an early return, which is similar in effect to the error being thrown. On the other hand, expecting to throw an error and not handling it is not great practice. Feedback here is welcome.

## Code changes

- **libs/common/src/platform/services/cryptography/multithread-encrypt.service.implementation.ts** - remove TTL and timeout. Listen for a "not unlocked" vault instead (i.e. lock or logout) and use that to terminate the worker.
- update dependencies
- **libs/common/src/platform/services/cryptography/encrypt.service.spec.ts** - move to the same folder as the sut

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by MGibson1** [comment]
Regarding return signature of your method, it'd need to be something other than `Promise<[] | void>`, we've had issues in the past losing void returns types with early returns. My memory is fuzzy, but iirc a `return` statement anywhere in the method resulted in `null` rather than `undefined` being returned from the method.

The lesson was: don't return from methods with `void` results.

**Review by MGibson1 — COMMENTED** [review]
I'm not positive this is a problem, but there might be a concurrency issue with your worker cleanup

**Comment by eliykat** [comment]
> Regarding return signature of your method, it'd need to be something other than `Promise<[] | void>`, we've had issues in the past losing void returns types with early returns. My memory is fuzzy, but iirc a `return` statement anywhere in the method resulted in `null` rather than `undefined` being returned from the method.
> 
> The lesson was: don't return from methods with `void` results.

This was the thing we dealt with in `StateService`, right? (I'm fuzzy on the details as well but it rings a bell)

We could return instead `Promise<[] | null>` or `Promise<[] | undefined>`, but that doesn't get enforced by Typescript unless strict mode is on (which it isn't at the moment). It even gets hidden in vscode's hints.

Either way, do you have any opinion on how existing callers should handle a `null`/`undefined` result? They generally don't check for `null` at the moment so most of them will throw an error. I tend to think I need to update all of them to check for null + then have an early return, but that's a bit of a pain and touches a lot of different areas of the codebase, so I wanted to check with someone first. Or just let 'em throw? In both cases, this will only happen when the user is navigating away from the component anyway (to lock/logout), so no UI feedback needs to be given to the user. We're just aborting operations we no longer care about.

**Comment by eliykat** [comment]
Just a thought - observables would solve the above issue, because we can simply choose to not emit the result of an aborted decryption, rather than handling null propagation. I'm not sure if `CipherService` is going to have observables any time soon though.

**Comment by eliykat** [comment]
This is well out of date and is better addressed by #6465 which decreases the worker TTL and improves the timeout mechanism.

**Pull request closed without merging**
