### PR TITLE
[PS-1182] Desktop / Browser: Accessibility - remove appBlurClick, change remaining links to buttons

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

- [x] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

This is essentially a port of some of the changes from https://github.com/bitwarden/desktop/pull/1514 to the browser extension.

- remove `appBlurClick` which is not necessary (and can instead in some circumstances lead to unwanted loss of focus and screen readers resetting to the start of the document). originally it seems this was used to get rid of focus indication following a mouse activation, but in my testing (Chrome/Windows) I found no adverse effect (as the controls that had `appBlurClick` generally ended up doing things like changing the view, opening a dialog, sliding in a panel, etc which already cause a change in focus anyway, so didn't notice any focus indicators "hanging around"; on top of that, modern browsers use heuristics to not show focus indicators as a result of mouse/touch interactions, unless there are explicit `:focus` styles, which doesn't seem to be the case here.
- change any straggler <a> links to buttons where appropriate (where they don't open a browser window) - once you're doing extension/native app work, almost all controls are really "buttons" as they initiate some sort of action - even opening a new panel/view etc can be considered an action, rather than a navigation. this is not a major issue, but for consistency it's best to keep the controls as buttons unless they very explicitly work as links with an `href`.

## Code changes

Bulk change across **apps/browser** files to change links to buttons and remove `appBlurClick`. In addition, one straggler `appBlurClick` in **apps/desktop**, and a few missing `type="button"`s

## Screenshots

No UI change (as far as I could tell)

## Testing requirements

- recommend visual testing to make sure the change from link to button didn't cause any layout/weird display issues (in my testing, I didn't notice anything)
- check that the removal of `appBlurClick` doesn't lead to weird "straggler" focus indicators where they're unwanted, as a result of mouse/touch interaction

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Updated, and now properly linted

**Comment by patrickhlauke** [comment]
not to hassle, but as I'm worried about too much divergence from main branch ... any chance this could be reviewed soon @djsmith85 ?

**Review by djsmith85 — COMMENTED** [review]
This is looking good. 

@patrickhlauke Thanks again for the great work and your patience with the review.

**Review by djsmith85 — APPROVED** [review]

**Comment by patrickhlauke** [comment]
yay, thank you @djsmith85 ... and sorry for nagging

**Comment by djsmith85** [comment]
@patrickhlauke No worries, not seen as nagging. We are still working out/improving the process on handling community PRs internally.

**Pull request merged**
