### PR TITLE
[PS-2266][SG-1067] Desktop: restyle generator panel to be panel-like and avoid overflowing

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

```
- [x] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Closes https://github.com/bitwarden/clients/issues/4469 and the unsightly overflow issue.

However, then takes this further to apply a bit more of a consistent design. This ports the rounded border look from the browser extension.

Supersedes https://github.com/bitwarden/clients/pull/4470 by @0x1AE7F

## Code changes

- **apps/desktop/src/scss/misc.scss:** adds more consistent styles for padding/margin/border, based on the styles for the same component in the browser extension's SCSS
- **apps/desktop/src/scss/variables.scss:** adds the alternative border color variables from the browser extension styles

## Screenshots

Current broken look:

screenshot of current password generator, with password content overflowing the modal

With this PR applied:

long passwords wrap, rounded border around the generator (in all themes: light, dark, nord)

light
dark
nord

### CODE REVIEW

**Review by danielleflinn — APPROVED** [review]

**Review by danielleflinn — CHANGES_REQUESTED** [review]
@patrickhlauke Design would like to keep the generated text styled differently than the form fields that affect it. Feel free to leave the styling similar to what is in the app today or match the browser's generator styling. We definitely would love to merge a fix to the overflow bug as well.

Thanks for working on this

**Comment by patrickhlauke** [comment]
@danielleflinn would you prefer keeping the current styling, and just fixing the overflow bug, or should I see if I can match the styling used in the extension, with the rounded border, for consistency?

**Comment by patrickhlauke** [comment]
@danielleflinn updated the styles to match the browser extension styles. updated the description in the OP

**Review by danielleflinn — APPROVED** [review]
Looks good thanks for adjusting

**Review by differsthecat — APPROVED** [review]
This looks good, thank you @patrickhlauke !  This will be merged after QA completes testing it 👍

**Comment by differsthecat** [comment]
QA approved, thanks again @patrickhlauke !

**Comment by patrickhlauke** [comment]
yay, thanks @differsthecat / team

**Pull request merged**
