### PR TITLE
[PM-5177] fix CLI list items lock error

### LINKED ISSUE #7126: BUG: CLI list item error
### Steps To Reproduce

1. brew install latest Bitwaden-cli 2023.12.0
2. login in
3. run `bw list items --session xxxxx`

### Expected Result

show data without error

### Actual Result

correct show vault data but returns an error

### Screenshots or Videos

image

### Additional Context

_No response_

### Operating System

macOS

### Operating System Version

_No response_

### Shell

Zsh

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by bxb100**
## Type of change

- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

fix #7126 

## Code changes

**apps/cli/src/commands/list.command.ts:** sync run `this.eventCollectionService.collect`

the execution stack is:

https://github.com/bitwarden/clients/blob/77c54c2765fac5ca9040fbc279654eb47caaa2f8/libs/common/src/services/event/event-collection.service.ts#L36

https://github.com/bitwarden/clients/blob/77c54c2765fac5ca9040fbc279654eb47caaa2f8/libs/common/src/vault/services/cipher.service.ts#L262-L263

https://github.com/bitwarden/clients/blob/77c54c2765fac5ca9040fbc279654eb47caaa2f8/libs/common/src/platform/services/state.service.ts#L1751

https://github.com/bitwarden/clients/blob/77c54c2765fac5ca9040fbc279654eb47caaa2f8/libs/common/src/platform/services/state.service.ts#L3011

https://github.com/bitwarden/clients/blob/77c54c2765fac5ca9040fbc279654eb47caaa2f8/apps/cli/src/platform/services/lowdb-storage.service.ts#L118

obviously `proper-lockfile` `lock` showed the error is typically lock race

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by ttalty — APPROVED** [review]
This fixes the issue on the lock file being held.

**Comment by ttalty** [comment]
Thank you for the contribution! This PR has been approved and is moving to QA for testing.

**Comment by Geezus42** [comment]
When will the release be cut? I've already delt with a broken work flow for a week, is it going to be two? It's not a good sign that this was not caught by your QA.

**Comment by jabofh** [comment]
Since I'm still struggling with this issue, have you any idea when it'll be generally available?

``` console
❯ macosver
10.16
❯
❯ ./bw --version
2024.2.0
❯ 
❯ time ./bw list items --session "$( cat ~/.bw_session )" > /dev/null
./bw list items --session "$( cat ~/.bw_session )" > /dev/null  75.39s user 18.67s system 151% cpu 1:02.10 total
❯ 
```

Still not the 5 seconds it takes on my Fedora box...

**Comment by bxb100** [comment]
you may need to check `lowdb/adapters/FileSync` how to prolong the execution

**Pull request merged**
