### PR TITLE
[PM-8098] Remove deprecated factory methods

### PR DESCRIPTION
**Pull request by MGibson1**
Note: Some of the init code here will be usable in the future for a different dependency framework.

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Removes deprecated dependency creation factory methods. We have chosen to not go in this direction for manifest v3. Eventually we will use some other dependency management framework to enable runtime jit creation of our services in non-angular contexts.

Some of the listener registration code will be useful in the future, but we can look back here when that time comes, there's no reason to assume they'll be useful in the interim and work to keep.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by ike-kottlowski — DISMISSED** [review]
Auth changes are good.

**Review by LRNcardozoWDF — DISMISSED** [review]

**Review by cagonzalezcs — APPROVED** [review]
Looks good to me

**Review by dani-garcia — APPROVED** [review]

**Review by addisonbeck — APPROVED** [review]

**Review by dani-garcia — APPROVED** [review]

**Review by audrey-jensen — COMMENTED** [review]
issue ⚠️ - broken build; looks like the last merge pulled in [a new factory method for the PIN service](https://github.com/bitwarden/clients/blob/ps/remove-browser-factory-methods/apps/browser/src/auth/background/service-factories/pin-service.factory.ts) that broke Chromatic. 

question ❓ - Was this code never used, or is there a new place these dependencies need to be registered? I have some code in #8998 that I'll need to adjust, and need to know if I missed a registration site.
answer ❗ - This code was never live.

**Comment by MGibson1** [comment]
@audrey-jensen thank you, was due to a bad merge where I failed to remove a new factory.

As for how these were used, they were a backup initialization method for a few background tasks. The source of services is currently and after this PR will still be the `MainBackground` class. If your class is used in the background, you'll have to register it on that class, but it should be a compile time error.

**Review by audrey-jensen — APPROVED** [review]
Thanks @MGibson1!

**Review by dani-garcia — APPROVED** [review]

**Review by justindbaur — APPROVED** [review]

**Review by jlf0dev — APPROVED** [review]

**Review by LRNcardozoWDF — APPROVED** [review]

**Review by jprusik — APPROVED** [review]
BIT run:
https://github.com/bitwarden/browser-interactions-testing/actions/runs/9130296331

**Review by eliykat — APPROVED** [review]

**Pull request merged**
