### PR TITLE
Auth/pm-6188/move-two-factor-service-to-popup

### PR DESCRIPTION
**Pull request by MGibson1**
Login does not occur outside of the angular context, no need for it in the background.

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Iterative work on removing direct access of the browser extension background page from angular.

This moves `TwoFactorService` and `LoginStrategyService`, neither of which is otherwise needed in the background.

## Code changes

- **removal of `init`**: `init` is a useful pattern when we have async work to do to initialize a service, but if that work is syncronous it's better placed in the constructor.
- **Move to services**: This is a simple lift and shift that specifies injection dependencies of the two classes and removes them from the background.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by justindbaur — COMMENTED** [review]
I never want to fight for the removal of an `init` method but are you sure about this one? My feeling was it was an init method and places after `I18nService`'s initialization so that it was sure to get the translations for the users selected locale? Is this probably saved by the fact that with its removal from background it will never be initialized before `InitService` has ran?

Also, I feel like this service probably has a bug by saving translations like this. If the user ever changes their local after having created this service once then the two factor options likely never get the updated translations. Either the translation should be moved to the component template or this service should still have some job in the `InitService` to start a subscription of listening for local changes.

**Comment by MGibson1** [comment]
>My feeling was it was an init method and places after I18nService's initialization so that it was sure to get the translations for the users selected locale

All initializer methods should run in the init service or the app compenent itself, so we shouldn't be able to call non-init services until those are run, correct?

>If the user ever changes their local after having created this service once then the two factor options likely never get the updated translations

translation changes mid-execution actually aren't supported anyway in angular -- it's kind of just the setting of pipe locales for things like dates and money, but all of our applications require a reload to update language settings.

**Comment by justindbaur** [comment]
> All initializer methods should run in the init service or the app component itself, so we shouldn't be able to call non-init services until those are run, correct?

This change will work in non-angular clients, but it would pretty silently fail if someone down the road injects `TwoFactorService` into `InitService` for another reason. Also, since CLI creates the service before it calls `I18nService.init` it would fail to get any translations. 

> translation changes mid-execution actually aren't supported anyway in angular

Didn't know that, but still feels like this is longer term a presentation layer concern. That would make my CLI concern moot but I'm also not saying we do that now. Maybe a `refreshTranslations()` method that is called in the constructor but CLI also calls it manually post `I18nService.init`?

**Comment by MGibson1** [comment]
CLI doesn't translate, it's always english (for now)

**Review by justindbaur — APPROVED** [review]
Thanks for the discussion.

**Comment by jlf0dev** [comment]
Pulled this down and tested, getting some weird behavior using Duo login where you popout the extension.

https://github.com/bitwarden/clients/assets/24985544/40af45c7-3482-4e10-b229-652eb793eca8

**Comment by jlf0dev** [comment]
Spoke about this and should be good to go once merged with latest from `main`!

**Comment by jlf0dev** [comment]
This has moved to #8820

**Pull request closed without merging**
