### PR TITLE
[PM-6749] Check MasterPassword in web app during change

### PR DESCRIPTION
**Pull request by Timshel**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Check the current master password client side during the change master password logic:
 - Prevent sending new valid key when the user inputted an invalid current master password.
 - Allow for faster feedback since it can be done before spending time computing the hash.

## Code changes

Replace the `getOrDeriveMasterKey` by `makeMasterKey` to ensure that the master key is computed from the user input and not retrieved from the store.
Add `decryptUserKeyWithMasterKey` to short circuit the rest of the logic if the user inputted an invalid current password.

Was playing with the client code and though this could be worth it, no idea if you are interested in such modifications.
Have a nice day :).

### CODE REVIEW

**Comment by rr-bw** [comment]
Thanks @Timshel! Could you please sign the CLA? https://contributing.bitwarden.com/contributing/#contributor-agreement

**Comment by Timshel** [comment]
@rr-bw I have no issue to sign the CLA but waiting for some feedback on the PR first.

**Comment by Timshel** [comment]
Hey,
Wanted to know if the fact that I did not yet sign the CLA is blocking review ?
As mentioned I don't really mind signing it but would prefer not to communicate personal information if there is no interest.

**Comment by rr-bw** [comment]
@Timshel No that's fine. I've just been focusing on a very large task the last few weeks, hence the delay.  I can almost certainly review later this week.

**Comment by rr-bw** [comment]
@Timshel Thanks for this, the team really likes it!

One merge conflict since we recently updated our `KdfConfigService` such that `makeMasterKey()` now only takes 3 arguments.

Should be as simple as merging latest from `main` and then updating that call to:

```typescript
const masterKey = await this.cryptoService.makeMasterKey(
  this.currentMasterPassword,
  await this.stateService.getEmail(),
  await this.kdfConfigService.getKdfConfig(),
);
```

With that in place, and signed CLA, I'll be able to approve.

**Comment by Timshel** [comment]
Done :)

**Review by rr-bw — APPROVED** [review]
Approved! Thanks again for this. I do have to wait until Monday to merge due to our SDLC.

**Comment by rr-bw** [comment]
@Timshel Thanks again for this work! QA approved and merged.

**Pull request merged**
