### PR TITLE
[PS-1029] Browser: suppress `user-select` for most interface elements

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

For a native-like experience (which also applies to extensions, which pretend/mimic being part of the browser UI), it would make sense to suppress user selection/highlighting for most of the interface (with the exception of text/content that a user may wish to actually select and copy).

Currently, most of the interface is selectable. A few examples:

initial login view, with all text selected and highlighted

lock/login view, with all text selected and highlighted

My Vault view, with all text selected and highlighted

Cipher/item view, with all text selected and highlighted

Send view, with all text selected and highlighted

Generator view, with all text selected and highlighted

Settings view, with all text selected and highlighted

Export Vault view, with all text selected and highlighted

Log Out dialog, with all text selected and highlighted

While this makes sense for a website, it does feel slightly unpolished for an app. This PR rather brutally (and admittedly a bit clumsily) suppresses user-select for most interface text/components, leaving only things like the actual bits of data (when viewing a cipher, for instance) as selectable.

This is a matching copy of https://github.com/bitwarden/clients/pull/2650

## Code changes

- **/apps/browser/src/popup/scss/misc.scss:** added `user-select:none` targeting a series of (generic, all the way to very specific) selectors

## Screenshots

Examples after this PR:

Unlock/login view, with only the input values highlighted

Cipher/item view, with only the values highlighted

Cipher/item view detail - the "Updated: ..." text right at the end is also highlighted

Generator view, with only the generated password, Number of Words value, and Separator value highlighted

Export Vault view, with only the .json format text highlighted

## Testing requirements

- select using either the mouse, or just hitting Ctrl+A, to see all the content that is and isn't selected/highlighted

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by danielleflinn** [comment]
The updated screenshots look as expected to me. @djsmith85 since you reviewed the the desktop PR for this (https://github.com/bitwarden/clients/pull/2650) can you take on code review?

**Comment by patrickhlauke** [comment]
noticed a few more straggler `.box-footer`s that shouldn't really be selectable, so took a different approach - instead of listing the cases where they shouldn't be selectable, turned it around and special-cased the one time where I thought it *was* appropriate to have it selectable (in the cipher/item view). did the same in the desktop one https://github.com/bitwarden/clients/pull/2650#issuecomment-1122991996

**Comment by danielleflinn** [comment]
Ran locally and tested selectable content; works as expected.

**Review by djsmith85 — APPROVED** [review]
@patrickhlauke This is looking good. Thank you again for your contributions and patience.

**Comment by patrickhlauke** [comment]
no worries, my pleasure as always :shipit:

**Pull request merged**
