### PR TITLE
[PM-3363] Implement keyboard arrow navigation for the browser extension & other hotkeys

### PR DESCRIPTION
**Pull request by quexten**
## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Since https://github.com/bitwarden/clients/pull/1962 seems to never have gotten rewritten, I gave it a shot using a11y's FocusKeyManager. Before spending too much time on this, I wanted to confirm with @eliykat that this is the approach to move forward with (since he also reviewed https://github.com/bitwarden/clients/pull/1962 at the time).

~~The PR is not ready and missing some stuff, but the basic approach for navigating the vault entries should be solid.~~
Edit: Also added some other hotkeys as listed in the first post below. This also picks back up https://github.com/bitwarden/clients/pull/1961.

## Code changes
- navigatable-list.component.ts/.html: This component uses a11y focus manager to make any list of components (navigatable-list-item) keyboard navigatable
- navigatable-list-item.component.ts/html: This component is used to wrap any element that should bey keyboard navigatable. F.e if a button should be keyboard navigatable, one would write:
```html
<navigatable-item>
  <button>
  </button>
</navigatable-item>
```
- cipher-row.component.ts: Change the tabindex so that the entire cipher row gets highlighted instead of just the label; Add hotkeys for copying totp/username/password/launching
- all other ts/html files: Wrap navigatable items & add nagitabable lists to make them navigatable
- for the ts/html files with a search field: Add the ctrl+f shortcut to jump to the search bar

## Screenshots
[Screencast from 2023-08-12 02-29-06.webm](https://github.com/bitwarden/clients/assets/11866552/67738675-612d-450d-9d02-223d7f4b5b04)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by quexten** [comment]
Added shortcuts for password (ctrl+p), username (ctrl+u), totp (ctrl+t) copy, for launching (ctrl+o) and for focusing the search bar (ctrl+f).
These are the same as on desktop.

[Screencast from 2023-08-12 02-29-06.webm](https://github.com/bitwarden/clients/assets/11866552/67738675-612d-450d-9d02-223d7f4b5b04)

**Comment by quexten** [comment]
Refactored the approach a bit so that it works with any elements, not just cipher-rows. Settings are also keyboard navigatable now (albeit the PR got a bit larger from this).

**Comment by eliykat** [comment]
Thanks @quexten ! I've raised this internally and our team is reviewing this. I've asked them to post any updates here.

**Comment by quexten** [comment]
Converted to draft because it's more for discussion about the approach and not merge ready.

**Comment by willmartian** [comment]
Hey @quexten, thank you for your work here. We have internal work planned to restructure a number of these pages and their underlying list components--part of which includes accessibility improvements that capture the goals of this PR. I think it is better to hold off on this to avoid duplicate efforts

**Comment by quexten** [comment]
Thanks for the note, Will. The PR was mostly meant as a starting point for discussion of which path to take anyways, and was nowhere near production ready. Looking forward to the accessibility improvements :)

**Pull request closed without merging**
