### PR TITLE
[PS-1830] Updated the autofill.js file to no longer add the 'data.com' attribute to tags

### PR DESCRIPTION
**Pull request by hkbertoson**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR is to resolve issue #725 

## Code changes

Removed ````addProp(field, 'userEdited', !!el.dataset['com.browser.browser.userEdited']);````

````
      document.addEventListener('input', function (inputevent) {
          inputevent.a !== false &&
              inputevent.target.tagName.toLowerCase() === 'input' &&
              (inputevent.target.dataset['com.bitwarden.browser.userEdited'] = 'yes');
      }, true);
````

- **autofill.js** Please see above

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by djsmith85 — CHANGES_REQUESTED** [review]
@hkbertoson: Thank you for your contribution!

I spoke with @eliykat about this, and we agree with the findings of @flexagoon and @hkbertoson, that the attribute `com.bitwarden.browser.userEdited` is no longer needed and can be removed.

Some manual local testing showed no negative side effects to the behaviour of auto-fill. 

1) Please add a comment on [line 45](https://github.com/bitwarden/clients/pull/4001/files#diff-b7224476182fa32e81e3ce5e8ec7fd01b87df8ca85d1d2f0efa622d740026412R45) describing your changes -> Something like "Remove setting of attribute `com.browser.browser.userEdited` on user-inputs" in case you don't have another suggestion
2) Remove empty [line 53](https://github.com/bitwarden/clients/pull/4001/files#diff-b7224476182fa32e81e3ce5e8ec7fd01b87df8ca85d1d2f0efa622d740026412R53)
3) Delete the commented out [line 278](https://github.com/bitwarden/clients/pull/4001/files#diff-b7224476182fa32e81e3ce5e8ec7fd01b87df8ca85d1d2f0efa622d740026412R278) 

@hkbertoson Please address my requested minor-changes and this should be good to pass this on to QA for testing.

**Comment by hkbertoson** [comment]
Got it updated. Thanks!

**Review by djsmith85 — APPROVED** [review]
@hkbertoson Wow, that was quick. Thank you for the quick turnaround. Changes are looking good and I will pass this on to QA.

**Comment by djsmith85** [comment]
@hkbertoson This has received approval from QA and is ready to get merged. Thank you for your contribution 👍 This will be included in an upcoming release.

**Pull request merged**
