### PR TITLE
[PM-11475] Move process reload ownership to key-management

### PR DESCRIPTION
**Pull request by quexten**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11475
https://bitwarden.atlassian.net/browse/PM-11961

## 📔 Objective

Move process reload ownership to key-management. This creates a new service "process reload service" which pulls out the proc reload functionality of the system service.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by dani-garcia — APPROVED** [review]

**Review by mzieniukbw — COMMENTED** [review]
The `libs/common/src/key-management` is not part of CODEOWNERS file for this PR.
Is this going to be added to this PR or the #10818 ?

**Comment by quexten** [comment]
> The `libs/common/src/key-management` is not part of CODEOWNERS file for this PR. Is this going to be added to this PR or the #10818 ?

Yeah, that was the plan. I'm wondering whether it might be better to make the codeowner changes first, so that this PR is unblocked though..

**Comment by quexten** [comment]
> The `libs/common/src/key-management` is not part of CODEOWNERS file for this PR. Is this going to be added to this PR or the #10818 ?

Created this PR to unblock: https://github.com/bitwarden/clients/pull/10988

**Comment by mzieniukbw** [comment]
> > The `libs/common/src/key-management` is not part of CODEOWNERS file for this PR. Is this going to be added to this PR or the #10818 ?
> 
> Created this PR to unblock: #10988

The `libs/common/src/key-management` is **STILL** not part of CODEOWNERS file for this or other PRs

**Comment by quexten** [comment]
> > > The `libs/common/src/key-management` is not part of CODEOWNERS file for this PR. Is this going to be added to this PR or the #10818 ?
> > 
> > 
> > Created this PR to unblock: #10988
> 
> The `libs/common/src/key-management` is **STILL** not part of CODEOWNERS file for this or other PRs

Not sure if it was because of updating the branch by merging main, but in the code review, the files do show under "owned by you" for me. Is this not the case for you?

**Comment by mzieniukbw** [comment]
> > > > The `libs/common/src/key-management` is not part of CODEOWNERS file for this PR. Is this going to be added to this PR or the #10818 ?
> > > 
> > > 
> > > Created this PR to unblock: #10988
> > 
> > 
> > The `libs/common/src/key-management` is **STILL** not part of CODEOWNERS file for this or other PRs
> 
> Not sure if it was because of updating the branch by merging main, but in the code review, the files do show under "owned by you" for me. Is this not the case for you?

Ah apologies, i have missed it in #10988 🙇 All good then!

**Review by mzieniukbw — APPROVED** [review]
LGTM!

**Comment by quexten** [comment]
QA approved, just resolved conflicts.

**Pull request merged**
