### PR TITLE
[CL-395] Add and use art colors in svgs

### PR DESCRIPTION
**Pull request by vleague2**
## 🎟️ Tracking

[CL-395](https://bitwarden.atlassian.net/browse/CL-395)

## 📔 Objective

As part of the extension refresh redesign, we are updating some color variables. We will begin using `art-` color variables for SVGs to more semantically separate them from other app colors. This PR adds the variables and assigns them to the existing color that is being used (i.e. `art-primary` is replacing `text-headers`, so it is set to the same color value as `text-headers`, and same for `art-accent` replacing `info-600`). There should be no visible user-facing changes at this point.

In the extension refresh feature branch, these color values will get updated to the new ones.

Please use the `art-` values for SVGs going forward!

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[CL-395]: https://bitwarden.atlassian.net/browse/CL-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by shane-melton — DISMISSED** [review]
Really appreciate this change and no longer needing to "guess" / remember which text class is appropriate for SVGs! 🎉  

Relatedly, we have a couple SVGs with `tw-fill-danger-600` and `tw-fill-secondary-300`. Would it also be beneficial for those have their own separate `art-*` colors as well?

**Review by JaredSnider-Bitwarden — APPROVED** [review]

**Review by merissaacosta — DISMISSED** [review]
looks good with `tw-fill-info-600` -> `tw-fill-art-accent` and `tw-fill-text-headers` -> `tw-fill-art-primary`

**Comment by vleague2** [comment]
> Really appreciate this change and no longer needing to "guess" / remember which text class is appropriate for SVGs! 🎉
> 
> Relatedly, we have a couple SVGs with `tw-fill-danger-600` and `tw-fill-secondary-300`. Would it also be beneficial for those have their own separate `art-*` colors as well?

Good question!! I will check with design!!

**Review by djsmith85 — APPROVED** [review]
Send icons are looking good.

With https://github.com/bitwarden/clients/pull/10921 we introduced `libs/tools/generator/components/src/icons/no-credentials.icon.ts`which I was missing here. It seems though,that it's not using the classes at all which we'll need to fix.

**Comment by vleague2** [comment]
@shane-melton The other colors will be addressed in an upcoming project to revamp all the icons.

@djsmith85 Thank you for creating that! Good to get that file updated so it will receive the color updates when the feature branch is merged!

**Review by JaredSnider-Bitwarden — APPROVED** [review]

**Review by merissaacosta — APPROVED** [review]

**Pull request merged**
