### PR TITLE
[AC-1632] Remove sm-ga-billing feature flag

### PR DESCRIPTION
**Pull request by eliykat**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Remove the feature flag for Secrets Manager billing now that the feature has launched.

Pairs with https://github.com/bitwarden/server/pull/3254.

## Code changes

- **file.ext:** Description of what was changed and why

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by Hinton — APPROVED** [review]
I presume we'll keep the flag around until reasonable time has elapsed to prevent existing clients from breaking?

**Comment by withinfocus** [comment]
> I presume we'll keep the flag around in the config endpoint until reasonable time has elapsed to prevent existing clients from breaking?

That's the expectation per the tech debt process with feature flags. I see the task attached here but there should be a corresponding server change on a delay.

**Comment by eliykat** [comment]
@Hinton / @withinfocus this feature flag only affected the cloud web vault. (It gated signup/subscription management capabilities which are not present in other clients or self-hosted.) Because web vault and server are released at the same time, is a delay required for the server changes? The intention was to totally remove the feature flag from the code all at once. It can remain in LaunchDarkly though.

**Comment by Hinton** [comment]
I can't find any references to the flag on server, I think we just send down whichever flags exists in launch darkly. So I think this means keeping the flag in launch darkly for a while (but since it's web only that time frame is much shorter)

**Comment by withinfocus** [comment]
@Hinton @eliykat since LD acts as a black box in a sense we can't ask it for flag keys, just values based on known key names. This means constants need to be maintained on the server or that entry won't be returned in config API calls.

Since it's just the cloud web vault that we control, this should be safe to remove at the same time assuming a release at the same time.

**Review by cyprain-okeke — APPROVED** [review]
LGTM

**Review by withinfocus — APPROVED** [review]

**Review by Hinton — APPROVED** [review]

**Pull request merged**
