### PR TITLE
Restore full extension window size in Safari (revert workaround from #1531)

### LINKED ISSUE #1692: [1.49.0] Safari with square window, opening delay, wrong button focus and missing Biometrics option
### Not fixed

⚠️  Since the recent 1.49.0 update the Safari extension now has a square window instead of a rectangular like in other browsers.

### Fixed

These bugs have been fixed and are no longer the focus of this ticket:

✅ (fixed with Safari 15)
Opening the window takes almost 3 seconds.

✅ (fixed)
The announced unlock with Biometrics option for this update is also missing. In Chrome it works for me.

✅ (fixed with Safari 15)
Also there is this glitch next to the popout icon:
Bildschirmfoto 2021-03-13 um 01 13 21

## Expected Result

⚠️ A rectangular window
✅ No delay between clicking and opening the window
✅ Unlock with Biometrics option
✅ Popout icon without glitch like this:
Bildschirmfoto 2021-03-13 um 01 23 14

## Actual Result

⚠️ A square window
3 seconds delay between clicking and opening the window
Unlock with Biometrics option is missing
A glitch next to the popout icon

## Environment

- Operating system: macOS Big Sur 11.2.3
- Browser: Safari 14.0.3
- Build Version (go to "Settings" → "About" in the app): 1.49.0

### PR DESCRIPTION
**Pull request by eliykat**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When we converted to using Safari App Extensions, we had UI flickering/refresh issues in the bottom half of the extension window. As a workaround, we limited the window height in https://github.com/bitwarden/clients/pull/1531.

There are reports in the tracking issue #1692 that the issue has now been solved. A quick test looks good to me. This PR reverts the workaround, but we'll get QA to give it a good going over before merge.

Closes #1692.

## Code changes

- **apps/browser/src/popup/scss/environment.scss** - revert Safari-specific styling that affects the dimensions of the `body` element.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by djsmith85 — APPROVED** [review]
@eliykat I'm glad this has finally been resolved upstream, and we can take out these limitations.

**Review by Hinton — CHANGES_REQUESTED** [review]
I think we'll want to check the safari version since the issue still exists for older versions and we're going to get a lot of reports on this otherwise. I started writing some code for this before I got sidetracked with everything else 😢 https://github.com/bitwarden/clients/commit/fbadcb08fce28c23c35f75baeba1c1a234435e8e

**Comment by djsmith85** [comment]
> I think we'll want to check the safari version since the issue still exists for older versions and we're going to get a lot of reports on this otherwise. I started writing some code for this before I got sidetracked with everything else 😢 [fbadcb0](https://github.com/bitwarden/clients/commit/fbadcb08fce28c23c35f75baeba1c1a234435e8e)

Good call, I had not thought about all the older Safari versions in use.

**Comment by eliykat** [comment]
Good point. @Hinton would you like to create a PR for your changes instead?

**Comment by eliykat** [comment]
Discussed with @Hinton, we'll revisit this in January (after the break) and work on a fix that accommodates older Safari versions.

**Comment by accolon** [comment]
Any news on this?

Catalina (a.k.a. macOS 10.15) has not received updates since July 2022, for example Microsoft dropped support for MS Office on Catalina last November. Safari 15 received its last update in August 2022.

macOS 11, 12 and 13 all have Safari 16.3 now.

While I understand some people might continue using unsupported OS versions and browsers, I personally don't think it is safe to do so. I'd love to see this fix enabled on current Safari versions, even at the expense of losing support of discontinued old versions.

**Comment by eliykat** [comment]
We've discussed that option internally, it's tempting but I still think we should err on the side of backwards compatibility for those users, at least for a little while longer.

No updates yet but I'll see if I can pick up @Hinton's work in progress soon, or pass it on to the team that has code ownership of this area if I don't have time myself.

**Comment by eliykat** [comment]
I'm handing this ticket to the appropriate team to work on. I'm not sure that parsing the UserAgent string is a good idea, and my focus is on other work at the moment so I don't want it to get held up on my account.

**Pull request closed without merging**
