### PR TITLE
[PM-7878] PopupSectionHeader component

### PR DESCRIPTION
**Pull request by nick-livefront**
## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adds a new PopupSectionHeader component to be used within the browser extension refresh 

## Code changes

- **popup-section-header.*** 
  - Implementation of heading component & associated stories
  - I followed the implementation pretty closely that is in [PM-7878](https://bitwarden.atlassian.net/browse/PM-7878).
    - With the each title slot having to implement `noMargin class="tw-mb-0"` would this be better off as an input rather than a slot?

## Screenshots

Screen Shot 2024-05-09 at 15 16 46 PM

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

[PM-7878]: https://bitwarden.atlassian.net/browse/PM-7878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by shane-melton** [comment]
>With the each title slot having to implement noMargin class="tw-mb-0" would this be better off as an input rather than a slot?

@nick-livefront Yeah, I'm of the opinion that consumers shouldn't have to concern themselves with the internal margins, so I think an input makes sense. However, if that's the case then we will need another slot for immediately after the title so we can add additional buttons. (per my [comment in Jira](https://bitwarden.atlassian.net/browse/PM-7878?focusedCommentId=57703))

@willmartian What do you think?

**Comment by shane-melton** [comment]
Also, ideally we wouldn't need to specify the typography for the title and trailing text portions. But, that is just from Vault's perspective and I don't know if there may be future use cases where we want/need that flexibility elsewhere.

**Comment by shane-melton** [comment]
@willmartian 

> Thoughts on this usage?
> 
> ```
> <popup-section-header title="Foobar">
>   <ng-container slot="start">...</ng-container>
>   <ng-container slot="end">...</ng-container>
> </popup-section-header> 
> ```
> 
> Edit: we could also do something like `slot="title-suffix"` if that is clearer than `slot="start"`

I like it! And +1 for `title-suffix` slot!

Only other small concern is styling for the trailing text. Its not a big deal to add the `bitTypography="body2"`, but maybe we can have a directive or something specific to the `popup-section-header` to apply that for us?

**Comment by nick-livefront** [comment]
> Only other small concern is styling for the trailing text. Its not a big deal to add the `bitTypography="body2"`, but maybe we can have a directive or something specific to the `popup-section-header` to apply that for us?

This is could also apply to the trailing button too. I used css `has` to apply negative margin so the button aligns properly with the title. This could also be wrapped into a directive, maybe a single directive `popupSectionHeaderSuffix`, `popupSectionHeaderTrailingContent`, those are kind of a mouthful 😄

**Comment by nick-livefront** [comment]
> Only other small concern is styling for the trailing text. Its not a big deal to add the `bitTypography="body2"`, but maybe we can have a directive or something specific to the `popup-section-header` to apply that for us?


@shane-melton I gave this a try and I think it's possible using the [Directive Composition API](https://angular.io/guide/directive-composition-api#adding-directives-to-another-directive) but the `TypographyDirective` would need to be a standalone directive to accomplish it. Do you think that's worth pursing + the cascading changes?

In my opinion that is a large refactor in order to not have to write the `typography` directive on the span. I'll rely on your experience because the benefits long term could far outweigh the work now! 

```ts
@Directive({
  standalone: true,
  selector: "[popupSectionHeaderEnd]",
  hostDirectives: [{
    directive: TypographyDirective,
    inputs: ["bitTypography: body2"]
  }]
})
export class PopupSectionHeaderEndDirective {}
```

**Review by shane-melton — APPROVED** [review]
This seems good to go from Vault's perspective! Thanks @nick-livefront!

**Comment by nick-livefront** [comment]
@willmartian When you have time could you give this a review?

**Review by willmartian — DISMISSED** [review]
> I think adding the typography directive manually is fine for now and perhaps we can revisit in the future.

Agree. This lgtm, thanks @nick-livefront!

**Comment by danielleflinn** [comment]
@nick-livefront can you update the Storybook to use an `icon-button size="small"`?

**Review by shane-melton — APPROVED** [review]

**Review by willmartian — APPROVED** [review]

**Review by danielleflinn — APPROVED** [review]
Looks great! Thanks for making that tweak

**Pull request merged**
