### PR TITLE
[PM-2083] Subdomains exclusion

### PR DESCRIPTION
**Pull request by jotak**
## Type of change

- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Feature request to allow all subdomains exclusion, based on domain suffix

See also: https://community.bitwarden.com/t/excluded-sub-domains/30985

Note: I'm not sure if backward compatibility would be expected for excluded domains, ie by default NOT excluding all subdomains when a specific excluded domain is set. If so, probably there could be a checkbox in the domain exclusion config screen, to explicitly ask for turning this feature on.
I can try to do that if requested, however would appreciate some guidance.

## Code changes

In `notificationBar.ts`, instead of checking for the whole hostname in excluded domains, checks that hostname `endsWidth` any of the excluded domains.

## Screenshots

n/a

## Testing requirements

non-regression on excluded domains / eventually add new test cases for subdomains exclusion.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [x] This change requires a **documentation update** (notify the documentation team) => https://bitwarden.com/help/exclude-domains/
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by jotak** [comment]
hey , any chance to have a review on this? Thanks

**Comment by gdlx** [comment]
@djsmith85 More than a year since @jotak updated his branch 11 minutes after you requested it and nothing happened...

**Comment by mauricioklein** [comment]
This is very needed.

It's super annoying having to dismiss these popups all the time (those who uses Gitpod knows the pain it's)

**Comment by micahblut** [comment]
@jotak thank you for your contribution. As implemented, we will not merge this feature. Rather than making subdomain exclusion the default behavior, I think following our community member's suggestion of implementing some sort of wildcard (*.example.com) would be a more flexible solution.

**Comment by zevisert** [comment]
Is there another PR for this using Regex yet?  Nothing new is referencing this PR since it's been closed.. I'd be happy to contribute the feature if not

**Comment by ibcht** [comment]
> Is there another PR for this using Regex yet? Nothing new is referencing this PR since it's been closed.. I'd be happy to contribute the feature if not

Maybe wildcard domain exclusion would be a simple yet powerful addition, regex might be overkill I don't know. Anyway, I would personaly love such kind of feature to exclude any applications hosted under a corporate subdomain.

**Comment by martinbra** [comment]
A wildcard would also benefit those who access devices by their IPs , i.e.: "10.42.0.*"

**Comment by ForsakenRei** [comment]
> Is there another PR for this using Regex yet? Nothing new is referencing this PR since it's been closed.. I'd be happy to contribute the feature if not

I would like to see a wildcard option as well, besides the ip address example above and some of my self-hosted services, there are a lot other cases for example Citibank they can have different subdomains and I don't want to click them every time.

**Pull request closed without merging**
