### PR TITLE
[PM-8204] V2 Folder View

### PR DESCRIPTION
**Pull request by nick-livefront**
## 🎟️ Tracking

[PM-8204](https://bitwarden.atlassian.net/browse/PM-8204)

## 📔 Objective

- Add Extension Refresh Folder functionality
  - Adding a new folder is accessible via the "New Item" dropdown in the popup header
  - Swap in a new Folder page for extension refresh
  - All Folder logic is contained `AddEditFolderDialogComponent`. 
    - I didn't see a technical reason to where the logic here had to be separated out. I'd imagine that another platform could use the same component if needed. I missed something here, let me know!
   - Added tests to all components touched.

## 📸 Screenshots

|Empty State -> New Folder|Edit Folder -> Delete Folder|New Folder from Menu|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/01df8ca6-9145-40d6-8994-2ec489494aff" />|<video src="https://github.com/user-attachments/assets/96ce6a09-828d-4232-9e51-85c064deb863" />|<video src="https://github.com/user-attachments/assets/6377d00a-ff66-45fe-98ec-1f1a48c02fa2" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-8204]: https://bitwarden.atlassian.net/browse/PM-8204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Jingo88 — APPROVED** [review]

**Comment by nick-livefront** [comment]
@vleague2 @willmartian I added an icon here which requires your approval 😄 

If there's a better spot for the icon, let me know!

**Comment by willmartian** [comment]
> @vleague2 @willmartian I added an icon here which requires your approval 😄
> 
> If there's a better spot for the icon, let me know!

Perhaps it makes more sense to move this to `libs/vault`? Also `./deactivated-org.ts` and `./vault.ts`? Since they are all vault specific. 

I could also see the argument that all illustrations and icons are owned by the DS. I am fine either way.

cc @shane-melton

**Review by willmartian — APPROVED** [review]

**Comment by shane-melton** [comment]
I think having icons only used by Vault our ownership makes sense and created a ticket ([PM-10731](https://bitwarden.atlassian.net/browse/PM-10731)) to move the others to `libs/vault`

@nick-livefront Up to you if you want to move this one now. I already have it listed in the ticket above.

**Comment by nick-livefront** [comment]
@shane-melton I'll fast follow with that ticket and move the icons!

**Pull request merged**
