### PR TITLE
[PM-1176] Hovering over the `Learn More about auto-fill` link in the …

### PR DESCRIPTION
**Pull request by cagonzalezcs**
…browser extension does not change the cursor

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The main issue described in the ticket describes a link within the extension pop-out that is not changing the user cursor from the default cursor to a pointer cursor. This link can be found within the extension under Settings > Auto-Fill with the text "Learn more about auto-fill". 

A side issue was identified where the link was not able to be tabbed into by keyboard navigation, and was a result was inaccessible to users who navigate by keyboard. 

## Code changes

- **apps/browser/src/popup/settings/autofill.component.html**: I have modified the anchor element by removing the programmatic opening of the new window and replaced this methodology with a native `href` implementation. This allows the browser to interpret the `<a>` element as a valid link, which applies the correct default styling on hover of the element (showing the cursor pointer). I have also added `target="_blank"` and `rel="noopener noreferrer"` values to the link to have the link open in a new tab in the same manner as we had done originally (programmatically).  Finally, I have added an icon indicating to the end user that this link will open in a new tab, similar to the button used for the "Auto-fill keyboard shortcut" button. This presents a distinct UI change, and design will need to sign off before this can be merged in. As a side note, I have added an `aria-label` attribute to icon that states "Opens in a new window". 

- **apps/browser/src/popup/settings/autofill.component.ts**: I have removed the `AboutAutofill` method from the component's typescript logic. From my understanding, this method is not used elsewhere in the implementation. 

- **apps/browser/src/_locales/en/messages.json**: Translation for "Opens in a new window" has been added.

## Screenshots

https://user-images.githubusercontent.com/16629865/234974911-1bef4209-c7ba-4869-9c7c-36cb62c3ed9e.mov

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by differsthecat — APPROVED** [review]
This looks good from a dev side, I'd just like @danielleflinn 's opinion on the design changes 🙂

**Review by danielleflinn — APPROVED** [review]
Amazing! Thank you @cagonzalezcs for for jumping on this and making it accessible.

**Comment by djsmith85** [comment]
@cagonzalezcs: Regarding translating the aria-label: If possible, the source string "opens in a new window" would need to be added to `apps\browser\src\_locales\en\messages.json` and then used with the i18n pipe like in the href above ( `{{ "learnMoreAboutAutofill" | i18n }}`)

**Comment by cagonzalezcs** [comment]
@djsmith85 

I'll set that up and push the change up.Does this somehow (maybe through a Github action or somehow else) do an automatic translation of the text?

**Comment by djsmith85** [comment]
@cagonzalezcs: Every change to `en/messages.json`, once merged into master, is pushed to [Crowdin](https://crowdin.com/). Our amazing translation community then takes over and translates the source strings. Once a week we pull down the changes made in Crowdin into PRs which get reviewed.

https://contributing.bitwarden.com/contributing/#localization-l10n

**Comment by cagonzalezcs** [comment]
@djsmith85 

Understood, sounds good. I've added the translation content and ensured that it is propagating correctly within the extension popup.

**Review by djsmith85 — APPROVED** [review]
@cagonzalezcs Nice work on this and I can confirm that the translations are being picked up and get announced using a screen reader.

**Pull request merged**
