### PR TITLE
[PM-2714] Use `nullValidator` to accept 'No folder' while moving item

### LINKED ISSUE #5278: Can't move item from folder to 'No Folder'
### Steps To Reproduce

1. Open Bitwarden web vault
2. Create folder
3. Create item in the folder or move some existing item to the folder
4. Select the folder in left pane to see only items in that folder
5. Select the item using the checkbox
6. Click three dots in items list header and click `Move selected`
7. Select `No folder` in the combobox
8. Click `Save`

### Expected Result

Item should be moved to `No folder`. 

### Actual Result

Error `Input is required.` appears and item is not moved. 

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

Windows

### Operating System Version

Windows 11 22H2 (22621.1555)

### Web Browser

Brave

### Browser Version

Brave: 1.50.121, Chromium: 112.0.5615.138 

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by arifszn**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix #5278.

## Code changes

- **apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.ts:** Use `nullValidator` for folderId to accept No folder while moving. As `No folder`'s value is null.

## Screenshots

N/A

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by DatuStram** [comment]
Is this PR completely dead?

The pending reviewer—bitwarden/team-vault-dev—doesn't seem to exist anymore, it redirects to a 404 page…

It would be a real shame since this issue still persists as of Mars 16, 2024 😓

**Comment by arifszn** [comment]
@djsmith85 @djchateau can someone please take a look at it?

**Review by gbubemismith — APPROVED** [review]

**Comment by gbubemismith** [comment]
Hello @arifszn, Thanks for helping out with this bug. Everything looks good for approval, and I will move this to our QA team before merging.  Once again, thanks for your patience and time working on this.

**Comment by gbubemismith** [comment]
Hello @arifszn, this PR has been approved by our QA team, thanks once again for working on this.

**Pull request merged**
