### PR TITLE
Document missing/incorrect install requirements

### PR DESCRIPTION
**Pull request by UppaJung**
Having not had node-gyp already installed globally, I learned the hard way that it is actually a requirement while not documented in the README.  Presumably nobody noticed because everyone who had followed these instructions already had it installed.  (Fortunately, the `build-desktop.yaml` came to my rescue).

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Code changes

- **file.ext:** Description of what was changed and why

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by Hinton** [comment]
This seems a bit odd. I haven't had to install `node-gyp` globally on either of my machines. (Windows 10 and macOS). From the changes it looks like you are using another major version of node. While it's slightly misleading, the `or greater` part is meant to represent that we support `>= 16.13.1 < 17`.

**Comment by UppaJung** [comment]
> This seems a bit odd. I haven't had to install `node-gyp` globally on either of my machines. (Windows 10 and macOS). From the changes it looks like you are using another major version of node. While it's slightly misleading, the `or greater` part is meant to represent that we support `>= 16.13.1 < 17`.

@Hinton, I ran into the problem with node 16 as well.  The necessity of installing node-gyp globally to get this project to run on a fresh windows build seems to be implied by the fact that BitWarden's existing `build-desesktop.yml` file for your CI testing installs node-gyp globally on windows before calling `npm ci`.  If it's not necessary, why include that step?

https://github.com/bitwarden/clients/blob/2a11b2c534b53d082e0f9fae0c19fe9fcadd0408/.github/workflows/build-desktop.yml#L197

(Since the `build-desktop.yml` is used to install software dependencies on fresh OS installs before building, it's a great resource to check when building a `README.md` with instructions for manually installing dependencies before building.)

**Comment by Hinton** [comment]
That's mostly for legacy reasons. We needed it when we used node 14 and npm 7. I did a quick test commit and the CI pipelines doesn't seem to require it any longer. https://github.com/bitwarden/clients/commit/39ff8215825e73dcd9103bf85a49a590259d3ae7 https://github.com/bitwarden/clients/actions/runs/2319965471

**Comment by Hinton** [comment]
We no longer have any native dependencies so node-gyp should not be needed. And the documentation has moved to https://contributing.bitwarden.com. Closing this, but thanks for the shown interest.

**Pull request closed without merging**
