### PR TITLE
[PS-2217] No unsecured HTTP page warning for localhost

### PR DESCRIPTION
**Pull request by simon04**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

I'm storing passwords for local development servers (such as https://vitejs.dev/). I'm ware that those servers are not running HTTPS. I don't want so see the "unsecured HTTP page" warning when filling passwords.

## Code changes

- **file.ext:** Description of what was changed and why

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by djsmith85** [comment]
Hi @simon04 and thank you for your contribution.

Just wanted to clarify one thing: The reason you are seeing this warning message is that one of the URLs saved within that entry, that you are attempting to auto-fill, starts with `https://`on a site with `http://`.

```
- http://localhost
- https://someother.domain
Will show the warning 
```

```
- http://localhost
- http://someother.domain -> or deleting this URL
Will not show the warning
```

I'll pass this onto the team for review.

**Comment by vsergeenko777** [comment]
I faced the same problem, I have home routers that allow them to be accessed locally via HTTP and remotely via HTTPS, so I had to keep both of URI.

The real reason for this issue is indeed that the browser extension does not check HTTP addresses. I consider this a bug that needs to be fixed. And I do not consider the proposed changes to be a fix, at least there are many other local addresses besides 127.0.0.1, for example 192.168.0.0/16 or 172.16.0.0/12.

**Comment by micahblut** [comment]
Hi @simon04, thank you for your contribution. We recently refactored our URI matching code to make it more re-usable. Rather than this change adding a check for localhost and local ip, would you be interested in implementing a change to the `http` check so that it is passed only the matching URIs (instead of all saved URIs) and if any of them permit the `http` protocol, it does not show the warning?

**Comment by simon04** [comment]
> ...would you be interested in...

@micahblut, no. As a volunteer I cannot spend time on a PR that has been left rotting for three months, sorry. Feel free to adopt this PR or close it. I applied the workaround from https://github.com/bitwarden/clients/pull/4430#issuecomment-1376926811.

**Pull request closed without merging**
