### PR TITLE
[PM-12753] Desktop edit folder button visibility

### LINKED ISSUE #6811: Left Navigation Edit Folder Icon does not display on very long folder names
### Description of Issue

On MacOS desktop client Version 2023.9.1 (12289), if a very long folder name(especially with wide characters) appear in the `left-nav` DIV, `Edit Folder` icon does not display in the navigation bar.

1. Create a new folder with a name like `5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D`
2. Select the newly created folder in the Left Navigation bar and observe that the `Edit Folder` icon is not visible

### Expected Result

Edit Folder Icon is visible to users when any folder is selected under the FOLDERS filter in the left navigation.

### Actual Result

no-edit-folder-icon

### Screenshots or Videos

_No response_

### Additional Context

Potential workaround for the issue:

1. While desktop client is open, hit F12 key to bring up developer tools
2. Select the inspector icon from the top left corner (or hit CMD+Shift+c)
3. Highlight the left navigation bar to expose `<div class="left-nav">` HTML tag under the `Elements` tab and then select it
4. From the Styles window on the right locate `.left-nav {` CSS properties and uncheck `width` and `max-width` properties
css-edit

5. Left navigation bar will expand to display the full name of the longest folder
6. Locate the edge of the Edit Folder icon in the navigation bar and click it to expose the Edit Folder modal
expanded-nav

7. Click Delete icon in the modal
edit-folder-modal

### Operating System

macOS

### Operating System Version

Sonoma 14.0

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.9.1 (12289)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by alex-hammer11**
## 🎟️ Tracking

Github Issue: #6811 

## 📔 Objective
Fixes #6811 
Proposed fix for issue where the edit button would not be visible when the folder name was too long. The proposed change applies a max width to a filter button when selected, allowing the edit folder button to be visible.

## 📸 Screenshots
**Deselected:**
Deselected
Deselected close up

**Previous:**
Previous
Previous close up

**Proposed change:**
Proposed change
Proposed change close up

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by alex-hammer11** [comment]
Hello @djsmith85, sorry for reaching out to you directly but I saw that you edited this pull request. In addition to wanting to contribute to Bitwarden as a project, I'm also taking part in a university course in open source programming. This unfortunately means that contributions I make do have a deadline. I still plan to contribute to Bitwarden, but I fear that this project might not be the best from a course perspective. I'm well aware you have more pressing manners to attend than my community pr with a small fix of a max width, which is why I'm asking if you would recommend me to switch project from a course perspective as community PRs might be a while before they are reviewed? 😄

**Comment by djsmith85** [comment]
> Hello @djsmith85, sorry for reaching out to you directly but I saw that you edited this pull request. In addition to wanting to contribute to Bitwarden as a project, I'm also taking part in a university course in open source programming. This unfortunately means that contributions I make do have a deadline. I still plan to contribute to Bitwarden, but I fear that this project might not be the best from a course perspective. I'm well aware you have more pressing manners to attend than my community pr with a small fix of a max width, which is why I'm asking if you would recommend me to switch project from a course perspective as community PRs might be a while before they are reviewed? 😄

Hi @alex-hammer11, no problem. Thank you for your contribution!

I can't say anything about, if Bitwarden meets the requirements of your university course. I did reach out to the team-owning the vault-filters though and as you can see @Jingo88 has assigned himself. I can't promise any deadlines/when this gets reviewed, but it is currently queued up for review by the Vault team in their upcoming sprint.

Kind regards,
Daniel

**Comment by alex-hammer11** [comment]
@djsmith85 probably my description that was unclear, I was mainly asking about how frequently I might expect community-prs to be looked at. Upon second glance, that wasn't really clear in my original message and understandably difficult for you to answer. This should however be fine, so thank you for your help!

**Comment by alex-hammer11** [comment]
@Jingo88 Any update on this? 😄

**Comment by Jingo88** [comment]
Apologies for the slow response @alex-hammer11 . Everything looks good, and all builds passed. Gonna pass this to QA for a quick check and will keep you posted.

**Review by Jingo88 — APPROVED** [review]

**Comment by Jingo88** [comment]
QA Passed. Thank you for your contribution!

**Pull request merged**
