### PR TITLE
[PM-4333] [Defect] Unable to register passkey as primary authentication on google

### PR DESCRIPTION
**Pull request by coroiu**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Change transport to `internal` makes google happy. Shows up as "iCloud keychain"

## Screenshots
image

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by gbubemismith** [comment]
@coroiu, would this work with all relying parties?

**Comment by coroiu** [comment]
@gbubemismith I think so, I don’t understand why anyone would even look at this field, makes no sense to me 🤷

**Comment by gbubemismith** [comment]
> @gbubemismith I think so, I don’t understand why anyone would even look at this field, makes no sense to me 🤷

Yeah, I just discovered there's no `hybrid` in the [transport enum](https://www.w3.org/TR/webauthn-2/#enum-transport)

**Review by gbubemismith — APPROVED** [review]

**Comment by coroiu** [comment]
@gbubemismith Yeah.. it's in the draft for the next release https://w3c.github.io/webauthn/#enum-transport . New transports are supposed to be handled better though, I dunno. :shrug: `internal` is probably more correct anyways so :)

**Pull request merged**
