### PR TITLE
[SM-251] Migrate to new avatar component

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate all existing app-avatar to use the new bit-avatar for web. The old avatar is still used in 1 place within the desktop application. I've also updated all places to use the user, organization or provider id as the identifier. This should ensure each user has a unique color + it stays consistent.

## Screenshots

image
image
image
image
image

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by danielleflinn — APPROVED** [review]

**Comment by Hinton** [comment]
@danielleflinn I updated desktop to use the same logic for the avatars. This also removes gravatar support.

image

**Comment by differsthecat** [comment]
@BrandonM-Bitwarden Heads up, this may affect some of the work you are doing for SG-58. For example, the removal of gravatar support.

**Review by danielleflinn — APPROVED** [review]
This looks fine. Will the changes need to be re-worked after @BrandonM-Bitwarden finishes the PR related to the avatar color selector?

**Comment by Hinton** [comment]
@danielleflinn Yes, @BrandonM-Bitwarden will need to make the changes to both components.

**Review by differsthecat — APPROVED** [review]
LGTM 👍

**Review by differsthecat — APPROVED** [review]
New changes look good too 👍

**Pull request merged**
