### PR TITLE
[PM-8116] Auth Browser Refresh: Password Hint Component

### PR DESCRIPTION
**Pull request by rr-bw**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8116

## 📔 Objective

To create a refreshed and consolidated PasswordHintComponent for use on all clients, which will be used when the `UnauthenticatedExtensionUIRefresh` is on.

Notes:
- This PR included a couple of changes to the `AnonLayoutComponent`, which can be viewed in the [Storybook Diff](https://www.chromatic.com/test?appId=62a88a6de5b807fa98886113&id=66be6a02dd7a92125ad95557). Specifically:
  - [ [Diff 1](https://github.com/bitwarden/clients/pull/10492/files#diff-23fb1db36c4641a3c29f57ac7849752dc990f3d8bb9256f9f316b3448113ce88R19) ] - To align with [Figma](https://www.figma.com/design/3nTnAyNBMyBKOgvE5ATS5R/Auth-pages-refresh?node-id=137-5767&t=GQ8yXVeKN5LbSGK1-0), `pageTitle` and `pageSubtitle` section has been given a `max-width`.
  - [ [Diff 2](https://github.com/bitwarden/clients/pull/10492/files#diff-23fb1db36c4641a3c29f57ac7849752dc990f3d8bb9256f9f316b3448113ce88R1-R10) ] - To account for the headers on Browser and Desktop, the `AnonLayoutComponent` will adjust it's minimum height based on clientType. Otherwise the user is required to scroll down to see the `EnvironmentSelectorComponent`.

#### Web - feature flag ON 🟢

https://github.com/user-attachments/assets/3225c146-97f8-4d67-8d2b-c44fc52e2cb1

#### Extension - feature flag ON 🟢

https://github.com/user-attachments/assets/fbec0a74-df10-48ec-b1e5-a3867bac256d

#### Extension (popout window)  - feature flag ON 🟢

Notice we are persisting the email to the popout

https://github.com/user-attachments/assets/9b8eb0bf-c59a-4719-af67-cea8c5896531

#### Desktop  - feature flag ON 🟢

https://github.com/user-attachments/assets/8155b3e5-6d05-4f6c-9f28-b74b7954bcb3

### Feature Flag OFF 🛑

It's important to review the FF OFF versions because we want to make sure we get the routing correct.

#### Web - feature flag OFF 🛑

https://github.com/user-attachments/assets/6e9a5212-b30a-4fe3-8504-d7d55c7643d5

#### Browser - feature flag OFF 🛑

https://github.com/user-attachments/assets/c3e359c0-5491-4c48-9d47-cb9c3a0f02c3

#### Desktop - feature flag OFF 🛑

https://github.com/user-attachments/assets/2b09f8ba-779b-4f3e-ae85-93ba86298db1

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by rr-bw** [comment]
@quexten and @dani-garcia

I somehow made changes to [Cargo.lock](https://github.com/bitwarden/clients/pull/10492/files#diff-d03c04f976d7941f1dfbc45eda77f3677683f0972c0b8162260638e3fed57db5) and [/napi/index.d.ts](https://github.com/bitwarden/clients/pull/10492/files#diff-ce4037ceaf5d4efc292be74b262cbb88022d8e913160cb07c340391f55b41b15), despite never touching either of these files. Since this relates to Rust, I'm curious if you know what happened here?

**Comment by quexten** [comment]
My guess was the prettier pre-commit hook, but looking at the prettierignore file, desktop-native seems to be entirely excluded. @dani-garcia would probably know better if there are any automations on cardo deps or formatting. I don't see a harm in the changes though, especially if other PR's will encounter the same issue.

**Comment by rr-bw** [comment]
Note: per a private slack conversation, the changes in https://github.com/bitwarden/clients/pull/10492/commits/6e4fc608af2c480a6a1f1c921a03e5860de5dd83 are a temporary solution. Eventually we will refactor the `LoginEmailService` to use a state provider for the in memory email, instead of having a normal `email` property directly on the service.

**Comment by rr-bw** [comment]
@danielleflinn The new SVG has been added to all clients.

Screenshot 2024-08-16 at 9 16 56 AM

**Review by dani-garcia — DISMISSED** [review]
LGTM

The changes to Cargo.lock and napi/index.d.ts seem okay to me. The files probably got updated when you ran `npm run [electron|build]` for the desktop, as that rebuilds the Rust NAPI module. I can reproduce them in a clean copy of the repo.
- The napi/index.d.ts is autogenerated, my guess is one of the last times either @quexten or I updated the file, our editors formatted it and added that extra newline and we didn't notice. Now when you ran the command again the file got autogenerated again and the new line got removed.
- The Cargo.lock file is just adding a dependency that was missing, probably some dependabot update that missed it, strange but nothing to worry about.

**Review by quexten — DISMISSED** [review]

**Comment by rr-bw** [comment]
@dani-garcia @quexten Temporarily placing this back into Draft as I work on a [blocker](https://bitwarden.atlassian.net/browse/PM-11136) that resolves [this comment](https://github.com/bitwarden/clients/pull/10492#issuecomment-2293696405). Once I re-open it should be a relatively simple re-review.

**Comment by rr-bw** [comment]
@dani-garcia and @quexten This is open for re-review. Changes just involve merging `main` and incorporating changes regarding the `LoginEmailService`. See this [commit](https://github.com/bitwarden/clients/pull/10492/commits/a0130ea0d61921c533129e8c2103d17c1ab99558) and this [commit](https://github.com/bitwarden/clients/pull/10492/commits/c46f5850393b561a51476261b5751520a3ef8434) for changes. I tested all scenarios again and everything works, so I won't re-record videos.

**Comment by rr-bw** [comment]
@danielleflinn I added one small change to AnonLayout on this PR. I noticed that the `pageTitle` and `pageSubtitle` were stretching across the width of the screen. But I realized Figma has them contained with the rest of the content.

If you wouldn't mind reviewing, this [UI Review](https://www.chromatic.com/pullrequest?appId=62a88a6de5b807fa98886113&number=10492&activeElementId=comparison-test-key-6598735c67724ccc4e37da96-1200px&view=changes) displays the change.

**Comment by rr-bw** [comment]
@jtouchstonebw I added one small change to AnonLayout on this PR. The pageTitle and pageSubtitle were stretching across the width of the screen. But I realized Figma has them contained with the rest of the content.

If you wouldn't mind reviewing, this [UI Review](https://www.chromatic.com/pullrequest?appId=62a88a6de5b807fa98886113&number=10492&activeElementId=comparison-test-key-6598735c67724ccc4e37da96-1200px&view=changes) displays the change.

**Review by quexten — APPROVED** [review]
LGTM

**Pull request merged**
