### PR TITLE
[PM-3100] Fixes imports of "reduced" psono data

### PR DESCRIPTION
**Pull request by kuhnchris**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Recent exports of Psono were not being importable to BitWarden, as Psono changed their JSON Format to exclude/remove/not export fields that are not filled for entries. The importer did require them and failed horridly.

## Code changes

- **psono-json-importer-spec-ts**:  Added new reduced test
- **reducded-website-logins.ts**: contains the reduced data export, values rewritten for test purposes
- **psono-json-importer.ts**: fix "undefined" crash on not existing value
- **psono-json-types.ts**: optionallify autosubmit and urlfilter

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
[X] Added
- If this change requires a **documentation update** - notify the documentation team
[X] n/a
- If this change has particular **deployment requirements** - notify the DevOps team
[X] n/a
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
[X] n/a

### CODE REVIEW

**Comment by djsmith85** [comment]
Hi @kuhnchris and thank you for your contribution.

I tried exporting from the psono web client and haven't been able to reproduce the missing fields. Was the export done through a specific client?

Overall the changes you have made are looking good (always love seeing unit tests added), just want to verify the actual issue.

**Comment by kuhnchris** [comment]
Yes, my actual export of about 1 - 1 1/2 years of using psono was having troubles getting imported, hence I had to do the change.
I exported it with the official web client (not the plugin). It seems that they have been already migrated from GoPass into Psono before, hence maybe there were already missing fields during *that* migration, and Psono just kept the data as-is. Anyways, with this change I was able to import my ~200 entries from Psono into my productive database (export Psono -> Import Locally into the Bitwarden with the Change). Want me to provide you with a smaller read-life example with reduced credentials? (should be similar to the test one I added tho)

**Review by djsmith85 — APPROVED** [review]
@kuhnchris Thanks again for your contribution ❤️. Changes are looking good. Just one typo I'll be fixing within a file-name.

Passing this on to QA for testing and once they have given their approval this will be merged.

**Review by djsmith85 — APPROVED** [review]

**Comment by djsmith85** [comment]
@kuhnchris QA has approved your changes and they are ready to merge. Your changes will be included in the upcoming `2023.9`release.

**Pull request merged**
