### PR TITLE
[PM-7985] Add & Use InlineDerivedStateProvider

### PR DESCRIPTION
**Pull request by justindbaur**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Switch to use `InlineDerivedStateProvider` for browser because we are seeing some race conditions which cause the vault to not load in certain circumstances. 

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by cagonzalezcs — APPROVED** [review]

**Review by MGibson1 — APPROVED** [review]
It would be nice to delete the orphaned browser derived state implementations

**Comment by justindbaur** [comment]
@MGibson1 Are we 100% going to just stick with this? Or might we try and fix it?

**Comment by MGibson1** [comment]
I'd prefer to try and fix, but I also think that this method for establishing connections between derived state way too dependent on keeping the two contexts in lockstep. Feels like a totally new direction is needed.

**Comment by justindbaur** [comment]
Sounds good, I deleted them but we always have commit history if we want to revive them.

**Review by cagonzalezcs — APPROVED** [review]

**Review by coroiu — APPROVED** [review]

**Pull request merged**
