### PR TITLE
[CL-254] Rename 500 colors to 600 to prep for UI redesign

### PR DESCRIPTION
**Pull request by vleague2**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR should have no user-facing changes. It renames the Tailwind *-500 color variables to *-600 without changing any of their values. This change is pre-work for the extension refresh project, in which we will be updating the color palette of the component library to use primarily 600 colors in all of the places we currently use *-500. By renaming them now prior to changing values, we can ensure a smoother transition later to the new color values.

This does mean that, temporarily, the value of the *-600 colors in the codebase will NOT match the value of the *-600 colors in the design system. A comment has been left in the `tw-theme.css` file to explain this.

## Code changes

Everything should be simple renames.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by willmartian — APPROVED** [review]
Nice. Looks good to me + no Chromatic diffs.

**Review by shane-melton — APPROVED** [review]

**Review by willmartian — APPROVED** [review]

**Review by audrey-jensen — APPROVED** [review]
❓ Just to confirm, this is making greyscale icons a bit darker?

**Comment by vleague2** [comment]
> ❓ Just to confirm, the intended impact is making icons a bit darker? (I understand the new class is pinned to the old one's presentation for compatibility purposes.)

@audrey-jensen The design team is working on updating the color palette and color usage as part of the browser extension refresh project, so yes, some things will be a little bit darker in the end. There will also be other color-related changes, but we're still working through all of it!

**Review by vincentsalucci — APPROVED** [review]
Reviewed AC owned file 👍

**Pull request merged**
