### PR TITLE
[PM-3442] Change AnonAddy to addy.io

### PR DESCRIPTION
**Pull request by willbrowningme**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

To use the new API URL for addy.io and update the name after the rebrand - [https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/](https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/).

## Code changes

- Updated API URL to `https://app.addy.io/api/v1/aliases`.
- Updated the `name` in `generator.component.ts`
- Left other behind the scenes references as they are (`anonaddy`), they can be updated at a later date if needs be.

### CODE REVIEW

**Comment by micahblut** [comment]
@willbrowningme thank you for your contribution! Does this change also update the default value for the `domain name` field?

**Comment by willbrowningme** [comment]
@micahblut Are you referring to this line here - https://github.com/bitwarden/clients/blob/master/libs/common/src/tools/generator/username/username-generation.service.ts#L25

If so, then no that domain will remain the same.

**Comment by willbrowningme** [comment]
Is there anything else you need from me to merge this PR? I also need to issue a PR on [https://github.com/bitwarden/mobile](https://github.com/bitwarden/mobile) to update the API URL.

**Comment by djsmith85** [comment]
@willbrowningme: I spoke with Micah and vetted that the domain name will stay the same (for now). For this PR there is no further work required and we have queued it up for review. 

If you'd like to also update the mobile client, we'd really appreciate that, as that would free us up to just review the changes instead of also making them. 

FYI: @aj-rosado

**Comment by willbrowningme** [comment]
@djsmith85 Thanks very much, I've just issued a PR to update the mobile client too.

**Review by aj-rosado — APPROVED** [review]
Thank you for your contribution @willbrowningme. 
Changes are looking good to me! 🎉 

I'm passing this to QA and once they have given their approval this will be merged.

**Comment by djsmith85** [comment]
@willbrowningme Changes have passed QA and are ready to get merged. Your changes will be included in the upcoming `2023.9`-release.

Thank you again for your contribution!!

**Pull request merged**
