### PR TITLE
[PM-1376] Issue 3365: Bitwarden is not importing custom fields correctly when importing from 1Password

### PR DESCRIPTION
**Pull request by rituraj00**
Removed the regex and length check of id in the getFieldName method. Since we need the title of fields as it is, so we checked for the emptiness and nullable of title. If it passed, we return title or if failed id.
Also wrote a unit test for the one-password importer. It checks for custom field equals to id in case of title is null or empty. 

Thanks

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

We need the custom fields from importing passwords from 1password as it is but regex check was messing with it.

## Code changes

- "onepassword-1pux-importer.ts" file and "getFieldName" method name
- removed the regex and length check of id.

### CODE REVIEW

**Review by djsmith85 — COMMENTED** [review]
@rituraj00 Thank you for your contribution. As you mentioned you were able to reproduce the issue, could you please also add a unit-test to verify the desired behaviour.

Could you please also give the PR a more descriptive title.

**Comment by rituraj00** [comment]
@djsmith85 
Added unit tests for the custom fields fix. Please review.

Thanks

**Comment by rituraj00** [comment]
@djsmith85 
Here is the test file changes I did to reproduce the issue. 
NullEmpty

Got correct fields, 
UpdatedFieldNames
 
Test completed successfully!

Please let me know if there is any scope of improvement in my code.

**Comment by felipecrs** [comment]
I'm also affected by this problem, and this PR looks good to me. @djsmith85 would you mind taking a look again?

**Comment by djsmith85** [comment]
Sorry for the long wait on getting this reviewed. I have queued this up for review and, carrying (resolving conflicts) if needed, for this iteration.

**Comment by felipecrs** [comment]
Just to mention, I just cloned the PR locally and built the Web Vault and tried importing my data. It works as expected (i.e, fixes the issue).

**Comment by felipecrs** [comment]
@rituraj00 @djsmith85 just to mention I sent #6261 which builds on this PR, but fixing everything including tests and it should be ready to review.

**Review by ttalty — CHANGES_REQUESTED** [review]
While this change does work. It does not solve the complete issue. 

If a custom field is added to the 1password vault and the title is removed. That item no longer has a title. In this case all fields without a title would display the 26 character id string all of the time. This does not provide any insight to the user and could cause confusion or the assumption the import failed. 

There is a way to help identify these fields. In 1password there is the ability to add in custom sections with custom fields in those sections. The getFieldName function should be modified to take in a nullable sectionTitle string. This should be provided to the function when parsing the custom fields. 

For example if a user added a section called "Additional Info" and there was a field without a title that contained a phone number. Instead of the importer using the 26 digit id for the phone number. The section title of "Additional Info" will be used. If there is a title provided, the title should be used over the section title. If no title is provided then simply set the name field blank.

**Comment by ttalty** [comment]
I just merged in a fix to take care of the custom field names. This should now be taken care of in the next release.  
https://github.com/bitwarden/clients/pull/7190

**Pull request closed without merging**
