### PR TITLE
[PM-5318] fix: allow submitting member-invite form on enter

### LINKED ISSUE #7156: When inviting a new organizational member, Input is required is shown below the email address field after pressing return (Enter).
### Steps To Reproduce

1. Navigate to the organizational (Members) menu and press on (Invite member).
2. Use the mouse to click on the (Email) field and type the email address.
3. Press Return (Enter) on the keyboard.

### Expected Result

To invite that email address into the organization.

### Actual Result

The modal remains on screen and (Input is required.) is shown below the (Email) field in red.

### Screenshots or Videos

image

### Additional Context

If you ignore the (Input is required.) message and press on (Save), the invitation is sent.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Firefox

### Browser Version

120.0.1

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by frederikprijck**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently, when hitting enter when still focussing the `emails` field when inviting a user to an organization, will try submitting the form.

However, [as `updatedOn` is set to `blur`](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts#L94) for the emails field, and[ the `blur` event not being triggered when submitting the form through hitting `enter`](https://jsfiddle.net/ac208g9y/), this results in an error message informing the user that the input is required. 

Closes #7156 

## Code changes

Intercept the `enter` key, trigger the `blur` event on the input, and continue calling submit.

### CODE REVIEW

**Comment by frederikprijck** [comment]
Marked as draft as it does solve the issue on Chrome, but not on firefox. Looking into this.

**Comment by frederikprijck** [comment]
Used `keydown` instead of `keyup` and `event.preventDefault` to also fix the behavior on firefox.

**Comment by frederikprijck** [comment]
Hey, any chance this can be looked at? Thanks 🙏

**Comment by dbosompem** [comment]
Hi @frederikprijck , thanks for checking in. The team will make time to check this and I will keep you posted.

**Review by eliykat — COMMENTED** [review]
The problem here seems to be the `updateOn: blur` setting. It was added in #5564 to enable a new validator, but I think this bug suggests that that wasn't the best solution. I think hooking into keyboard events and manually triggering blur is an unnecessary workaround - please revisit that PR and see if you can remove `updateOn: blur` while maintaining the validation (and other existing behaviour).

**Comment by frederikprijck** [comment]
Thanks for getting back to me @eliykat. I did look into that, and I believe it's a bit of an odd PR making this workaround needed.

However, if the original PR can be reconsidered, that would change things.

What https://github.com/bitwarden/clients/pull/5564 does, is:

- It adds a new validator that checks if the limit of free organization users has reached.

However, this validation does allow inviting users that are already part of the organization. This looks awkward and is what is the reason blur was added (or at least how I understand it).

Imagine the following scenario:

- Organization is Free and the limit is 2
- We have two users john@myorg.com and jane@myorg.com

When I am now trying to invite another member, and I start typing john@myorg.com and blur away, it wont be invalid. If I would drop the `updateOn: blur`, it would show the invalid message until the point I end up at the last `m` and have the email spelled out.

Now, the thing I wonder is ... Why does this have to happen like this? Why does that matter that it should be valid if we exceed the limit with users that are already part of the organization? 

I think the above isn't a question I, as a random outside contributor, can answer. But personally, I would not do this through a validator, but instead do the check outside of the form and have a more generic check that lives outside of the validator (e.g. on form initialization) that does not care about the current organization members, but just shows a message that tells the user they have reached their total seat limit for the plan.

**Comment by eliykat** [comment]
I experimented with this today and it looks like we can just remove it; our [component library](https://components.bitwarden.com/) handles the validation behaviour already. I'd appreciate it if you could test #8009 and let me know if you agree it fixes the issue.

**Comment by frederikprijck** [comment]
If you are saying that the validation library ensures no validations are shown up until a certain point (e.g. blur), and not on keystroke, than I am convinced that PR will solve it.

I will try and take some time to see if this also fixes #7156, but I am pretty convinced it will.

**Comment by eliykat** [comment]
#8009 has been validated and merged so I'll close this one. Thanks for your work here @frederikprijck !

**Pull request closed without merging**
