### PR TITLE
[PM-969] Fix card number not being populated for Greek provider Eurobank.

### PR DESCRIPTION
**Pull request by xnick**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

They use the identifier `card.pan` for the card number, both in the `name` attr and the `id`. 

Example card number input field.

```
<input type="text" id="card.pan" name="card.pan" maxlength="23" value="" onfocus="setOldPan(this.value)" class="inp_full" placeholder="Αριθμός Κάρτας" onblur="unSelectPayMethod(''); CheckPanAndSubmitCard(this.value, null, 'payform1', 'refresh');">
```

## Code changes

clients/apps/browser/src/services/autofillConstants.ts: Appended the new identifier to CardNumberFieldNames.

### CODE REVIEW

**Comment by xnick** [comment]
Looking at it again, I realize now that this wouldn't work. 
Sorry, I should have tested this before pushing.

`isFieldMatch` in [autofill.service.ts](https://github.com/bitwarden/clients/blob/504e6202ab69901c2bb16610398edbe48b9ab541/apps/browser/src/autofill/services/autofill.service.ts) removes all non-alphanumeric characters from the attribute being checked, and removes the dash from the attributes in [autofillConstants.ts](https://github.com/bitwarden/clients/blob/429b92003a3c2d2748476e14852bd1e4ec5e86ed/apps/browser/src/services/autofillConstants.ts).

An easy fix is obviously to simply replace `card.pan` with `card-pan` or with `cardpan`, since the dot will be removed either way in isFieldMatch. And we keep the simple regex in the second replacement, which I suppose would be more performant than running the full one again.

Of course, if the matching logic ever changes this will break.

**Comment by jprusik** [comment]
e85bf2543ed01caa25a496a623a505981835a267 resolved merge conflict due to a rename of the target file

**Review by jprusik — APPROVED** [review]
Makes sense; tested and verified. Thanks for your contribution @xnick !

I'm sending this to our QA team next, and assuming there are no issues there, we'll be able to get this merged in.

**Comment by jprusik** [comment]
Hey @xnick thanks again for your work here - this change has passed QA and has been merged; expect to see it in an update soon!

**Pull request merged**
