### PR TITLE
[PM-5450] Admin Console event collection

### PR DESCRIPTION
**Pull request by nick-livefront**
## 🎟️ Tracking

[PM-5450](https://bitwarden.atlassian.net/browse/PM-5450)

### Issue
When "Owners and admins can manage all collections and items" is selected for an organization and an added Owner is added without giving explicit access the organizations collections, events are not being sent.

UI like this:
| Org Settings | Member Setting (owner)|
| - | - |
|org-setting|member-setting|

### Fix

The `collect` method on EventCollectionService has logic to determine if an event should be sent. One of those checks is if the cipher is available for the user. With the settings shown above and when the user is in the Admin Console, the cipher service **does not** return the cipher resulting in the event being skipped.
Switching to `collectMany` allows for the consumer to pass the full cipher rather than just the cipher id. This works and I can see the `/events/collect` being hit with the correct events.

There was a change needed on the server side as well: https://github.com/bitwarden/server/pull/4705

## Screenshots

https://github.com/user-attachments/assets/c4932d05-60ae-44a0-8eea-37c93c2ccc34

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-5450]: https://bitwarden.atlassian.net/browse/PM-5450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by shane-melton — DISMISSED** [review]
Looks good, thanks for cleaning up those `FIXME`s too!

**Comment by nick-livefront** [comment]
@cd-bitwarden Just keeping track of my open work, when you get a chance could you give this one a review?

**Comment by shane-melton** [comment]
This looks good, but is going to conflict with the changes in https://github.com/bitwarden/clients/pull/11092 which more fully address the issues with the View dialog in the org vault. 

#11092 should ideally be merged soon, it just had some merge conflicts that were just resolved after approval.

**Comment by nick-livefront** [comment]
@shane-melton This was approved by QA but I realized you never approved after I fixed the conflict from `main`. Can you do another review when you have time?

**Review by shane-melton — APPROVED** [review]

**Pull request merged**
