### PR TITLE
[PS-1160] re-order autofill events

### PR DESCRIPTION
**Pull request by TomK**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Address #3141 

## Code changes

- **apps/browser/src/content/autofill.js** I have re-ordered the events that are fired so the value of the element is correct at the time of each event.

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Comment by dbosompem** [comment]
Hi @TomK , just a little update on your PR. The team is taking a look at it currently, but we intend to handle this with caution. We agree your PR addresses the issue, but what we would want to look into further is whether it breaks something else, which is even more important. We'd have to make time to evaluate this change with a lot of testing efforts too. Could take some time, but just keeping you in the loop.

**Comment by trmartin4** [comment]
Hi @TomK.  I am an Engineering Manager at Bitwarden.  We are evaluating this fix and attempting to verify that there are no unexpected side-effects for other uses of our autofill logic.  As you're probably aware, the autofill process has been built iteratively over the years to try to handle different permutations of fields and events.

I was wondering if you could go into a little more detail about how you decided to alter the event order to add the "keyup" event after the setting of the field back to its original value.  We want to make sure we understand the intent so we can document it.

**Comment by TomK** [comment]
Hi @trmartin4
The order of events was based on the feedback from the codepen I wrote: https://codepen.io/oridan/pen/qBomOpM

It appears that under normal keyboard entry the browser recognises the element value as being updated after keydown, but before keyup.

<table>
<tr>
    <th>event order
    <th>event name
    <th>element value
<tr>
	<td>1
	<td>focus
	<td>
<tr>
	<td>2
	<td>focusin
	<td>
<tr>
	<td>3
	<td>keydown
	<td>
<tr>
	<td>4
	<td>keypress
	<td>
<tr>
	<td>5
	<td>beforeinput
	<td>
<tr>
	<td>6
	<td>input
	<td>a
<tr>
	<td>7
	<td>keyup
	<td>a
<tr>
	<td>8
	<td>change
	<td>a
<tr>
	<td>9
	<td>blur
	<td>a
<tr>
	<td>10
	<td>focusout
	<td>a
</table>

so, i reordered the events to match this finding.  Setting `el.value` immediately before the `input` event (where this is triggered).
In the case of function `setValueForElement`, `el.value` is set before `keyup` for consistency with this.

I did not add a `beforeinput` trigger as it seemed out of scope for this PR, but perhaps it should be considered?

**Comment by TomK** [comment]
@trmartin4 is this something you'd like me to rebase? relating specifically to issue #3141

**Comment by cagonzalezcs** [comment]
The reworked logic within the `InsertAutofillContentService` class effectively incorporates these changes, with a minor different relating to the keyup event. In either regard, these changes can't be merged as the script that is being referenced here has been removed from the implementation. 

Closing this PR.

**Pull request closed without merging**
