### PR TITLE
[AC-1842] Secrets Manager Trial Page

### PR DESCRIPTION
**Pull request by amorask-bitwarden**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

[AC-1842](https://bitwarden.atlassian.net/browse/AC-1842)

The purpose of this PR is to create a trial page that allows the user to sign up for a "stand-alone" Secrets Manager subscription. While a "stand-alone" Secrets Manager subscription doesn't actually exist, this trial page will enroll the user in a plan that has both Password Manager and Secrets Manager, and then a [separate ticket](https://bitwarden.atlassian.net/browse/AC-1843) is responsible for discounting the Password Manager portion down to $0.

## Code changes

- **secrets-manager-trial-billing.component.*:** The component responsible for the billing section of the right-hand form on the trial page whenever the `layout` query parameter is set to "secretsManager".
- **trial-initiation.component.*:** Updated this component to support a "secretsMaanger" `layout`. When the `layout` is "secretsManager", shows the new `secrets-manager-content.component` and uses the `secrets-manager-trial-billing.component`. 
- **secrets-manager-content.component.*:** The static left-hand content for the Secrets Manager trial page.
- **review-blurb.component.*:** A small reusable quote blurb component.

## Screenshots

https://github.com/bitwarden/clients/assets/144709477/2f967330-0db0-46dc-a0f7-176852619787

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

[AC-1842]: https://bitwarden.atlassian.net/browse/AC-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cturnbull-bitwarden — DISMISSED** [review]
This is great, thank you, sir. I'll branch off of this to finish up my changes on the backend

**Review by jlf0dev — APPROVED** [review]
There's some untranslated text in here, but I'm assuming thats intentional

**Comment by amorask-bitwarden** [comment]
@cturnbull-bitwarden @jlf0dev Thank you both for the review. I actually refactored this a bit with newly introduced requirements. If you two have some free time, can I get a second look?

**Review by jlf0dev — DISMISSED** [review]
If there's more work planned we might want to consider moving the trial initiation stuff over to billing sooner. Seems like ya'll are expanding it quite a bit 
CC: @cturnbull-bitwarden

**Review by cturnbull-bitwarden — APPROVED** [review]

**Review by vincentsalucci — DISMISSED** [review]
Sorry for the delay - reviewed the only file owned by AC. 👍

**Comment by amorask-bitwarden** [comment]
@cturnbull-bitwarden @vincentsalucci @jlf0dev Had a conflict in `messages.json` that wiped the approvals. Can I get a re-stamp whenever you all have a sec?

**Review by cturnbull-bitwarden — DISMISSED** [review]

**Review by jlf0dev — DISMISSED** [review]

**Review by cturnbull-bitwarden — APPROVED** [review]

**Review by jlf0dev — APPROVED** [review]

**Review by vincentsalucci — APPROVED** [review]

**Pull request merged**
