### PR TITLE
[PM-14627] Import TOTP with ZohoVault CSV importer

### LINKED ISSUE #11872: Zoho importer does not import TOTP seeds
### Steps To Reproduce

When attempting to import TOTP codes from a CSV file exported from Zoho Vault into Bitwarden, the TOTP codes do not appear to be imported correctly.

Steps to Reproduce:
1. Export your vault from Zoho Vault and save it as a CSV file.
2. Log in to the Bitwarden Password Manager/Admin Console.
3. Go to the import section and select Zoho Vault as the source.
4. Upload the CSV file.

### Expected Result

The TOTP codes should be imported and appear correctly in the Bitwarden vault.

### Actual Result

The TOTP codes are not imported or do not appear in the Bitwarden vault after the import process.

### Screenshots or Videos

_No response_

### Additional Context

Example file:
```
"Password Name","Description","Password URL","SecretData","Notes","CustomData","Tags","Classification","Favorite","login_totp","Folder Name"
XYZ Test,,https://abc.xyz.de:5001/#/login,"SecretType:Web Account
User Name:email@domain.de
Password:PcY_IQEXIjKGj8YW
",,"",,E,0,otpauth://totp?secret=PI2XO5TW0DF0SHTYOVZXOOBVHFEWM6JU&algorithm=SHA1&period=30&digits=6,someValue,
```

### Operating System

Windows, macOS, Linux

### Operating System Version

_No response_

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Browser Version

_No response_

### Build Version

2024.10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by kshashikumar**
## 🎟️ Tracking

[](https://github.com/bitwarden/clients/issues/11872)

## 📔 Objective

totp secret is assigned to cipher object in zohovalut-csv-importer to populate when importing keys from zoho vault fixes  #11872 closes #11872

## 📸 Screenshots
Before
image

After
image

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by djsmith85 — COMMENTED** [review]
@kshashikumar Thank you for your contribution 🚀  

Your changes are looking good. I just tested and you can actually simply assign the full `login_totp` to `cipher.login.totp`. This has the benefit of retaining all information (secret, algorithm and period)

Would you be willing to also add unit tests for this or even for the full importer?

Unfortunately this specific importer has no unit tests yet, but examples can be found within [libs/importer/spec](https://github.com/bitwarden/clients/tree/main/libs/importer/spec).

Kind regards,
Daniel

**Comment by kshashikumar** [comment]
Thank you for the review @djsmith85, will update the  cipher.login.totp to take full url and also will add unit tests for it. Thanks again

**Comment by kshashikumar** [comment]
Hi @djsmith85 , updated **cipher.login.totp** to take full totp url and also implemented unit tests for above. Please let me know if any further changes needed. Thank you for your time and consideration.

**Review by djsmith85 — DISMISSED** [review]
Awesome work @kshashikumar and thank you for adding unit tests ❤️ 

Approving your changes, but while testing I noticed that folders/collections were no longer imported as the column name had changed. I have gone ahead and added a fix for that and will pass the work on to QA.

Once QA gives their go, this PR will get merged and your changes will be included in a future release.

Thanks again, for your contribution 🚀

**Review by djsmith85 — APPROVED** [review]

**Comment by kshashikumar** [comment]
Thank you so much for your review and the valuable changes, @djsmith85 !❤️ Your guidance truly inspires me. I’m excited to continue contributing to the Bitwarden community and growing together. 🚀

**Comment by djsmith85** [comment]
@kshashikumar QA has given their approval and this is ready to get merged. Your changes will be included in an upcoming release.

**Comment by kshashikumar** [comment]
Thank you so much @djsmith85 , Looking forward to contribute more to the community!

Kind Regards,
Shashi Kumar K

**Pull request merged**
