### PR TITLE
[PM-5043] Update ownership of code to autofill team

### PR DESCRIPTION
**Pull request by cagonzalezcs**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Updating location of files that should be owned by the autofill team within the project.  Changes should be reflected mainly in modifications to `import` statements, and should not functionally affect the implementation in any manner. This is a follow up PR to https://github.com/bitwarden/clients/pull/6928 to address provided feedback.

## Code changes

Move files that relate to autofill into the `autofill` project scope and update import references to those files.

### CODE REVIEW

**Comment by eliykat** [comment]
See [this doc](https://bitwarden.atlassian.net/wiki/spaces/DEV/pages/373948418/Pod+-+Team+Code+Reorganization+Plan#%5BinlineExtension%5DOnly-File-Renames-in-Commits) for more info.

Basically you have to split it into 2 PRs:
* one to move the file
* one to update its content

I don't think it matters which order you do it in, it just has to be merged separately. The problem is that if you do it at once, the diff is large enough on small files that git registers it as a different file rather than a move.

**Comment by cagonzalezcs** [comment]
@djsmith85 @eliykat 

Hm... I can split that change up into two PRs are suggested... that said, is this git history correction really that important? This file is fairly small, and presents as a simple model definition for a data structure. I'm not sure how much historical context we're preserving with this particular file, especially since the file was created this year for the popout window unlock update and hasn't been modified since creation.

**Comment by eliykat** [comment]
Not my rule - just repeating what @MGibson1 has asked me to do in the past. I'll let him weigh in.

**Comment by MGibson1** [comment]
The thinking isn't so much about the specific file, but the history surrounding it's inclusion. It just makes detective work in the codebase harder and we wanted to avoid that as much as we can.

However, If the code owners don't care about losing that context, I'll not belabor it further than that explanation.

**Comment by cagonzalezcs** [comment]
@MGibson1 

For a larger file or for a file that has a longer history, I'd 100% agree.

For this file, I'm not concerned with the history.

**Review by MGibson1 — APPROVED** [review]

**Review by jprusik — APPROVED** [review]

**Pull request merged**
