### PR TITLE
[PM-2871] Submenu UI elements cannot be accessed by keyboard navigation when screen reader is active

### PR DESCRIPTION
**Pull request by cagonzalezcs**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

An issue was identified with our `bit-menu` component that impeded access by keyboard navigation to the menu items of the component when a user has a screen reader active.

The component actually can be navigated using a keyboard. This is done when triggering the component to an active state, a user can then press `keyup` or keydown` to navigate through the list of submenu items. The problem with our implementation, however, is that screen readers sometimes override keydown events to facilitate their own specific behavior.

For example, VoiceOver on MacOS handles navigation from heading to heading through the use of they `keydown` and `keyup` keystrokes. With that usage, all event listeners on a page that are expecting to navigate using those keystrokes end up being ignored.

Resolution of this comes by referencing an established [action menu button pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/). This pattern acts similarly to our own submenu component, however it has one key difference in that upon triggering the menu to an open state, the Ui component focuses the first item in the list of the submenu.

By implementing a similar manner of focus redirection, users can then use the left and right arrow keys to navigate the submenu (instead of up and down, this behavior is also seen in the WAI-ARIA pattern).

## Code changes

-**libs/components/src/menu/menu-divider.component.html:** Adding an `aria-hidden` attribute to the menu divider component to ensure that screen readers do not attempt to read the DOM element's content.
- **libs/components/src/menu/menu-trigger-for.directive.ts:** Adding a call to set the first item as active within the KeyManager method used by the submenu.

## Demo of the issue

https://github.com/bitwarden/clients/assets/16629865/e07ef1ba-083d-4bbb-a612-af48798ec1b2

## Demo of the fix

https://github.com/bitwarden/clients/assets/16629865/935dea06-2da5-4e54-b472-0744fba6499b

### CODE REVIEW

**Comment by vleague2** [comment]
I'm having a hard time repro-ing the issue -- is there a certain mode/setting that needs to be turned on for Mac Voiceover to cause it to hijack the keyboard nav?

**Comment by cagonzalezcs** [comment]
@vleague2 

Interesting, I'm having issues with accessing the menu elements while VoiceOver is enabled. Normally you can focus into the submenu by pressing `Arrow Down`, but that doesn't seem to be possible to do with VoiceOver's default settings. Instead, pressing `Arrow Down` seems to jump between heading elements within the DOM. 

I'm not sure if there is something I've misconfigured on my side, but regardless focusing the first item of an expandable submenu not only fixes the issue from my side, but is also likely the expected/intended behavior given the way this [WAI ARIA pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/) is implemented.

**Comment by vleague2** [comment]
@cagonzalezcs The up and down arrows work fine for me on the existing and on yours, so who knows 😂 But I agree that this matches the spec better. I also can't get right and left arrows to work, which you do mention in the PR description 🤔

**Comment by cagonzalezcs** [comment]
@vleague2 

Are you testing this with a screen reader like VoiceOver turned on?

I'm not seeing the up and down arrows function with that screen reader active. Without it, yes the up and down arrows function as expected.

**Comment by cagonzalezcs** [comment]
@vleague2 

Hmm interesting, definitely willing to jump on a call and verify if that makes sense to do. I'm not seeing the up and down arrows function with VoiceOver turned on, so likely there is some kind of configuration that can impede navigation while using it. As far as I know, I'm using VO in it's default configuration...

**Comment by vleague2** [comment]
@cagonzalezcs I think I figured out what might be happening!! Here's a video of me discovering it in real time 😂  At first it works fine with up and down arrow keys and VO on (although it does seem to track what you were last focused on in the menu). Then I hit the right and left arrows a bunch of teams in quick succession trying to test those, and it turned on arrow key quick nav. In that mode, right and left arrows work for navigating the menu (or at least, they did for this video -- can't get it to work with those keys again on `main`), but up and down cause me to jump around the page. I wonder if that is turned on for you?


https://github.com/bitwarden/clients/assets/32983157/8f804792-a694-4bbe-b7f5-ca30290fe975

**Comment by cagonzalezcs** [comment]
Yeah, looks like that was it 100%. I had [turned on](https://support.apple.com/guide/voiceover/with-quick-nav-vo27943/mac) the quick nav setting at some point...

I'm definitely not an expert with screen readers, and know just about enough to get myself around. Turning off that setting allowed me to use the Up/Down arrows on the submenu (which disabled the left and right arrows).

**Comment by vleague2** [comment]
🎉  I still think this PR is better aligned with the ARIA spec than it was before. Maybe we can also update the Storybook docs page for Menu to clarify the keyboard navigation for screenreaders with the quick nav setting on/off?

**Review by vleague2 — APPROVED** [review]
My only non-blocking suggestion is to update the storybook docs re: accessibility for the menu component, or we can make a task on the CL board for that.

**Pull request merged**
