### PR TITLE
[PS-1465] Fix #2806 - The "Import Data" page's file selector button cannot be translated

### LINKED ISSUE #2806: The "Import Data", "Premium Membership", "Subscription" and "Edit User" pages contain strings that cannot be translated
## Describe the Bug

It seems that the "Choose File" button text and its "No file chosen" description can't be translated at Crowdin (at least I could not find them there). Both Finnish and English screenshots are attached.

These are located under "Tools" > "Import Data" > "2. Select the import file".

The membership and subscription status message is also not translatable it seems. 

Located under "Settings" > "Premium Membership" and Organization "Settings" > "Subscription".

One addition to this list: "Organization Settings > Manage > People" page "Edit User" screen. The headers for custom permissions do not seem to be available for translation at Crowdin.

## Screenshots

**Tools > Import Data:**
bitwarden_import_en
bitwarden_import_fi

**Settings > Premium Membership:**
english
finnish

**Organization Settings > Subscription:**
english_org

**Organization Settings > Manage > People > Edit User:**
en
fi

## Environment

- Build Version: [2.21.1]

### PR DESCRIPTION
**Pull request by schang1146**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix for #2806 where some pages contained strings that weren't being translated.

## Code changes

- **apps/web/src/app/tools/import-export/import.component.html**
I added a button that calls click() on the now hidden type="file" input so users are still going through the usual upload file workflow but we can now control what the text in the button says. I also added a short description after the button similar to how it was originally which is either the translatable default of "No file chosen" or whatever their file is called. The original input is hidden and has a `(change)` handler to capture the file in a variable.

- **apps/web/src/app/tools/import-export/import.component.ts**
I added a `setSelectedFile` to save the selected file in the `selectedFile` variable for the HTML template to grab and show the user.

- **apps/web/src/locales/en/messages.json**
I added some English defaults for the new translatable text to grab from.

## Screenshots

Tools > Import Data (English)
image
image

Tools > Import Data (Finnish - Changes to Finnish `messages.json` reverted after testing changes)
image
image

Tools > Import Data (English - Dark Mode; new button has the same on-hover effect as the "Import Data" button where the cursor changes and the button gets slightly brighter)
image

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by djsmith85 — CHANGES_REQUESTED** [review]
@schang1146 Thank you for your contribution.

1) The changes  for the missing translations on the `user-add-edit.component` and accompanying `en/messages.json` are looking good. 
Bitwarden's translations are done via Crowdin where we push the `en/messages.json` and after translations are done,  pull in the `xx/messages.json` files. Please remove the changes from  `fi/messages.json`.

2) The changes for the import file input selector also look good, but I'd like to get an opinion from @bitwarden/dept-design regarding that change.
 
Our current implementation relies on the users browser display language to change the text on the file-input (button). This has the downside that if a user has set a certain language for their vault other than the browsers one, it would still show the browsers one.
 - In my case for example: Browser UI set to German, vault language set to English, the input shows "Datei auswählen" instead of "Choose file".
 
This PR would solve this, but is a change in design and only addresses the import file-select. We have several other places, also across clients that use the old way.

After a decision/approval from @bitwarden/dept-design I can create a task to address the other occurrences, as I'd say it's likely out of scope for this PR. It would be up to @schang1146 to decide though.

@schang1146 To make this easier/faster to merge, you could also split this PR up, as the first changes I commented on, would be mergable in my opionion.

**Comment by schang1146** [comment]
I reverted my changes to the Finnish `messages.json`.

I'm down to separate the work for `user-add-edit.component.ts` and accompanying `messages.json` from the import file input selector work. Makes more sense in my head to save the work for the latter for the new task(s) you're creating and have them all lumped together.

Would you like me to revert the other changes and update this PR or create a fresh one for just the mergeable content and close this one out?

**Comment by djsmith85** [comment]
@schang1146 Thank you for reverting the Finnish messages.

I think it would be great to split out the IMHO now mergeable content into a separate and we can see what changes follow with the file-selector.

I'm personally always in favour of keeping PRs small in scope and thus easier to review/merge. Hard to gauge with this one beforehand.

**Comment by schang1146** [comment]
<3 Keeping PRs small in scope too for the same reasons.

Created #3607 for the mergeable content and closed this out as the file-selector stuff is awaiting review from @bitwarden/dept-design.

**Comment by djsmith85** [comment]
@schang1146: Re-opening this as it's still in progress.

Could you please update your fork/branch with `master`, as the changes made on #3607 have been merged. 

Design can then have a look at the remaining changes of this PR.

**Comment by schang1146** [comment]
Ah gotcha, sorry if I misunderstood.

**Comment by danielleflinn** [comment]
@schang1146 can you send a screenshot of this page in the Dark mode theme for Design? 

It would also be helpful to update the PR title since only the file selector edits are included and the content strings were addressed in another PR.

**Comment by schang1146** [comment]
Yep, I'll update the PR screenshots with an image of the page in Dark mode theme and update the PR title.

**Comment by schang1146** [comment]
😅 I'm done finagling with the title. Forgot for a sec GitHub tracks all title updates :(

**Review by danielleflinn — APPROVED** [review]

**Review by djsmith85 — CHANGES_REQUESTED** [review]
@schang1146: With design giving their okay, I tested your branch locally and something seems wrong with file-select button.

As soon as I click on it, it seems to trigger the submit-action which shows an error toast if not all conditions have been met, like selecting a file. 

Please have another look at this.

**Comment by schang1146** [comment]
Sure, I'll take a look at why that might happen. 👍

**Review by djsmith85 — APPROVED** [review]
@schang1146 Thanks for looking into this again. This is ready to get passed on to QA. Once I get an approval, this will get merged into master.

**Review by djsmith85 — APPROVED** [review]
@schang1146 I have received approval from QA and this is ready to merge. Thank you for your work on this and your other contributions 🎉

**Comment by djsmith85** [comment]
Hi @schang1146,

I'm sorry but I had to revert your changes. We had an issue on one of our test environments and missed 2 issues. Luckily we did catch them before the release. Details around the issues can be found on the linked [PR](#3900)

We'd be really grateful if you'd be open to take another look at this. We understand though, that you might not have the time or wish to continue with this. If that is the case, then this will likely be addressed during a future vault refresh work.

Again apologies for the revert.

**Comment by schang1146** [comment]
Gotcha :+1: , I'd love to take another look and see if I could get those issues resolved.

Could you fill me in on some details about the test environment? I don't remember seeing 2 buttons come up when I was working on it locally. What browser & browser version was used? Were there specific steps taken in order to get 2 buttons to show up? Might be less applicable but what OS / OS version was used?

I think I know what to do about the CSP issue - finding it super funny how I just went through CSP hell at work and now it's followed me here.

(Let me know if there's a better place to continue discussion on the bug)

**Comment by djsmith85** [comment]
Hi @schang1146, thank you so much. Highly appreciated.

I'm on Windows 10 and tested it with Chrome 106.0.5249.119. Special to my setup might be, my browser's UI language is set to German. This will translate the `Choose file` input to `Datei auswählen` like shown in the screenshots in the linked PR. The same happens also though when I switch the browser's UI language to English. A colleague was also able to repro this on Chrome on Mac but his system and browser UI will be in EN-US.

Let me know if there's anything else I can support you with.

Those CSP issues can really be pesky and I'm looking forward to see what you come up with.

**Pull request merged**
