### PR TITLE
[PM-1950] Add support for a loading state in dialogs

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adds support for a loading state to the dialogs. Replaces the need to implement your own loading state. Uses the same implementation as the `secret.dialog.component`.

Ideally we would have had a way to disable the buttons  as well, but those are controlled by the implementing component.

## Screenshots

image

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by coroiu** [comment]
Your screenshot has a lot of vertical padding but storybook doesn't, is that expected?
image

**Comment by Hinton** [comment]
The dialog height is calculated from the content, the spinner consumes the full height but doesn't add any margin/padding itself to prevent the dialogs from resizing after the spinner is done.

**Comment by coroiu** [comment]
Oh yeah you're just hiding the content, nice!

**Comment by coroiu** [comment]
So uhm, scrolling content might not be working as expected 😄  https://62a88a6de5b807fa98886113-nqifucddmk.chromatic.com/?path=/story/component-library-dialogs-dialog--scrolling-content&args=loading:true

**Comment by danielleflinn** [comment]
UI looks good!

We should make sure that "loading" is announced by a screen reader and "finished" is announced once the content loads. This will allow a user with low or no vision who is using a screen reader to know the content is ready to interact with. Here is [an example](https://carbondesignsystem.com/components/loading/accessibility/) from another design system. 

Perhaps we should look into building a "Loading" component to use across all "loading" instances? (pages, tables, dialogs, loading buttons)

**Comment by Hinton** [comment]
@danielleflinn created CL-95 for implementing a generic loading indicator which fulfills the accessibility concerns. Somewhat out of scope for this PR since we're already implementing loading indicators in dialogs and it's not making accessibility worse at this time just easier to align at a later stage.

**Review by JaredSnider-Bitwarden — APPROVED** [review]
LGTM! Thank you for adding this functionality!

**Review by willmartian — CHANGES_REQUESTED** [review]
> Ideally we would have had a way to disable the buttons as well, but those are controlled by the implementing component.

Could the storybook example be updated to bind `[disabled]="loading"` on the buttons in the footer? I imagine that is the best practice we want to follow if we are not handling it automatically.

**Review by willmartian — APPROVED** [review]

**Review by danielleflinn — APPROVED** [review]

**Comment by Hinton** [comment]
QA will do the last testing on master.

**Pull request merged**
