### PR TITLE
[PM-13804] Add new Is-Prerelease header to requests

### PR DESCRIPTION
**Pull request by trmartin4**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13804

## 📔 Objective

We want the ability to control feature flags based on whether the requesting client is a beta build or not.

To provide this context to LaunchDarkly, we must introduce a way for the clients to communicate that they are a beta to the server, where it can be used to build the LaunchDarkly context.

This will be done with an `Is-Prerelease` header on the request.

This PR adds that header to all API requests to our back-end based on whether the client-side `prereleaseBuild` flag is enabled.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by withinfocus** [comment]
💭 What if we don't consider just betas? Is the naming of "prerelease" more appropriate? Do we think these need to be enumerated?

**Comment by trmartin4** [comment]
> 💭 What if we don't consider just betas? Is the naming of "prerelease" more appropriate? Do we think these need to be enumerated?

Addressed with [`3427ea7` (#11605)](https://github.com/bitwarden/clients/pull/11605/commits/3427ea704be3f11d71010195ad058157eab3cc6f)

**Comment by trmartin4** [comment]
🤔 I see that there aren't any tests for `api.service.ts`.  Should we add that as part of this request?

**Review by dani-garcia — APPROVED** [review]
Changes LGTM, I'm also surprised there aren't any tests for the API service, seems like it would be fairly easy to mock the `nativeFetch` method to add some tests for expected headers.

**Pull request merged**
