### PR TITLE
[PM-4090] Fix: Automatic biometric authentication no longer worked (Resolves: #6134)

### PR DESCRIPTION
**Pull request by thomasync**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

For several versions now, when Bitwarden is opened and automatic biometric authentication is enabled, it no longer works.
The problem had already been identified here: #6134

## Code changes

- **apps/desktop/src/auth/lock.component.ts:** The biometric authentication request was only sent when the route settings were updated. Now, the request is sent in all cases, keeping the delay and checking that the setting is active.
- **apps/desktop/src/locales/fr/messages.json:** Just an improvement in the French translation.

### CODE REVIEW

**Review by djsmith85 — CHANGES_REQUESTED** [review]
Hi @thomasync and thank you for your contribution.

We use Crowdin to manage our translations and these are commonly done by our amazing translation community 🚀 🙌
Please have a look at the localization section [here](https://contributing.bitwarden.com/contributing/#localization-l10n) for further information.

Here is the link to the specific translation for desktop:

https://crowdin.com/translate/bitwarden-desktop/53/en-fr#12146

New translations can be added or existing ones can be up-/down-voted

Please remove your changes to the `messages.json`

**Comment by thomasync** [comment]
> Hi @thomasync and thank you for your contribution.
> 
> We use Crowdin to manage our translations and these are commonly done by our amazing translation community 🚀 🙌 Please have a look at the localization section [here](https://contributing.bitwarden.com/contributing/#localization-l10n) for further information.
> 
> Here is the link to the specific translation for desktop:
> 
> https://crowdin.com/translate/bitwarden-desktop/53/en-fr#12146
> 
> New translations can be added or existing ones can be up-/down-voted
> 
> Please remove your changes to the `messages.json`

Hi @djsmith85,

Thanks for the link, I'll modify it directly on Crowdin, as it looks like google translation.


I did revert the **messages.json** file

**Review by djsmith85 — DISMISSED** [review]
@thomasync Thanks for the quick response. Approving to remove my previous request for changes. **Not ready to get merged** as review is now up to product and then @bitwarden/team-auth-dev

**Comment by trmartin4** [comment]
@thomasync With https://github.com/bitwarden/clients/pull/6479 we introduced some merge conflicts with the `LockComponent`.  Would you be able to take a look at these and resolve them so that the team can review?

Thank you!

**Comment by thomasync** [comment]
> @thomasync With #6479 we introduced some merge conflicts with the `LockComponent`. Would you be able to take a look at these and resolve them so that the team can review?
> 
> Thank you!

@trmartin4 I've solved the merging problems, and my PR is ready for review.

**Comment by thomasync** [comment]
> Thank you for the PR! Just need some minor changes to get this working.

@jlf0dev Thank you for your review. The changes mentioned have been fixed.

**Review by jlf0dev — APPROVED** [review]
Thanks @thomasync! Approving and marking this as ready for testing!

**Comment by M0fafahrer** [comment]
Update to 2024.2.0
There was nothing fixed for me.
Popup still does not work at all.
My #6159 was closed but problem still exists

**Comment by medeiroshudson** [comment]
Not fixed. Bug still happening on Windows 24H2 and BW 2024.12.1

**Pull request merged**
