### PR TITLE
[PM-15937] ssh agent: fix first start when no .bitwarden-ssh-agent.sock exists

### PR DESCRIPTION
**Pull request by Icelk**
## 🎟️ Tracking

#10825

## 📔 Objective

When starting the ssh-agent the first time on unix, the rust code tries to remove the previous ssh-agent socket. On first time setup, there is no file, so it fails. This change makes it fail gracefully when no file is found.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by quexten** [comment]
Ohh, interesting. I think this error was introduced as a result of a last minute security fix (https://github.com/bitwarden/clients/pull/12048).

I will test the PR closely tomorrow and give the final approval. Thank you for the PR!

**Comment by quexten** [comment]
@Icelk Could you accept the CLA? (If you've already done that, also let me know. I know the CLAssistant was buggy the past few weeks).

**Comment by Icelk** [comment]
> Could you accept the CLA? (If you've already done that, also let me know. I know the CLAssistant was buggy the past few weeks).

Just did, thanks for reminding me :)

And also thank you for bitwarden and all it's components!

**Comment by quexten** [comment]
Nice, thanks again for the PR!

**Pull request merged**
