### PR TITLE
[CL-77] Multi-select Dropdown Styles

### PR DESCRIPTION
**Pull request by rr-bw**
## Type of change

- [x] Bug fix

## Objective

1. Add hover state for already selected items
2. Add a static state for already selected items (a slightly lighter bg color)

From [Issue CL-77](https://bitwarden.atlassian.net/jira/software/projects/CL/boards/43?selectedIssue=CL-77):

> We might also want to consider adding a static background to selected items to make them easier to identify. At the moment they can be identified by a checkmark, but if we add a “single select” this checkmark might not be present.

Let me know if we want to keep this static state, or just go with the hover state alone.

## Code changes

`libs/components/src/multi-select/scss/bw.theme.scss`: Add hover and selected states for already selected items

## Screenshots

Screenshot 2023-01-11 at 2 34 03 PM

### CODE REVIEW

**Review by danielleflinn — APPROVED** [review]

**Comment by coroiu** [comment]
I completely missed this one, sorry about that! Could you update the branch and make sure that this also works with the new single select version?

**Comment by rr-bw** [comment]
@coroiu No problem, just merged master. Looks like it does work with single select.

**Review by coroiu — APPROVED** [review]
Looks great!

**Comment by coroiu** [comment]
What's the status on this?

**Pull request merged**
