### PR TITLE
[PM-6735] Remove deprecated uses of StateService

### PR DESCRIPTION
**Pull request by eliykat**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

ConfigService and ConfigApiService were using AuthService to determine the user's authentication status. This is deprecated, they should use AccountService instead, and it was causing circular dependency errors in #6465.

Update these services and their dependencies to use AccountService.

## Code changes

- **file.ext:** Description of what was changed and why

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by justindbaur** [comment]
@MGibson1 Assigning this one to you since you're actively working on a config service rewrite. Is this worth doing in the meantime to unblock other work?

**Comment by ccben87** [comment]
@justindbaur & @MGibson1 FYI it is blocking https://github.com/bitwarden/clients/pull/6465 Will leave it up to you to prioritize but I hope you will please address this soon. Thanks.

**Comment by MGibson1** [comment]
As you mentioned this does have some implications in the config service work being queued up for #8325 ,
but I'm kind of more concerned with the implied deprecation of auth service.

I think that my addition of account status to `accountsService` was a mistake. Issues have arisen due to the enum with clear state paths (logged out <-> locked <-> unlocked, but no jumps) being less true now. In truth, we want to calculate the current state given two bools (we have a valid auth token and we have a decrypted user key). I'm of the mind that this is best handled in something like an auth service where we can centralize that logic. @jlf0dev interested in your opinion of this deprecation proposal, too

**Comment by jlf0dev** [comment]
Talked this through with @MGibson1 offline and I agree with keeping authentication status as part of auth service. I've created #8377 that should allow others to migrate off `getAuthStatus` while we work out the internals of this.

**Comment by eliykat** [comment]
@MGibson1 will your work remove authService from both configService and configApiService? Both are required to avoid this circular dependency.

Otherwise we get MultithreadEncryptService -> ConfigService -> ConfigApiService -> AuthService -> CryptoService -> MultithreadEncryptService.

Alternatively, do you have any other suggestion for resolving this issue? While I want to progress the community PR, I definitely want to feature flag any changes to our decryption logic. We could pass in the flag value but that's a hack - although maybe acceptable in this case if there's no other choice near-term.

**Comment by MGibson1** [comment]
[It does now](https://github.com/bitwarden/clients/pull/8325/commits/0896087e317645931dda010e702b0338367c3c2f)! I had to wait on token service and environment service improvements to complete those changes, but I believe this should allow config access with very few exceptions.

**Comment by eliykat** [comment]
Thanks! I will close this in favour of #8325.

**Pull request closed without merging**
