### PR TITLE
Defect/SG-825 - users in org w/ no personal vault still see personal vault (disabled org policies now still apply)

### PR DESCRIPTION
**Pull request by JaredSnider-Bitwarden**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Disabled organizations should still apply their policies to their users. 

## Code changes

- **apps/web/src/app/vault/vault-filter/organization-filter/organization-filter.component.html:**  Org Filter - (1) Show org suspended icon when org is disabled and remove personal vault policy enabled (2) Refactor - Enterprise users can now access org options to leave orgs without selecting them (previously, you had to select an org to get the options to show up which was not possible for disabled orgs). Users can now leave disabled orgs.
- **libs/common/src/services/policy/policy.service.ts:** Policy service - updated `checkPoliciesThatApplyToUser(...) `method to no longer filter out disabled orgs. 

Changes depend on server changes in [PR](https://github.com/bitwarden/server/pull/2429).

## Screenshots

SG-825-personal vault policy enabled w: disabled org

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by differsthecat — DISMISSED** [review]
Looks good!

**Comment by JaredSnider-Bitwarden** [comment]
Updated Desktop behavior (previously no icon shown when no personal vault): 
image

Updated Browser Behavior (selected vault text + dropdown menu item text both have better scaling and ellipsis truncation): 
image
image

**Review by differsthecat — APPROVED** [review]
New browser and desktop changes look good!

**Comment by JaredSnider-Bitwarden** [comment]
Merging to master per request from QA

**Pull request merged**
