### PR TITLE
[PM-9604] hasPremiumGuard not properly verifying premium after login

### PR DESCRIPTION
**Pull request by aj-rosado**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9604

## 📔 Objective
Creating this draft in order to continue the discussion on code regarding how to address this issue, sustaining it with code.

Currently when the `hasPremiumGuard` is called after the login, there is no sync call so the `hasPremiumFromAnyOrganization` value will always false.

This solution fixes it by 1. adding a sync call on login, 2. waiting for it on the guard.

The guard is waiting for sync with a 10 seconds timeout, if it fails, navigates to the vault and displays an update to premium message.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by aj-rosado** [comment]
🤔 The observable waiting logic should be on `BillingAccountProfileStateService`❓ could this affect any other part of the application?

❓should the fullSync be called there? If the sync takes long, it will be on an awkwards state where seems nothing is happening as there is no loading but in reality is waiting for sync

**Review by coroiu — COMMENTED** [review]
This seems to be the context https://bitwarden.slack.com/archives/C02LPDKPML6/p1723199776246849 that triggered this PR, please correct me if I'm wrong! (I was on vacation when that discussion happened so I was a bit confused :D) 

I completely agree with your own conclusion in that thread 

>Not fully happy with this, as
> 1. We will need to add it to any guard that needs the sync . Should add it to the BillingAccountProfileState , was afraid it could affect other parts of the application.
> 2. During the login, the page doesn’t show any animation, if the sync takes too long it looks like the application is not doing anything. I’ve added a [video](https://bitwarden.atlassian.net/browse/PM-9604?focusedCommentId=67190) showing this code with a “quick” sync and another waiting for the sync to the task

I think the correct solution would be to create a new "initial sync page" that properly informs the user about what is happening and what the progress is. That way we can safely assume that a sync has already happened in all the other guard AND we improve the UX

**Comment by aj-rosado** [comment]
> This seems to be the context https://bitwarden.slack.com/archives/C02LPDKPML6/p1723199776246849 that triggered this PR, please correct me if I'm wrong! (I was on vacation when that discussion happened so I was a bit confused :D)
> 
> I completely agree with your own conclusion in that thread
> 
> > Not fully happy with this, as
> > 
> > 1. We will need to add it to any guard that needs the sync . Should add it to the BillingAccountProfileState , was afraid it could affect other parts of the application.
> > 2. During the login, the page doesn’t show any animation, if the sync takes too long it looks like the application is not doing anything. I’ve added a [video](https://bitwarden.atlassian.net/browse/PM-9604?focusedCommentId=67190) showing this code with a “quick” sync and another waiting for the sync to the task
> 
> I think the correct solution would be to create a new "initial sync page" that properly informs the user about what is happening and what the progress is. That way we can safely assume that a sync has already happened in all the other guard AND we improve the UX

Yes that's exactly the context.
That "initial sync page" would be a page between login and navigation that would call and wait for `sync`?

The issue I see on that solution is that it will block the users and most of the times we don't need to, this is a very specific scenario and a sync in some scenarios can take a long time. I've talked a bit more with @justindbaur on DM and something he suggested was, in case multiple guards need it, to create a `waitUntilSynced` observable helper

**Comment by justindbaur** [comment]
A few thoughts:

1. A sync is always expected after a login, the problem could be that our login button is `await`ing all the necessary promises. If they were awaiting everything, including the final `router.navigate` call it would hopefully show the log in button in the loading state until all guards have said "yes", I would hope that largely removes the need for a sync in progress page.
2. My hope would be that relatively few full pages absolutely require a sync is completed. Even though they should expect that one does happen if they are an "authed" page. They would instead be a bit more reactive, they can start initially showing the skeleton of their page and show more local loading indicators that might need to wait for the sync to complete and then emitting their data once that is complete. This would avoid sending them to an intermediary page that they would hopefully be on for a very short period of time. The most obvious example of this is a users vault, we can send them there relatively quickly and as information is saved and decryptable it can just load into the page. 
3. We actually do have some indication of premium before a sync has happened, we have the user direct premium that is set from the access token we technically only need to wait on the sync if that isn't `true`.

**Comment by aj-rosado** [comment]
I have added a validation that in case the user hasPremium, it doesn't wait for the sync.

Adding await seems to not solve the button loading behaviour

**Review by ike-kottlowski — APPROVED** [review]

**Comment by coroiu** [comment]
@aj-rosado I'll hand the view of this PR over to @justindbaur since I think I'm missing some important context. That said, I still have some opinions on the solution which I'll share below :)

**My opinion**
I was wrong. I thought this was a common scenario and so I thought a sync page after login would make sense.
However, I still don't think we should putting syncs in guards. You said it yourself:

> it will block the users [...] and a sync in some scenarios can take a long time. 

While you meant for this to be a response to my suggestion with a separate page, I also think it applies to putting syncs in guards. Arguably it's worse in guards because the user will have no idea what is happening.

**My suggestion**
If we have an issue with the fact that we have to sync the entire vault with possibly thousands of items just to get a boolean value for `hasPremium`, then why not just add a new endpoint that returns only that information and wait for that in the guard instead?

**Pull request closed without merging**
