### PR TITLE
adjust max iterations for argon2

### PR DESCRIPTION
**Pull request by kspearrin**
ref https://bitwarden.atlassian.net/browse/PS-2404

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

People end up bricking their accounts by using values that are way out of bounds of modern day devices. This PR puts some guard rails on that by adjusting the iteration count maximum values for Argon2.

## Code changes

- **change-kfd.component.html:** Adjust client side validation for Argon2 iterations.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by kspearrin** [comment]
@quexten Any thoughts here? We are making this change based on recommendations from QA. For example, our QA engineer basically bricked his account by settings all maximum values: 1024 iterations, 1023mb memory, 16 parallelism. Limiting iterations seemed to be the most appropriate to prevent these kinds of issues.

**Comment by quexten** [comment]
Yeah, such high iteration counts only really make sense for super low memory setting, which we don't even allow. I agree limiting it is the best choice here.

By the way, how did the account get bricked? I would assume that if the web client can't handle the KDF for those values, the browser would just get stuck calculating the new key, and wouldn't be able to update the account settings.

**Comment by tangowithfoxtrot** [comment]
Hi, @quexten. I'm the QA engineer that tested this. To clarify: I waited ~35 minutes and ignored the "page unresponsive" dialog prompt, and the KDF settings were successfully applied to that account. I then tested decrypting that account on a different device, which took ~57 minutes, but the account data was still in-tact. I changed my iterations to a much more reasonable setting immediately after.

The bigger concern for me is just that many users might be tempted to close the page when it becomes unresponsive or take such a long amount of time and risk _actually_ bricking their vault data, but lowering the maximum allowed iterations should definitely help avoid that possibility.

**Comment by quexten** [comment]
> Hi, @quexten. I'm the QA engineer that tested this. To clarify: I waited ~35 minutes and ignored the "page unresponsive" dialog prompt, and the KDF settings were successfully applied to that account. I then tested decrypting that account on a different device, which took ~57 minutes, but the account data was still in-tact. I changed my iterations to a much more reasonable setting immediately after.
> 
> The bigger concern for me is just that many users might be tempted to close the page when it becomes unresponsive or take such a long amount of time and risk _actually_ bricking their vault data, but lowering the maximum allowed iterations should definitely help avoid that possibility.

Yeah, that's completely reasonable. Thanks for the clarification! Bricked sounded like somehow the wrong settings, or incorrect key got saved, so I was wondering if there was an undiscovered bug there. Glad that's not the case.

Anyways, I fully agree on lowering the bound for iterations to prevent this from happening.

**Review by withinfocus — APPROVED** [review]
I think this works well enough for release to protect our users in the referenced situation, but the combination of the three parameters can lead to weaknesses if say two of the three were especially low. It would be a valuable enhancement to add some client-side logic to recommend a target of the three, but that's gonna take some analysis.

**Pull request merged**
