### PR TITLE
[PM-13207] Detect incompatible locale changes

### PR DESCRIPTION
**Pull request by mzieniukbw**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13207

## 📔 Objective

Locale changes cannot include messages updates on existing message id's/keys. This is a how Crowdin works, once translation from english is completed, updates to english message will not cause re-translations in other languages.
To get around this problem, we tend to create new message id's/key's and stop referencing the old one in the new code.
But there is no validation at this moment that would check if the changes to `messages.json` locales respect the immutability of existing messages - which this PR intends to fix, by adding additional CI step into all PR.

### ℹ️ Notes
- Only validating English `messages.json`. Current list:
  > apps/browser/src/_locales/en/messages.json
  >apps/cli/src/locales/en/messages.json
  > apps/desktop/src/locales/en/messages.json
  > apps/web/src/locales/en/messages.json
- Errors when message id/key changed and suggests an alternative (new message id/key)

## 📸 Screenshots

See #11426 and new workflow: https://github.com/bitwarden/clients/actions/runs/11199726589/job/31132423924?pr=11426

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by michalchecinski — APPROVED** [review]
LGTM

**Review by djsmith85 — APPROVED** [review]
Thanks again @mzieniukbw, this is great!

Some future ideas for improvement would be:
- A duplicate key detection (usually happens when resolving a merge conflict badly)
- Erroring if any files other than `en/messages.json` get edited. Only valid on the crowdin-sync branches (`crowdin-auto-sync-*`)

**Comment by mzieniukbw** [comment]
@djsmith85 i have tried to add duplicate key detection, but was not able to, since `JSON.parse` returns JS object, so no duplicate fields.
Erroring on non-english `messages.json` being edited - i though that's how we override non-english translations, so in those cases editing existing keys should be valid, hence why the CI only runs on `en/messages.json`

**Comment by djsmith85** [comment]
> @djsmith85 i have tried to add duplicate key detection, but was not able to, since `JSON.parse` returns JS object, so no duplicate fields. Erroring on non-english `messages.json` being edited - i though that's how we override non-english translations, so in those cases editing existing keys should be valid, hence why the CI only runs on `en/messages.json`
@mzieniukbw 
- Duplicate keys: Hm okay, it has happened maybe twice since I've been involved with the translations, so not a high priority thing.
- With editing non-english `messages.json` I mean any kind of edit. Nothing other than the Crowdin-Sync should be modifying those files.

**Pull request merged**
