### PR TITLE
[PM-12765] - add subscription validation to member dialog

### PR DESCRIPTION
**Pull request by jaasen-livefront**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12765

## 📔 Objective

This PR adds additional validation to the org member dialog to ensure the org has a valid subscription and before running any other validation like number of seats.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by kendratodd** [comment]
The code changes here seem fine to me, but I'm not currently able to test this one locally. I'm going to defer to someone from @bitwarden/team-admin-console-dev for a  proper review.

**Review by eliykat — CHANGES_REQUESTED** [review]
We currently validate autoscaling and subscription changes server-side - some client-side validation is here for inline form errors, but that's the exception. Given that this is just showing an error toast on submit which is how server errors are displayed anyway, I recommend this validation is moved into the existing validation logic on the server. In particular, take a look at `OrganizationService.CanScaleAsync` which validates autoscaling.

**Comment by jaasen-livefront** [comment]
@eliykat @kendratodd Sounds like we need to reassign this to the api team?

**Comment by eliykat** [comment]
@jaasen-livefront there isn't any Api team, our domain teams own both front-end and back-end code. In this case, `OrganizationService` in `server` is formally owned by Admin Console Team, but it contains a lot of billing-related code. Handling autoscaling falls within the Billing Team domain, so I'd like this to stay with Billing Team. You may have to check back in with the team as to how they want to handle this ticket.

I'm happy to pair with whoever works on it if they need some orientation in this part of the code.

**Comment by cturnbull-bitwarden** [comment]
Closing this PR and reassigning to Jonas to handle the backend change

**Pull request closed without merging**
