### PR TITLE
[PS-1950] [PS-1211] Added autofill for textareas

### PR DESCRIPTION
**Pull request by mr-manuel**
## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective

Be able to use autofill also for textareas. https://github.com/bitwarden/clients/issues/1966

## Code changes

- **https://github.com/mr-manuel/bitwarden_autofill_clients/commit/dbb7b6ec6d9e1a3700514d82cc8b00048480cd7b** Added textarea tag in order to use autofill also on textareas.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

Accidentially deleted repo, old pull request: https://github.com/bitwarden/clients/pull/3192

### CODE REVIEW

**Comment by olluz** [comment]
I wonder why such a small change takes several years to fix. Even worse: Now with an already available PR...Nobody cares to review it ???

**Review by fabiengagne — DISMISSED** [review]
This is a very small change with virtually no risk.
I recommend this request be approved.

**Comment by mr-manuel** [comment]
I updated my fork and made the changes again, so there are no conflicts.

**Comment by levihb** [comment]
Merge this you donkeys

**Comment by dbosompem** [comment]
Hi @mr-manuel , thanks for updating. Just an update that the team has picked this up internally and we'd communicate with you to ensure this is merged. Thank you for your patience.

**Comment by jprusik** [comment]
Hi @mr-manuel - thanks for your contribution! I've moved this PR to QA for testing.

**Review by jprusik — APPROVED** [review]

**Pull request merged**
