### PR TITLE
[PM-10399] Add ssh key import export for bitwarden json

### PR DESCRIPTION
**Pull request by quexten**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10399

## 📔 Objective

Add import / export for ssh key item type for the bitwarden json export format.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by quexten** [comment]
Changing to ready for review. Target branch might still change, but the export format should be pretty solid.

**Review by djsmith85 — CHANGES_REQUESTED** [review]
Changes are looking good. Just some lint issue and a failing test according to the PR workflows. Once those are addressed, this is good to go. 

Thank you for remembering to include the item type with the import/export

**Comment by quexten** [comment]
Updated and fixed linting / test errors.

**Review by djsmith85 — APPROVED** [review]
Nice work and looking forward to have this included

**Comment by quexten** [comment]
Re-based and merged to the feature branch (will be tested later on the feature branch).

**Pull request merged**
