### PR TITLE
[PM-4406] fix bit-select popover not visible on zoomed browser extension

### PR DESCRIPTION
**Pull request by willmartian**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fixes an issue where the dropdown for `bit-select` and `bit-multi-select` was not visible on a browser extension page with zoom greater than 100%. 

## Code changes

- **libs/components/src/multi-select/multi-select.component.html:** set `appendTo` to `"app-root"`
- **libs/components/src/select/select.component.html:** set `appendTo` to `"app-root"`

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by coroiu — CHANGES_REQUESTED** [review]
Looks good but broken in storybook

**Comment by willmartian** [comment]
The selector components now expect `app-root` as an ancestor, which Storybook currently doesn't provide. We will need to update the story wrapper to include it.

**Comment by willmartian** [comment]
[f09b6ae](https://github.com/bitwarden/clients/pull/6682/commits/f09b6ae6f2dc8961db2cef624fac1afd57c3d317) fixes Storybook, but this PR introduces an issue where the extension save bar misaligns the select popover:

https://github.com/bitwarden/clients/assets/17113462/5026488b-aa6d-476e-89ba-93a24a4c1444

**Comment by stefan0xC** [comment]
@willmartian after reading the [ng-select README](https://github.com/ng-select/ng-select/blob/1497f19df6c31580b90cb3780f005aaf2b278eed/README.md?plain=1#L167) I think I found the issue:

> For correct positioning `body` should have `position:relative`

**Pull request closed without merging**
