### PR TITLE
Add eslint rule no-floating-promises

### PR DESCRIPTION
**Pull request by willmartian**
## Type of change

- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Floating promises can causes errors. See rule [docs.](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md)

This PR enables an eslint rule to catch them, and adds a disable comment to all occurrences. 

## Code changes

- **file.ext:** Description of what was changed and why

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by jprusik — APPROVED** [review]
Approved for autofill

**Review by justindbaur — APPROVED** [review]
Thank you! This should maybe prompt a discussion on if `router.navigate` should be awaited. I don't see angular even awaiting it in their docs.

**Review by JaredSnider-Bitwarden — APPROVED** [review]
Approving for auth

**Review by jlf0dev — APPROVED** [review]
Approving for Auth!

**Review by audrey-jensen — APPROVED** [review]
This looks pretty straightforward.

🤔 Wonder whether the lint should [set the `ignoreVoid` flag](https://typescript-eslint.io/rules/no-floating-promises/#ignorevoid). The exporters have async setup/teardown but jest's  `beforeEach` doesn't support async/await. Being able to annotate those cases with `void` would indicate this is expected and not muddy the test code w/ disable lint comments.

**Review by Hinton — APPROVED** [review]
CL code looks good.

**Review by addisonbeck — APPROVED** [review]

**Review by gbubemismith — APPROVED** [review]

**Pull request merged**
