### PR TITLE
[PM-4293] Update duo and add allow-popups and allow-popups-to-escape-sandbox

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Duo needs the `allow-popups` and `allow-popups-to-escape-sandbox` permissions to function correctly with yubikeys.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by JaredSnider-Bitwarden — APPROVED** [review]
LGTM!

**Comment by JBLeung** [comment]
The pull request has been merged successfully, yet the underlying issues persist.

**Comment by ArtifactLabsOfficial-Jeff** [comment]
image

**Comment by Hinton** [comment]
@JBLeung it's merged but not released yet.

**Comment by JBLeung** [comment]
What is the expected deployment schedule? I have been unable to log into Bitwarden for the past two weeks.

**Comment by b1tzer0** [comment]
I am wanting to know the same, I would really like to be able to access my account as well.

**Pull request merged**
