### PR TITLE
SM-717-proj

### PR DESCRIPTION
**Pull request by cd-bitwarden**
## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

focus on project name when you open create a new project.

## Code changes

bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-dialog.component.ts - on page load set focus on projectName element

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by Thomas-Avery — CHANGES_REQUESTED** [review]
Can we update the service account and secret dialogs in this PR too?

**Review by Thomas-Avery — APPROVED** [review]
LGTM

**Comment by cd-bitwarden** [comment]
@Thomas-Avery QA noticed I missed a modal, so I added it to the create new access token and updated the PR :)

**Review by Thomas-Avery — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
