### PR TITLE
[PM-13928]use the user's email address in owner dropdown rather than "You"

### PR DESCRIPTION
**Pull request by nick-livefront**
## 🎟️ Tracking

[PM-13928](https://bitwarden.atlassian.net/browse/PM-13928)

## 📔 Objective

Update the Owner dropdown to display the user's email rather than "You"
- I have an open question to Danielle in the ticket about if this should also be displayed on the individual vault. Currently the dropdown is shown as empty.

## 📸 Screenshots

|Before|After|
|-|-|
|Screenshot 2024-10-30 at 2 16 28 PM|Screenshot 2024-10-30 at 2 14 30 PM|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-13928]: https://bitwarden.atlassian.net/browse/PM-13928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by shane-melton — DISMISSED** [review]

**Comment by nick-livefront** [comment]
@shane-melton Danielle got back to me in the ticket, I added a commit to show the user's email address in the individual vault as well. This required a little more logic: [669bec7](https://github.com/bitwarden/clients/pull/11798/commits/669bec74433f146b65dba852b59cdfaa3cde1f93)

Screenshot 2024-10-31 at 8 01 51 AM

**Review by shane-melton — CHANGES_REQUESTED** [review]
Changes look good! But we broke the storybook with the `AccountService` dependency.

**Comment by nick-livefront** [comment]
> Changes look good! But we broke the storybook with the AccountService dependency.

Updated: [1cad02f](https://github.com/bitwarden/clients/pull/11798/commits/1cad02f97c09316da9a02c42ecc5f87d0ec26e1e)

@shane-melton Is there work to do here for the Chromatic checks?
Screenshot 2024-10-31 at 7 56 27 PM

**Comment by nick-livefront** [comment]
> @nick-livefront We just need to go into Chromatic (clicking "details") and approve the changes made (in this case going from "You" -> "[test@email.com](mailto:test@email.com)"). I'm not sure if you have access, so I already took care of them.
> 
> There is one un-related Chromatic test I left un approved, but you should be good to merge still.

@shane-melton Sweet, I was able to log in with my github account and see the difference so I believe I would have been able to accept them.

I need an approval to merge 😄

**Review by shane-melton — APPROVED** [review]

**Pull request merged**
