### PR TITLE
[PM-10375] Remove Identity Margin

### PR DESCRIPTION
**Pull request by nick-livefront**
## 🎟️ Tracking

[PM-10375](https://bitwarden.atlassian.net/browse/PM-10375)

## 📔 Objective

Removes the margin from the last field in each identity section.
- With each field being dynamically shown this was a little more involved than I anticipated. I think there are a couple ways to shorten this code up using some `Object.keys` tricks but I opted for the simple and straight forward here. 

## 📸 Screenshots

https://github.com/user-attachments/assets/9c1f3b04-d172-41ae-b979-e3a332fe806c

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-10375]: https://bitwarden.atlassian.net/browse/PM-10375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by shane-melton** [comment]
Tagging the design system team in case they have any suggestions / ideas to better handle this without so much verbosity in the component w.r.t. to disabling margins.

**Comment by shane-melton** [comment]
@nick-livefront After chatting with @vleague2 about this a bit, she gave an example of this magical Tailwind/CSS selector we can use on the parent containers instead of setting the `disableMargin` attribute manually and having to track which fields are shown. For example:

```<bit-card class="[&_bit-form-field]:last-of-type:tw-mb-0">```

I think we should give this a try instead, unless you run into some unexpected issue or think otherwise!

**Comment by nick-livefront** [comment]
> @nick-livefront After chatting with @vleague2 about this a bit, she gave an example of this magical Tailwind/CSS selector we can use on the parent containers instead of setting the `disableMargin` attribute manually and having to track which fields are shown. For example:
> 
> `<bit-card class="[&_bit-form-field]:last-of-type:tw-mb-0">`
> 
> I think we should give this a try instead, unless you run into some unexpected issue or think otherwise!

@vleague2 absolutely magic. 👏 👏 [0fc135a](https://github.com/bitwarden/clients/pull/10349/commits/0fc135ab8020f94536fe9421a17542c12fea5bf0)

**Review by Jingo88 — APPROVED** [review]

**Review by shane-melton — APPROVED** [review]
🪄

**Pull request merged**
