### PR TITLE
[PM-4791] Injected content scripts prevent proper XML file display and disrupt XML responses

### PR DESCRIPTION
**Pull request by cagonzalezcs**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Resolves https://github.com/bitwarden/clients/issues/6865

An issue exists when the extension injects the `page-script.ts` content script into non `text/html` content type documents. Due to the injection, the presentation of XML documents and any web response handled as XML becomes corrupted. 

To resolve this, two changes are being made. First we are adding a check within the `fido2/content-script.ts` script that validates the `document.contentType` is a `text/html` type. The second is a modification within the `manifest.json` that ignores any routes that contain a `.xml` reference within the URL. These two elements combined ensure we are deliberately avoiding injection of the content script into XML documents, as well as other non-html document types.

## Code changes

- **apps/browser/src/manifest.json:** Refining URL match patterns and incorporating an `exclude_matches` pattern that will exclude any XML documents when content scripts are being injected.
- **apps/browser/src/manifest.v3.json:** Applying the same refinements to manifest v3.
- **apps/browser/src/vault/fido2/content/content-script.ts:** Adding a check to validate the `document.contenType` before continuing with execution of the `fido2/content-script.ts` behavior.

## Demo of the issue with a refresh to show the fix

https://github.com/bitwarden/clients/assets/16629865/a3460ff4-4b63-4841-8519-760f549c0259

### CODE REVIEW

**Comment by kepstin** [comment]
Code change seems functionally equivalent to some hacking on the script that I did when trying to figure out the cause of the issue in https://github.com/bitwarden/clients/issues/6865#issuecomment-1854321285 - should work.

Please double-check whether the manifest permissions change to add `"*://*/*"` causes extension updates to be blocked pending a permissions prompt in Firefox. If it does, it might be better to avoid that.

**Comment by cagonzalezcs** [comment]
@kepstin 

Have you experienced a block when having this reviewed by Firefox?

`"https://*/*", "http://*/*` as a URL match pattern is functionally equivalent to `"*://*/*"`

**Comment by coroiu** [comment]
Technically we should be able to remove `http://*` and eventually replace it with `http://localhost/*`. WebAuthn should only be available over `https`, and the localhost rule is a exception that we are planning on implementing.

**Review by coroiu — DISMISSED** [review]

**Comment by cagonzalezcs** [comment]
@coroiu 

If that's the case, then it would make sense to separate the static content script declarations for `trigger-autofill-script-injection.js` and `trigger-fido2-content-script-injection.js` to match in different ways. The autofill work should still match for `http://` routes, but if Fido2 should never run on anything other than `https://` then we should separate that out.

**Comment by hjalm8** [comment]
Could you also include the same exceptions for SVG files?

**Review by shane-melton — APPROVED** [review]

**Pull request merged**
