### PR TITLE
[PS-1604] Design: Tweak styles for browser/desktop selects and desktop form groups

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

A slight visual tweak. Currently, `<select>`s used in the browser popup and the desktop app are (subjectively) far too small/claustrophobic looking.

In addition, in the desktop app, particularly under the Settings, `<select>`s are not always 100% wide, and  form groups are far too closely bunched up together.

Overall, this makes both looks quite shoddy and unpolished.

This PR adds padding to the `<select>`s, makes sure they're always set to 100% width, and for desktop increases the bottom margin to make the forms (particularly in Settings) breathe a bit and provide more visual clarity.

## Code changes

- **apps/browser/src/popup/scss/base.scss** and **apps/desktop/src/scss/base.scss**: add explicit styles to make `select` 100% wide and give it some padding
- **apps/desktop/src/scss/misc.scss**: increase the bottom margin for `.form.form-group`

### Browser popup before (left) / after (right) combined shots:

browser-settings

---

browser-settings-options1

browser-settings-options2

---

browser-send

---

browser-cipher-edit1

browser-cipher-edit2

---

browser-cipher-add1

browser-cipher-add2

### Desktop before / after separate shots

desktop-export-before

desktop-export-after

---

desktop-settings-before

desktop-settings-after

---

desktop-cipher-before

bitwarden-cipher-after

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by patrickhlauke** [comment]
related: sadly, the down-arrow/chevron for `<select>`s doesn't take its cue by default from the padding, otherwise I'd have gone a bit heavier on it...but then it just starts looking odd (and didn't fancy going down the route of redoing the chevron myself from scratch) https://twitter.com/patrick_h_lauke/status/1575182409573670912

**Review by danielleflinn — APPROVED** [review]

**Comment by patrickhlauke** [comment]
any reason why @bitwarden-bot didn't do its usual tagging/changing title?

**Comment by djsmith85** [comment]
Hi @patrickhlauke, we did some internal migrations over the weekend and the @bitwarden-bot has had a slight hiccup. I've reported this to the team once I noticed it and we are working on getting it up and running again.

**Review by djsmith85 — APPROVED** [review]
@patrickhlauke This is looking good and thank you for the constant stream of little tweaks.

**Comment by patrickhlauke** [comment]
my pleasure. scratching my own itches, mainly ;)

**Pull request merged**
