### PR TITLE
[PM-3732] Use subtle to make aes keys

### PR DESCRIPTION
**Pull request by MGibson1**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Uses generateKey in subtle crypto get generate material used either directly as keys or used to generate keys for aes.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by cagonzalezcs — APPROVED** [review]
Changes look good from my side. Willing to bet Auth Team might have more feedback.

**Review by JaredSnider-Bitwarden — DISMISSED** [review]
LGTM!

**Review by Thomas-Avery — COMMENTED** [review]
SM changes look good, should look into why the unit test is failing.

**Review by djsmith85 — APPROVED** [review]
Approving for tools

**Review by JaredSnider-Bitwarden — APPROVED** [review]
LGTM!

**Review by Hinton — APPROVED** [review]
LGTM

**Review by Thomas-Avery — APPROVED** [review]

**Pull request merged**
