### PR TITLE
[AC-1518] Remove extra v2 from generated SCIM url

### PR DESCRIPTION
**Pull request by vincentsalucci**
## Type of change
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Code changes
- **environment.service.ts:** Removed `v2` from both the `usUrls` and `euUrls`. Any adjustment to the url is handled within the `getScimUrl` method. 

## Discussion
I couldn't replicate this issue locally or using qaCloud but did realize a potential issue while debugging. While setting the region, we set the internal urls of the `environment.service` using the defined `usUrls` and `euUrls` objects. Both of those lists included `.../v2` at the end of the SCIM which is used as the base and adjusted within the `getScimUrl` method. There **might** be some kind of race condition between the service initialization `init.service` and the construction of the `environment.service` itself due to the intermittent nature of the bug - I wasn't able to successfully conclude this, however.  My urls were coming back as expected and not being overridden via the lists mentioned above. Open for feedback!

## Before you submit
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by trmartin4** [comment]
I am seeing the same race condition in the QA Cloud environment and when testing locally with the web client.  I've got https://github.com/bitwarden/clients/pull/5830 as a Draft PR to try to band-aid that race condition until a more intensive refactor can take place.  I'm testing this out now.

**Review by r-tome — COMMENTED** [review]
Line 174 should also be changed.

I think the SCIM url isn't used anywhere in clients though.

**Comment by vincentsalucci** [comment]
> Line 174 should also be changed.
> 
> I think the SCIM url isn't used anywhere in clients though.

I'm not sure I follow. The SCIM url is pulled from environment service, adjusted with the `orgId` and then shown via the `ScimComponent`. Any adjustment of the base URL comes from the `getScimUrl` method in the `environment.service`.

**Comment by r-tome** [comment]
> > Line 174 should also be changed.
> > I think the SCIM url isn't used anywhere in clients though.
> 
> I'm not sure I follow. The base SCIM url is pulled from environment service, adjusted with the `orgId` in the `ScimComponent` and shown there. Any adjustment of the base URL comes from the `getScimUrl` method in the `environment.service`.

You're right, I missed that. My bad!

**Review by justindbaur — APPROVED** [review]
LGTM

**Pull request merged**
