### PR TITLE
[PS-1387] Desktop: Remove "delete account" from settings

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

<s>`<a>` is not keyboard-focusable/operable. `<button>` is. giving it a `.danger` styling because...well...it's dangerous
this also makes the control far more obvious - before, it was almost imperceptible (which perhaps was the point, but made it very difficult to actually find this when you do need it)</s>

Per https://github.com/bitwarden/clients/pull/3406#issuecomment-1230941693 the plan is to remove the delete option altogether as it's redundant. PR modified to do just that.

Closes https://github.com/bitwarden/clients/issues/3401

## Code changes

- **apps/desktop/src/app/accounts/settings.component.html**: removes the "Delete Account" section from the desktop settings.
-  **apps/desktop/src/app/accounts/settings.component.ts**: remove `openDeleteAccount` and `DeleteAccountComponent` import

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Comment by sukhleenb** [comment]
We will be removing this option from the settings modal in an upcoming release as users can delete their account from the Account menu. For that reason, we won’t add this enhancement. If you’d like to change your PR to remove the delete account section / option from the modal, we will happily accept it.

**Comment by patrickhlauke** [comment]
@sukhleenb 

> If you’d like to change your PR to remove the delete account section / option from the modal, we will happily accept it.

done

**Review by sukhleenb — APPROVED** [review]

**Review by Hinton — CHANGES_REQUESTED** [review]
We can also remove the `openDeleteAccount` in `settings.component.ts`. Line 443-445. + the import to that file.

**Comment by patrickhlauke** [comment]
> We can also remove the `openDeleteAccount` in `settings.component.ts`. Line 443-445. + the import to `DeleteAccountComponent`.

done

**Review by Hinton — APPROVED** [review]
This looks good from a code perspective.

**Review by sukhleenb — APPROVED** [review]

**Comment by Hinton** [comment]
Merged, thanks for the contribution @patrickhlauke!

**Comment by patrickhlauke** [comment]
@Hinton my pleasure, as always :)

**Pull request merged**
