### PR TITLE
[PM-2340] Enable use-lifecycle-interface

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Enables one of the recommended rules of `@angular-eslint`. Since this rule was fairly trivial to fix and has no QA effects it seemed reasonable to migrate all code.

## Code changes

- **.eslintrc.json:** Add `"plugin:@angular-eslint/recommended",` to extends, and disables all rules but `use-lifecycle-interface`. This should let us incrementally turn on more rules afterwards. `use-lifecycle-interface` defaults to a warning however I changed it to error since it will otherwise be easy to miss.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by vincentsalucci — DISMISSED** [review]
Seems minimally invasive and straightforward to me!

**Review by willmartian — APPROVED** [review]

**Review by cturnbull-bitwarden — APPROVED** [review]

**Review by djsmith85 — DISMISSED** [review]
Approving for Tools

**Review by willmartian — APPROVED** [review]
Approved for CL, thanks!

**Review by rr-bw — APPROVED** [review]
Approved for Auth

**Review by willmartian — DISMISSED** [review]

**Review by willmartian — DISMISSED** [review]

**Review by djsmith85 — APPROVED** [review]
Approving for tools

**Review by LRNcardozoWDF — APPROVED** [review]

**Review by djsmith85 — APPROVED** [review]

**Review by cturnbull-bitwarden — APPROVED** [review]

**Review by willmartian — APPROVED** [review]

**Review by rr-bw — APPROVED** [review]

**Review by gbubemismith — APPROVED** [review]

**Review by vincentsalucci — APPROVED** [review]

**Review by coltonhurst — APPROVED** [review]
SM files look good.

**Pull request merged**
