### PR TITLE
[PM-7413] fix(8560): refreshing reports pages displays empty pages

### LINKED ISSUE #8560: Refreshing any reports pages leads to the displaying an empty state
### Steps To Reproduce

1. Go to reports page '#/reports'
2. Click on any report page, for example 'Reused passwords'
3. Results appears
4. Refresh the page

### Expected Result

Shows the report's results

### Actual Result

'Good news' empty state appears

### Screenshots or Videos

image

### Additional Context

_No response_

### Operating System

macOS

### Operating System Version

_No response_

### Web Browser

Chrome

### Browser Version

_No response_

### Build Version

Current production version

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by abarghoud**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Resolved #8560, ciphers data are lost when refreshing reports pages

## Code changes

- **cipher-report.component.ts**: Adds a call to `syncService.fullSync(false)` in the `load()` method
- **admin-console/organizations/tools/*-report.component.ts**: addition of syncService dependency
- **tools/reports/pages/*-report.component.ts**: addition of syncService dependency
- ***.spec.ts**: addition of a test to make sure `syncService.fullSync(false)` is called

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by abarghoud** [comment]
I fixed it this way, but I think it could be resolved differently with resolvers, defined at routes level, which blocks the access to the page till all necessary data is fetched, I did not see it implemented elsewhere int the repo.

**Comment by eliykat** [comment]
The main operational change here is to `cipher-report.component.ts` which is owned by @bitwarden/team-tools-dev so I'll defer to them on the review. If that is approved then the AC Team changes are uncontroversial.

**Review by aj-rosado — APPROVED** [review]
Thank you for your contribution @abarghoud !

This change seems to fix the issue, I'm passing it to QA testing.

**Review by r-tome — APPROVED** [review]

**Comment by aj-rosado** [comment]
@abarghoud there are some changes on the reports files that are conflicting with the changes on this PR.
Can you merge this branch with the most recent version from main and resolve the conflicts please?

If you can't, could you give me permission to push into your repository so that I can fix them?

thank you!

**Comment by abarghoud** [comment]
> @abarghoud there are some changes on the reports files that are conflicting with the changes on this PR. Can you merge this branch with the most recent version from main and resolve the conflicts please?
> 
> If you can't, could you give me permission to push into your repository so that I can fix them?
> 
> thank you!

@aj-rosado Done ;)

**Review by r-tome — APPROVED** [review]

**Review by aj-rosado — APPROVED** [review]

**Comment by aj-rosado** [comment]
Thank you for your contribution @abarghoud ! QA has approved it and has been merged into main!

This will be part of the next release ! 🎉

**Pull request merged**
