### PR TITLE
Tools/pm 4440 replace lastpass sso dialog

### PR DESCRIPTION
**Pull request by ttalty**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Replace the lastpass-sso specific dialog with the component library simple dialog. 

## Code changes

- **libs/importer/src/components/lastpass/lastpass-direct-import.service.ts:** Removed the lastpass dialog component, added the i18n service for the text for the title, description, and button text. Removing the opening of the lastpass dialog and using openSimpleDialog
- **libs/importer/src/components/lastpass/dialog/index.ts:** Removing the reference to the lastpass sso dialog.
- **libs/importer/src/components/lastpass/dialog/lastpass-await-sso-dialog.component.ts:** Deleting the component
- **libs/importer/src/components/lastpass/dialog/lastpass-await-sso-dialog.component.html:** Deleting the component

## Screenshots

Previous lastpass specific dialog:
image

New implementation of the simple dialog:
image

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by djsmith85 — COMMENTED** [review]
@ttalty Nice one, this should simplify the codebase around that feature. Could you please add a before screenshot to show the visual different.

As this aims to replace the existing dialog, please delete the old dialog.

**Comment by ttalty** [comment]
@djsmith85 Added the before screenshot. Is the button styling an issue? I was torn on this. As the component library really only shows one dialog with just one button which uses the primary color button. Not the secondary color like the previous lastpass dialog.

**Comment by djsmith85** [comment]
> @djsmith85 Added the before screenshot. Is the button styling an issue? I was torn on this. As the component library really only shows one dialog with just one button which uses the primary color button. Not the secondary color like the previous lastpass dialog.

Please speak with @willmartian about it. The [SimpleDialog](https://github.com/bitwarden/clients/blob/main/libs/components/src/dialog/simple-dialog/simple-configurable-dialog/simple-configurable-dialog.component.ts) currently does not support only having cancel-button. You are working around it as you tell the AcceptButton to have the caption: "Cancel".

As this is the only button on the Form/Dialog I think it still might be valid to use the primary color.

**Comment by willmartian** [comment]
Yeah, this is a limitation of the simple dialog implementation. 

> As this is the only button on the Form/Dialog I think it still might be valid to use the primary color.

I think this is fine, but I would defer to @bitwarden/dept-design. Generally, should "cancel" actions always use the secondary button style?

**Review by djsmith85 — APPROVED** [review]
Approving and as long as Design doesn't have any change requests, this is ready to get passed on to QA.

**Review by danielleflinn — APPROVED** [review]

**Pull request merged**
