### PR TITLE
[PM-3155] CLI: Editing a cipher with a non-discoverable passkey causes the passkey to be removed

### PR DESCRIPTION
**Pull request by gbubemismith**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Preserve the non-discoverable passkey when a cipher is edited through the CLI.

## Code changes
This bug was caused due to the absence of the `fido2Key` property in the login export class that could retain the passkey information during the editing process. To resolve this, a new `fido2keyexport` class has been created with properties to be set when a login cipher is being edited, and a fido2Key property has been added to the login export class to preserve the non-discoverable passkey.

- **libs/common/src/models/export/fido2key.export.ts:** Created a `fido2keyexport` class with properties that can be set when a login cipher is edited.
- **libs/common/src/models/export/login.export.ts:** Added the `fido2Key` property to the `login export` class.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by gbubemismith** [comment]
**🚨NOTE TO SELF🚨**

Merge [PM-2270](https://github.com/bitwarden/clients/pull/6005) before this.

**Review by differsthecat — COMMENTED** [review]
This looks good, one question though!
Do we need to add this type to `getTemplate()` in `/apps/cli/src/commands/get.command.ts`? It looks like that is where the model template methods are called for the other item export models.

**Comment by gbubemismith** [comment]
> This looks good, one question though! Do we need to add this type to `getTemplate()` in `/apps/cli/src/commands/get.command.ts`? It looks like that is where the model template methods are called for the other item export models.

Yeah needed to add it on the `LoginExport`

**Review by aj-rosado — APPROVED** [review]
Changes are LGTM!

**Review by differsthecat — APPROVED** [review]

**Pull request merged**
