### PR TITLE
[PM-1823] Defining the card brand according to its number

### PR DESCRIPTION
**Pull request by tarv7**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Set card brand automatically via card numbers

## Code changes

It is not necessary

## Screenshots
https://user-images.githubusercontent.com/15661066/231914535-342117ec-9b68-4493-a254-ff354ee6c855.mp4

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by djsmith85** [comment]
@tarv7 Thank you for your contribution. 

I just glanced over this and we have something similar in the importers to [set the card-brand](https://github.com/bitwarden/clients/blob/b3d4d9898e0eb196e872501246c1856ccdcbf993/libs/importer/src/importers/base-importer.ts#L245). 

Do you think we might be able to combine the two to only have one area to change, if we want to add more credit-card brands in the future?

**Comment by tarv7** [comment]
> @tarv7 Thank you for your contribution.
> 
> I just glanced over this and we have something similar in the importers to [set the card-brand](https://github.com/bitwarden/clients/blob/b3d4d9898e0eb196e872501246c1856ccdcbf993/libs/importer/src/importers/base-importer.ts#L245).
> 
> Do you think we might be able to combine the two to only have one area to change, if we want to add more credit-card brands in the future?

Great idea!
I made the change. Could you review it again please?

**Review by djsmith85 — CHANGES_REQUESTED** [review]
Hi @tarv7,

I spoke with team-vault-dev about the changes affecting the card-viewmodel.

I think we'd prefer to have a method that is called with the cc-number as a param instead of a getter.

Same as we had before within the [getCardBrand](https://github.com/bitwarden/clients/pull/5204/files#diff-f6e39b8b189eaa04cee692198a2ab628b59ec1ebb678b406584939b4463795e3L245) in the `baseImporter`

So please rename and alter the method signature of the getter:
```
onCardNumberChange(): void {
    this.cipher.card.brand = this.cipher.card.getcardBrandByPatterns(this.cipher.card.number);
  }
```
...or any other/better name you can come up with.

The reason being that someone wanting to use this outside of the `onCardNumberChange` (.i.e [importers](https://github.com/bitwarden/clients/pull/5204/files#diff-f4f09d0269ea57929552c88fa6ceda05ac4af39199989612f4823db8192a2f24L51-R51)) would need to know to set the cc-number on the view-model before calling `cardBrandByPatterns`

One last thing:  We strive to have feature parity across all clients. Could you please add the `onCardNumberChange`-logic also to the web and desktop client

Kind regards,
Daniel

**Review by tarv7 — COMMENTED** [review]
@djsmith85, great suggestions! Thanks for the collaboration!

I apologize for the delay in making the changes. But now it's done.
I preferred to transform the getCardBrandByPatterns method, I think it makes more sense in this context. But if it's not to your liking, I can implement it as requested.

Let me know if you need any further changes. I will be available if necessary.

**Review by djsmith85 — APPROVED** [review]
@tarv7 Thank you for returning and incorporating the feeback.

From my side this is looking good. Just going to wait on a review from team-vault-dev

**Review by differsthecat — APPROVED** [review]
This looks good from the Vault team, thank you for your work on this @tarv7 ! 🎉

**Comment by djsmith85** [comment]
@tarv7: QA has approved your changes and these are ready to get merged. Your changes will be included in the `2023.6` release. Thank you for your contribution!

**Pull request merged**
