### PR TITLE
PM-238 Master Reprompt Enabled Appears on Item in Organization

### PR DESCRIPTION
**Pull request by Jingo88**
```
- [ X ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When a user enables the master reprompt on an item in the organization vault, the password reprompt modal should appear on the next click of the item. 

Previously it would only appear after a refresh. 

## Code changes

- removed the `saveCipher` logic from the `add-edit.component` inside the org-vault
- updated the `saveCipher` method in the base `add-edit.component` inside libs to add additional parameters to the cipherService call
- updated `createWithServer` and `updateWithServer` inside of the `cipher.service.ts` to call the `apiService` `postCipherAdmin` and/or `putCipherAdmin` if the add-edit save is coming from an organization admin. 

## Video

https://github.com/bitwarden/clients/assets/8302660/f43c9640-ab1a-41f3-810d-09aa1a4018e0

### CODE REVIEW

**Review by differsthecat — CHANGES_REQUESTED** [review]
I think you need to update the method signature of all of the call sites for `createWithServer` and `updateWithServer` as well.

A quick search for `updateWithServer` is showing these sites as well:
Screenshot 2023-07-19 at 4 36 41 PM

**Comment by Jingo88** [comment]
> I think you need to update the method signature of all of the call sites for `createWithServer` and `updateWithServer` as well.
> 
> A quick search for `updateWithServer` is showing these sites as well: Screenshot 2023-07-19 at 4 36 41 PM

ah thanks for that. So I updated the code where the new params are optional. How do we feel about this?

**Review by differsthecat — COMMENTED** [review]
Much better, thanks @Jingo88 !

One last thing while you are here; can you add unit tests for these methods to `cipher.service.spec.ts`? We need to get more of our code tested and this is a good opportunity to add some 😄

**Review by differsthecat — DISMISSED** [review]
Good solution on the cipher service side, and thank you for the test updates! 🪨 ⭐

**Review by differsthecat — APPROVED** [review]
Looks good!

**Pull request merged**
