### PR TITLE
[PM-3554] Add support for alias creation via self-hosted SimpleLogin

### PR DESCRIPTION
**Pull request by djsmith85**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Extending username-generation to self-hosted SimpleLogin analogue to https://github.com/bitwarden/clients/pull/4056
## Code changes

- **generator.component.html:** Display Server url field which a user can edit to point to their self-hosted instance of SimpleLogin. In the web-vault only visible when also self-hosting Bitwarden. Users will need to edit their Nginx and CSP rules to allow traffic to/from their SimpleLogin instance.
- **libs/common/src/tools/generator/username/email-forwarders/forwarder-options.ts:** Extend forwarder-options to include additional for SimpleLogin
- **libs/common/src/tools/generator/username/email-forwarders/simple-login-forwarder.ts:** Use server-url set in SimpleLogin-options (default cloud or custom)
- **libs/common/src/tools/generator/username/username-generation-options.ts:** Extend type to include forwardedSimpleLoginBaseUrl
- **libs/common/src/tools/generator/username/username-generation.service.ts:** Set default-url for forwardedSimpleLoginBaseUrl

### Browser
browser

### Desktop
Desktop

### Web
Web

* Shows the web-vault of a self-hosted BW instance. On Cloud the Server-Url-field is hidden.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by DNCD** [comment]
Any update on this?

**Review by aj-rosado — APPROVED** [review]
LGTM

**Comment by timespaced** [comment]
Looks like it's close!  Thanks for all the work on this!

**Comment by jeisonbeast** [comment]
Thank you so much @aj-rosado and @djsmith85. will this be included in the upcoming 2023.10-release? Thank you!

**Comment by djsmith85** [comment]
> Thank you so much @aj-rosado and @djsmith85. will this be included in the upcoming 2023.10-release? Thank you!

We are aiming for it. This is currently in review by QA (Quality assurance). I'll update here once this is ready to be merged.

**Comment by djsmith85** [comment]
This has passed QA and I just merged to master and will be included in the upcoming `2023.10`-release.

**Pull request merged**
