### PR TITLE
[PM-11497] If an org has only one collection, check it by default

### PR DESCRIPTION
**Pull request by szh**
## 🎟️ Tracking

https://github.com/orgs/bitwarden/discussions/10760

## 📔 Objective

When saving a password into an organization, if there's only one collection available to save to, select it by default. This improves UX by decreasing the number of clicks required.

## 📸 Screenshots

image

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by Jingo88** [comment]
This has been approved by QA and merged. Thanks for the contribution!

**Comment by szh** [comment]
Thank you for merging this! Where should I look for the equivalent code in the mobile apps?

**Comment by KatherineInCode** [comment]
Hi! 👋🏻 The place where that would be figured out on iOS is in the [VaultItemCoordinator](https://github.com/bitwarden/ios/blob/main/BitwardenShared/UI/Vault/VaultItem/VaultItemCoordinator.swift#L151), moving into the [AddEditItemProcessor](https://github.com/bitwarden/ios/blob/main/BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift) and its state/view objects.

**Comment by aj-rosado** [comment]
Hello!
For Android, on the `VaultAddEditViewModel`, the method that deals with the org change is the [handleOwnershipTextInputChange](https://github.com/bitwarden/android/blob/083578ec2bc7872438196542666fba98c81030d6/app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt#L845)

[handleCollectionSelect](https://github.com/bitwarden/android/blob/083578ec2bc7872438196542666fba98c81030d6/app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/addedit/VaultAddEditViewModel.kt#L866C17-L866C39) might also be helpful

**Pull request merged**
