### PR TITLE
Remove "Mir" CC brand option

### PR DESCRIPTION
**Pull request by djsmith85**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective
Bitwarden is removing the option to select "Mir" as a credit-card brand in the vault.
This is to ensure Bitwarden clients stay available in all digital storefronts.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by justindbaur — APPROVED** [review]

**Comment by sguryev** [comment]
@djsmith85 Don't you want to remove `RuPay` as well because it may be associated with Russia as well?

**Comment by aptixx** [comment]
@sguryev they won't respond, cause RuPay is fine for them, as well as UnionPay, although China makes a lot of mess with Tibetans, Uyghurs, Taiwanese people, and India actively trades with Russia, and it's payment system is indeed RuPay, with Ru part in it's name. They made Bitwarden a Ukrainian political battlefield, and the support does everything that the Ukrainian users ask them to do, just like trained puppies. Disgrace.

**Comment by ageev** [comment]
That's the reason why I stopped paying for BitWarden. Now they push out Russians. Next will be Jews, or Iranians. At the very end only white people will be allowed to use it.

**Comment by intari** [comment]
Is it possible to pay for Bitwarden using non-Russian Mir cards using existing payment providers?
(All Russian cards(VISA/MC/Mir) will not work anyway without using Russian payment processor)
If answer is "no" - it makes perfect sense to remove this option

**Comment by ClusterM** [comment]
Anyway, how it will help to stop putin? I can't understand.

**Comment by intari** [comment]
> Anyway, how it will help to stop putin? I can't understand.

It will confirm that sanctions are against putin and not against everybody in Russia which will decrease his support by Russians who were pro-putin or neutral.

**Pull request merged**
