### PR TITLE
[PM-8039] Fastmail: Change website default value to empty string.

### PR DESCRIPTION
**Pull request by dixls**
Fastmail API returns and error when passed a null value in forDomain. Empty string is the preferred blank option.

## Type of change

```
- [ X ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

`null` is not allowed in forDomain in Fastmail's API

### CODE REVIEW

**Comment by audrey-jensen** [comment]
Hi @dixls! Thank you for your contribution!

We're in the middle of replacing the forwarders, and this code is deprecated. Good news, though! The new code is already written and the integration PR (#8998) should merge soon!

Could you move your fix to the new forwarder? I think the right spot is [on line 38](https://bitwarden.atlassian.net/browse/PM-8039).

**Review by audrey-jensen — CHANGES_REQUESTED** [review]
Hi @dixls! Thank you for your contribution!

We're in the middle of replacing the forwarders, and this code is deprecated. Good news, though! The new code is already written and the integration PR (#8998) should merge soon!

Could you move your fix to the new forwarder? I think the right spot is [on line 38](https://github.com/bitwarden/clients/blob/386a171c18f4685ee7035dd9986b79366ef1718a/libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts#L38).

**Comment by dixls** [comment]
@audrey-jensen hey thanks, I don't have access to view your jira, I'm not sure what the process is there or if i should, but if it seems warranted, go ahead and grant that access to ybeadenkopf@fastmailteam.com. 

but I can go ahead and make this same change to the new forwarder, it looks like that little bit is mostly the same but I'm not certain.

**Comment by audrey-jensen** [comment]
@dixls - Sorry. that was a paste buffer issue. I've updated the link.

**Comment by dixls** [comment]
Oh I see, I *believe* this issue would be fixed with the change [here](https://github.com/bitwarden/clients/blob/386a171c18f4685ee7035dd9986b79366ef1718a/libs/common/src/tools/generator/username/email-forwarders/forwarder-options.ts#L3), since the default is now a string, but typescript is not my main thing, so let me know if I'm reading this wrong!

**Comment by audrey-jensen** [comment]
I'd like this in the procedural code because the way that we're handling defaults and so on is in flux, and this is fastmail-specific behavior.

There's two spots for that at present.

* ["classic" forwarders](https://github.com/bitwarden/clients/blob/386a171c18f4685ee7035dd9986b79366ef1718a/libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts#L38)
* ["vNext" forwarders](https://github.com/bitwarden/clients/blob/386a171c18f4685ee7035dd9986b79366ef1718a/libs/common/src/tools/generator/username/forwarders/fastmail.ts#L74)

**Comment by dixls** [comment]
I updated this PR with the change in that other spot, but let me know if it makes more sense to close this one and open a PR against the other branch that's in progress.

**Review by audrey-jensen — APPROVED** [review]

**Comment by audrey-jensen** [comment]
Sorry for the delay! For some reason your last push didn't come through my notifier! 😬

This is good to go! Thank you! :D

**Comment by audrey-jensen** [comment]
@dixls - Looks like you need to [sign the CLA with your fastmail account](https://cla-assistant.io/bitwarden/clients?pullRequest=9127) due to 73c0a00.

**Comment by dixls** [comment]
I think I got it now lol, whoops! Thanks so much!

**Comment by audrey-jensen** [comment]
Thanks!

**Pull request merged**
