### PR TITLE
Add workflow to apply needs-qa label

### PR DESCRIPTION
**Pull request by trmartin4**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [X] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

We have a `needs-qa` label that we can apply to our PRs to prevent them from being accidentally merged without QA testing on the feature branch.  The problem we face now is that we have to remember to apply the label on the PR.  This is complicated by the fact that the label only needs to be applied when we're merging into `master` - if there is a long-lived feature branch that is the PR target, testing will occur on the destination branch and should thus _not_ be a blocker for PR merge.

To alleviate this, I've created a workflow that will apply the label when a PR is reviewed and approved.  It will only apply if the target is `master` and it's not a fork (proxy for community PRs).

## Code changes

- **[label-issue-pull-request.yml](https://github.com/bitwarden/clients/pull/4727/files#diff-d6bbcb02c652bcaa86a2da3c08ca015be30a974bc462339fffde8dc1acd334d6):** New workflow to add label to PRs

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by differsthecat — DISMISSED** [review]
Thanks Todd, I think this will be very helpful 🙂

**Comment by differsthecat** [comment]
Interestingly, approving this added the `needs-qa` tag but did not re-run the `Enforce PR labels` action, so it is allowing you to merge it still 🤔

**Comment by trmartin4** [comment]
I have adjusted the job to now be triggered on the creation of the PR.  This should eliminate the need for one job to trigger another.

**Review by differsthecat — APPROVED** [review]
I like this adjustment, it's easy to remove the tag if it is a feature branch being merged, and when it has passed QA. Thanks @trmartin4 !

**Pull request merged**
