### PR TITLE
[PM-8316] Fix account switcher on vault logout timeout

### PR DESCRIPTION
**Pull request by quexten**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8316

## 📔 Objective

Fix account switcher on desktop and browser. The active account on startup can be logged out (for an account with the vault timeout action logout).

On desktop, this PR adds a check on the account switcher init, that checks whether the account is logged out, and if so switches to the next account, so that the account switcher is never in a broken state.

On browser, this happens in the main.background, because otherwise the badge is in an incorrect state before opening the extension after launching the browser.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by JaredSnider-Bitwarden — DISMISSED** [review]

**Comment by quexten** [comment]
@JaredSnider-Bitwarden Updated this with a fix for a minor symptom discovered by QA that would have actually lead to a major defect. I copy pasted the desktop code when the scope was extended to cover browser too. But the desktop code included an early return, that - in browser - lead to init code for the badge and tabbackground/overlay being skipped. Should be fixed now.

**Comment by quexten** [comment]
@JaredSnider-Bitwarden Recording:

https://github.com/user-attachments/assets/94f2d48c-fbd1-479f-80eb-4af344ecf4ff

**Comment by quexten** [comment]
Verifying the actual functionality the PR fixes (switch to next account - in this case "new account") when timing out with login timeout:

https://github.com/user-attachments/assets/f900d43e-1dcc-43a7-88e7-599f60311edb

**Review by JaredSnider-Bitwarden — APPROVED** [review]
LGTM!

**Pull request merged**
