### PR TITLE
PS-1620 Move AccountService.delete to Internal

### PR DESCRIPTION
**Pull request by MGibson1**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Move server sync calls to ApiServices. Corrects dependency flow of AccountService/AccountApiService set.

## Code changes

- **delete-account.component**: use API service for server sync actions
- **jslib-services**:  update deps
- **accountApiService**: call accountService from the api call to sync local caches
- **accountService**: just do the local call stuff in this method. Also extract delete to an internal-only method

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by coroiu — APPROVED** [review]
This was one of my first adventures in service-land thanks for tagging me! Change makes sense. Looking forward to seeing a full refactor of the `AccountService`

**Review by djsmith85 — DISMISSED** [review]
Changes are looking good.

**Comment by MGibson1** [comment]
looking for final review post-qa

**Review by djsmith85 — APPROVED** [review]
Looking good.

**Pull request merged**
