### PR TITLE
[SG-360] Remove the /modules/ folder

### PR DESCRIPTION
**Pull request by addisonbeck**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
https://adr.bitwarden.com/decisions/0011-angular-folder-structure introduced a folder structure that removes the `/modules` folder. This PR relocates everything in `/modules/` to its proper home and does some cleanup on the NgModules inside.

## Code changes
For details, see commits and their descriptions. The changes here can be broken up into a few chunks:

1. `37023a6-e45513c`: These commits relocate everything out of `/modules/` in web without making any changes to names or content (except for imports)
2. `c1b8f81`: Does the same thing but for desktop, which was much more straightforward and easy to do in one commit.
3. `2a71322`: Restructures the `/modules/vault-filter/` code that was in `libs`
4. `73d079c-fe5da92`: Rename files that were in `/modules/` to fit the new structure
5. `1d0ede6`: Modifies the content of the `VaultFiltersModule` to separate the organization view from the individual view.

## Before you submit
```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Comment by addisonbeck** [comment]
For anybody that sees this between now and then:

Oscar and I discussed this a bit on Slack, and the following changes are incoming but not listed on the PR yet:
1. Moving the `VerticalStepperModule` from `/shared/` to `/accounts/trial`
2. Breaking up `/shared/pipes/` and ensuring they are all reused heavily enough to deserve the `shared/` spot.
3. Cherry-picking the comment warning against adding to `SharedModules` from #3222 
4. Moving `PaymentComponent` out of `SharedModule`
6. Moving `TaxInfoComponent` out of `SharedModule`.

The following tech debt items will be created for later:
1. Moving the `VerticalStepperModule` to the component library

**Comment by Hinton** [comment]
@addisonbeck seems like storybook is failing to run. I got the following error:

```
apps/web/src/app/accounts/trial-initiation/trial-initiation.component.spec.ts:20:42 - error TS2307: Cannot find module '../vertical-stepper/vertical-stepper.component' or its corresponding type declarations.
```

**Comment by addisonbeck** [comment]
@Hinton this was an issue with the last merge commit. I amended it to correct a file path that was changed, and storybook builds locally now.

**Review by differsthecat — COMMENTED** [review]
I originally left the vertical stepper out of the trial initiation folder and into it's own with the thought in mind that it could potentially be re-used elsewhere, and there is nothing about it tying it to trial initiation. 

The chances of it being used elsewhere though are low, and moving it out of trial initiation will be an easy change later.

**Review by differsthecat — DISMISSED** [review]

**Review by differsthecat — APPROVED** [review]

**Pull request merged**
