### PR TITLE
[PM-2792] Fix for #5110 (The "Settings" > "Options" page's section headers cannot be translated)

### PR DESCRIPTION
**Pull request by sdimarzo**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fixes https://github.com/bitwarden/clients/issues/5110, making "Options" page's section headers translatable.
## Code changes
- **apps/browser/src/popup/settings/options.component.html** Changed "General" and "Display" text with the correct syntax to pull the translation from ***messages.json***. 
- **apps/browser/src/_locales/en/messages.json** Added "General" and "Display" as default translations.
## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by Jingo88** [comment]
@sdimarzo Thanks for the contribution. It looks great.

**Review by cagonzalezcs — APPROVED** [review]
Looking good 👍

**Comment by cagonzalezcs** [comment]
Thank you for your contribution! I'll be moving this to QA to test your changes, once those are approved we'll merge these changes into the upcoming release candidate.

**Review by Jingo88 — APPROVED** [review]

**Comment by Jingo88** [comment]
failed actions were checked against a temp branched and passed. qa approved. squashed and merged.

**Pull request merged**
