### PR TITLE
[PM-5749] Make cipher decryption faster by replacing promise.all in encrypt.service.implementation

### PR DESCRIPTION
**Pull request by quexten**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Another partial fix for https://github.com/bitwarden/clients/issues/1597

When developing https://github.com/bitwarden/clients/pull/6465 I also considered looking at what is bottlenecking the single threaded "decryption" speed when having large (10k+ cipher) vaults, but did not investigate further at the time. When looking at the unlock process in a profiler, the actual decryption did not play a significant role in the unlock time. Instead, there are many smaller overheads here and there (GC's due to many heap allocations, overhead from async await, and others) that cause the slowness during unlock.

This PR addresses one aspect, but there are other gains left to be had.

One small and simple fix is simply replacing a Promise.all with a for loop. While Promise.all would be faster in an io-bound scenario (HTTP requests, Disk access), it is much slower for this type of CPU-bound task. I have validated this over hundreds of runs over decrypting a 10k+ cipher test vault, and replacing Promise.all with a simple for loop ~~speeds "decryption" of the ciphers up by 70-100% (measured inside the worker)~~ (this was in dev mode), speeds up the decryption by **20-30% in prod builds in chrome**, and **50% in Firefox**, with quite some variance.

```
// these numbers are for dev builds, in prod the difference is still there but not as pronounced
// before (in milliseconds)
{
    "Avg": 268.58,
    "Median": 234,
    "Min": 220,
    "Max": 301,
    "Ciphers Per Second Median": 42854.70085470085
}

// after (in milliseconds)
{
    "Avg": 182.25,
    "Median": 144,
    "Min": 138,
    "Max": 295,
    "Ciphers Per Second Median": 69638.88888888889
}
```

Beware when replicating this result to close the browser console during unlock, and measuring over hundreds of test runs, otherwise the results are fairly noisy.

## Code changes

- **encrypt.service.implementation.ts**: Replace Promise.all with a for loop for performance (and add a comment explaining this)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by MGibson1** [comment]
I don't see the same trends you found. What I see is that for very small arrays of encrypted strings, promise is slower, but for any size decryption larger than 1, the for loop is slower.

(note these units are quite different from your data) 
image

I used [tinybench](https://github.com/tinylibs/tinybench) since more advanced benchmarking software tends to be difficult to run in webpack projects, but I see similar results using benny in our CLI project.

Can you share more about your testing methodology? One possible big difference is that I'm directly testing decryption, but it sounds like you might have measured in our more typical web worker environment.

(I removed `package.json` and `package.lock.json` from this diff)
```
diff --git a/apps/cli/src/program.ts b/apps/cli/src/program.ts
index 64fe209258..8c9ee461ec 100644
--- a/apps/cli/src/program.ts
+++ b/apps/cli/src/program.ts
@@ -99,6 +99,13 @@ export class Program {
       );
       writeLn("", true);
     });
+    
+    program
+      .command("bench [iterations]")
+      .description("Run a benchmark test.")
+      .action(async (iterations) => {
+        this.main.cryptoService.testDecryption(iterations);
+      });
 
     program
       .command("login [email] [password]")
diff --git a/libs/common/src/platform/services/crypto.service.ts b/libs/common/src/platform/services/crypto.service.ts
index 0d0085f1db..001ee11768 100644
--- a/libs/common/src/platform/services/crypto.service.ts
+++ b/libs/common/src/platform/services/crypto.service.ts
@@ -1,5 +1,7 @@
+import * as benny from "benny";
 import * as bigInt from "big-integer";
 import { Observable, firstValueFrom, map } from "rxjs";
+import { Bench } from "tinybench";
 
 import { EncryptedOrganizationKeyData } from "../../admin-console/models/data/encrypted-organization-key.data";
 import { ProfileOrganizationResponse } from "../../admin-console/models/response/profile-organization.response";
@@ -73,6 +75,56 @@ export class CryptoService implements CryptoServiceAbstraction {
     this.activeUserOrgKeys$ = this.activeUserOrgKeysState.state$; // null handled by `derive` function
   }
 
+  async testDecryption(reps: number = 1000, time: number = 1000): Promise<void> {
+    const userKey = await this.getUserKey();
+    const testData = await Promise.all(
+      Array.from({ length: reps }, (e, i) => i).map((x) =>
+        this.encryptService.encrypt(x.toString(), userKey),
+      ),
+    );
+
+    // const bench = new Bench({ time });
+    // bench.add("Promise#all", async () => {
+    //   await this.testPromiseAll(testData, userKey);
+    // });
+    // bench.add("For#loop", async () => {
+    //   await this.testForLoop(testData, userKey);
+    // });
+    // bench.warmup();
+    // await bench.run();
+    // console.table(bench.table());
+
+    benny.suite(
+      "Decryption",
+      benny.add("Promise#all", async () => {
+        await this.testPromiseAll(testData, userKey);
+      }),
+      benny.add("For#loop", async () => {
+        await this.testForLoop(testData, userKey);
+      }),
+      benny.cycle(),
+      benny.complete(),
+    );
+  }
+
+  async getTestData(): Promise<[string, SymmetricCryptoKey]> {
+    const encPriv = await this.stateService.getEncryptedPrivateKey();
+    const userKey = await this.getUserKey();
+    return [encPriv, userKey];
+  }
+
+  async testPromiseAll(testData: EncString[], key: SymmetricCryptoKey): Promise<Uint8Array[]> {
+    return await Promise.all(testData.map((x) => this.encryptService.decryptToBytes(x, key)));
+  }
+
+  async testForLoop(testData: EncString[], key: SymmetricCryptoKey): Promise<Uint8Array[]> {
+    const results = [];
+    for (let i = 0; i < testData.length; i++) {
+      results.push(await this.encryptService.decryptToBytes(testData[i], key));
+    }
+    return results;
+  }
+
   async setUserKey(key: UserKey, userId?: UserId): Promise<void> {
     // TODO: make this non-nullable in signature
     userId ??= (await firstValueFrom(this.accountService.activeAccount$))?.id;
```

**Comment by quexten** [comment]
I'll try to set up some more reproducible tests in a bit, to figure out what's going on. 

Roughly:
The results were admittedly quite noisy between runs, but were consistent for my test runs on both chromium 120 and firefox 122. I measured:

https://github.com/bitwarden/clients/blob/cf470e3ad30c9890aeb7137ba39a47fa5bae3963/libs/common/src/platform/services/cryptography/encrypt.worker.ts#L50

using a vault containing 10.000 ciphers, each of which had 4 encstrings, manually unlocking in the web vault prod build. When taking measurements, I had a loop around `await encryptService.decryptItems(items, key)`, repeating it ~100 times. Afterwards, I had it print mean and median.

The logic behind doing it like this, is that it was the specific scenario I'm testing for (unlock time in the web vault in the browsers engine, using the web-worker).

Using an automated test in the cli seems like a good idea for reproducibility, but again is a different environment (even if still using v8) so might have different results, just by simply scheduling promises differently. I have not dug into either deep enough to be confident on this, but at least black box benchmark should provide sufficient data.

**Comment by quexten** [comment]
Benchmark diff:
```
diff --git a/./clients/libs/common/src/platform/services/cryptography/encrypt.worker.ts b/home/quexten/tmp/clients/libs/common/src/platform/services/cryptography/encrypt.worker.ts
index 047b7a9..a1d8476 100644
--- a/./clients/libs/common/src/platform/services/cryptography/encrypt.worker.ts
+++ b/home/quexten/tmp/clients/libs/common/src/platform/services/cryptography/encrypt.worker.ts
@@ -8,6 +8,7 @@ import { WebCryptoFunctionService } from "../web-crypto-function.service";
 
 import { EncryptServiceImplementation } from "./encrypt.service.implementation";
 import { getClassInitializer } from "./get-class-initializer";
+import { InitializerMetadata } from "../../interfaces/initializer-metadata.interface";
 
 const workerApi: Worker = self as any;
 
@@ -28,6 +29,69 @@ export function init() {
   inited = true;
 }
 
+async function decryptItemsFor<T extends InitializerMetadata>(
+  items: Decryptable<T>[],
+  key: SymmetricCryptoKey,
+): Promise<T[]> {
+  if (items == null || items.length < 1) {
+    return [];
+  }
+
+  // don't use promise.all because this task is not io bound
+  let results = [];
+  for (let i = 0; i < items.length; i++) {
+    results.push(await items[i].decrypt(key));
+  }
+  return results;
+}
+
+async function decryptItemsPromise<T extends InitializerMetadata>(
+  items: Decryptable<T>[],
+  key: SymmetricCryptoKey,
+): Promise<T[]> {
+  if (items == null || items.length < 1) {
+    return [];
+  }
+
+  return await Promise.all(items.map((item) => item.decrypt(key)));
+}
+
+async function runBenchmark(items: Decryptable<any>[], key: SymmetricCryptoKey) {
+  const iterations = 100;
+  console.log("Decrypting " + items.length + " items")
+  console.log("User agent", navigator.userAgent)
+  console.log("Iterations", iterations);
+  
+  var start = new Date().getTime();
+  var end = new Date().getTime();
+
+  var resultTimesFor = [];
+  var resultTimesPromise = [];
+  for (var i = 0; i < iterations; i++) {
+    start = new Date().getTime();
+    var result = await decryptItemsFor(items, key);
+    end = new Date().getTime();
+    resultTimesFor.push(end - start);
+
+    start = new Date().getTime();
+    result = await decryptItemsPromise(items, key);
+    end = new Date().getTime();
+    resultTimesPromise.push(end - start);
+  }
+  console.log("For loop");
+  console.log("Average " + resultTimesFor.reduce((a, b) => a + b, 0) / resultTimesFor.length + "ms");
+  console.log("Median " + resultTimesFor.sort()[Math.floor(resultTimesFor.length / 2)] + "ms");
+  console.log("Min " + resultTimesFor.sort()[0] + "ms");
+  console.log("Max " + resultTimesFor.sort()[resultTimesFor.length - 1] + "ms");
+
+  console.log("Promise all");
+  console.log("Average " + resultTimesPromise.reduce((a, b) => a + b, 0) / resultTimesPromise.length + "ms");
+  console.log("Median " + resultTimesPromise.sort()[Math.floor(resultTimesPromise.length / 2)] + "ms");
+  console.log("Min " + resultTimesPromise.sort()[0] + "ms");
+  console.log("Max " + resultTimesPromise.sort()[resultTimesPromise.length - 1] + "ms");
+}
+
+
 /**
  * Listen for messages and decrypt their contents
  */
@@ -47,6 +111,9 @@ workerApi.addEventListener("message", async (event: { data: string }) => {
     const initializer = getClassInitializer<Decryptable<any>>(jsonItem.initializerKey);
     return initializer(jsonItem);
   });
+
+  await runBenchmark(items, key);
+
   const result = await encryptService.decryptItems(items, key);
 
   workerApi.postMessage({
```


On firefox:
```
Starting decryption using multithreading console-log.service.ts:43:16
Decrypting 10005 items encrypt.worker.ts:61:10
User agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 encrypt.worker.ts:62:10
Iterations 100 encrypt.worker.ts:63:10
For loop encrypt.worker.ts:81:10
Average 798.57ms encrypt.worker.ts:82:10
Median 749ms encrypt.worker.ts:83:10
Min 1016ms encrypt.worker.ts:84:10
Max 957ms encrypt.worker.ts:85:10
Promise all encrypt.worker.ts:87:10
Average 1907.21ms encrypt.worker.ts:88:10
Median 1922ms encrypt.worker.ts:89:10
Min 1532ms encrypt.worker.ts:90:10
Max 3077ms encrypt.worker.ts:91:10
Finished search indexing console-log.service.ts:43:16
```

On chromium:
```
Decrypting 10005 items
encrypt.worker.ts:62 User agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
encrypt.worker.ts:63 Iterations 100
encrypt.worker.ts:81 For loop
encrypt.worker.ts:82 Average 175.8ms
encrypt.worker.ts:83 Median 149ms
encrypt.worker.ts:84 Min 143ms
encrypt.worker.ts:85 Max 2336ms
encrypt.worker.ts:87 Promise all
encrypt.worker.ts:88 Average 263.03ms
encrypt.worker.ts:89 Median 240ms
encrypt.worker.ts:90 Min 227ms
encrypt.worker.ts:91 Max 402ms
```

Built with: `npm run dist:oss:selfhost`
Again, browser console is closed while logging in. It might take a few minutes (on firefox atleast) to complete.

Test vault export:

[bitwarden_export_20240124071522.csv](https://github.com/bitwarden/clients/files/14033890/bitwarden_export_20240124071522.csv)

**Comment by quexten** [comment]
The above logs were on Linux (Fedora 39), just to make sure this isn't just a weird scheduler issue on Linux, here is a log from a Windows system:
```
Starting decryption using multithreading
encrypt.worker.ts:61 Decrypting 10005 items
encrypt.worker.ts:62 User agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
encrypt.worker.ts:63 Iterations 100
encrypt.worker.ts:81 For loop
encrypt.worker.ts:82 Average 116.79ms
encrypt.worker.ts:83 Median 90ms
encrypt.worker.ts:84 Min 100ms
encrypt.worker.ts:85 Max 99ms
encrypt.worker.ts:87 Promise all
encrypt.worker.ts:88 Average 165.97ms
encrypt.worker.ts:89 Median 172ms
encrypt.worker.ts:90 Min 132ms
encrypt.worker.ts:91 Max 232ms
console-log.service.ts:43 Finished search indexing
```

The results are roughly the same.

**Comment by quexten** [comment]
To be honest, looking at the tinybench code, I think it's not so much about the decryption itself running faster, but instead the `item.decrypt(key)` promises completing faster. Whether that's due to them being scheduled more densely, or something much lower level (data remaining in the L3 cache of the CPU, and not getting kicked out by other promises for other ciphers), I do not know.

Changing the tinybench benchmark code to decrypt entire ciphers might provide inside here.

**Comment by MGibson1** [comment]
decryption of entire items, and actually even just `decrypt` method on an `EncString` is quite a bit more complicated than what I was doing, so perhaps it has something to do with all the retrieval that's done repeatedly being more efficient serialized rather than parallel.

**Review by MGibson1 — APPROVED** [review]
I've repeated these results when testing through the web worker. Thank you for your investigations here and you help with my reproduction efforts, this couldn't have been easy to find.

**Pull request merged**
