### PR TITLE
[PS-2367] CLI pkg ref for argon2 lib

### PR DESCRIPTION
**Pull request by kspearrin**
https://bitwarden.atlassian.net/browse/DEVOPS-1182

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix reference to argon2 lib for CLI packaging.

## Code changes

- **build-cli.yml:** Change to os matrix for building cli and artifacts.
- **apps/cli/package.json:** Add argon2 `node_modules` to assets.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by kspearrin** [comment]
@Hinton I made the change, but it doesn't appear to work in my tests.

**Comment by Hinton** [comment]
@kspearrin that's odd. I did test it locally but I forgot to move the executable and after moving I get the same error. According to the docs it should pick it up https://github.com/vercel/pkg#native-addons.

We do still need the argon2 in the `package.json` as a dependency though for the npm installs to pick it up.

**Comment by kspearrin** [comment]
Should be good to go now @Hinton. @bitwarden/dept-devops  is exploring what we need to do to suppose the argon2.node binary on different OSs during the CI build.

**Review by Hinton — COMMENTED** [review]
Package changes looks good. I'll let devops review the workflow changes.

**Review by joseph-flinn — APPROVED** [review]

**Pull request merged**
