### PR TITLE
[PM-5438] Force biometric with touch id

### LINKED ISSUE #2592: Bitwarden desktop app 1.30.0 allows vault unlock with profile password (not master password) when Touch ID is enabled on macOS 12.1
### Steps To Reproduce

1. Have Touch ID enabled on macOS 12.1, along with a profile password. Have Bitwarden desktop app v1.30.0 installed.
2. In the Bitwarden desktop app, enable "Unlock with Touch ID" in Bitwarden -> Preferences -> Security if it is not enabled already.
2. Click Bitwarden -> "Lock Now", or Cmd + L
3. Click "Unlock with Touch ID"
4. In the Touch ID popup, click "Use Password..."
5. You can now type in your profile password (as compared to the Bitwarden master password) and click "OK"
6. The Bitwarden vault should now be unlocked.

### Expected Result

I expect that Bitwarden would require the user to still use the master password, similar to what is done with 1password.

As it is, this allows for a second password to be used to unlock the password vault, and in my opinion, makes the whole app less safe.

### Actual Result

The actual result was that my Bitwarden vault was opened with just my profile password, rather than my master password.

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

macOS

### Operating System Version

12.1

### Installation method
I confirmed this via the Mac App Store, as well as the download from Bitwarden.com.

### Build Version

1.30.0

### PR DESCRIPTION
**Pull request by danielr18**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

1. Fix #2592 by requiring user's master password as fallback instead of profile password, when using TouchID.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by danielleflinn** [comment]
@danielr18 Thank you for your contribution. Please attach a screen recording of the updated experience. Thanks!

**Comment by danielr18** [comment]
@danielleflinn Here's the video

Scenarios in order:
1 - Success touch id
2 - Failed touch id
3 - Clicked fallback option to enter master password
 
https://github.com/bitwarden/clients/assets/9046616/da51ef30-2ba7-45c1-8e57-92299a9f8eff

**Comment by danielleflinn** [comment]
Thank you @danielr18 this is very helpful! A few pieces of feedback from our Product and Design team:

- We have some users who do not have master passwords that may use this feature. With this in mind, can you remove the the Primary button and just offer users the option to "Cancel"? 
- Please update the copy in the modal to: "Touch ID or cancel to use another method"
- Can you confirm the logic for how many attempts a user is given before Touch ID is disabled?

**Comment by danielr18** [comment]
Hi @MGibson1, I was wondering if the `OsBiometricService.authenticateBiometric` method should be similar to the Safari extension, where an item is read from the keychain. It doesn't seem like the interface supports that, because it needs the `userId`.

That would allow the app to disable Touch ID if the fingerprints are changed for example.

**Comment by MGibson1** [comment]
@danielr18, it does have a userId, just in the form of the `storageKey`, which is [built from the userId and some constant key data](https://github.com/bitwarden/clients/blob/main/libs/common/src/platform/services/state.service.ts#L731-L743), just like in safari.

I believe my ideal would be for the macOS implementation to mirror the windows one more closely, where we push triggering of biometric prompts and validations downwards into rust. In which case, `authenticateBiometric` isn't the method, it's something akin to `getBiometricSecret`. The rust module would then determine whether or not to prompt, whether that prompt was sufficient, and whether the data stored in the keychain represents the full key or needs to be further decrypted.

On a broader implementation level, I haven't done the work needed to really research calling macOS APIs from rust, but are you familiar with a way that doesn't involve a swift package that is then called? It would be preferable to keep things within a rust binary, even if it's a loose wrapper around objc.

**Comment by danielr18** [comment]
@MGibson1, thanks for the input. I'll review the existing Windows implementation for consistency.

Regarding the Touch ID integration, I've found an existing Rust wrapper, [tid-rs](https://github.com/lightsing/tid-rs), which interfaces with Objective-C for Touch ID. We can develop a similar wrapper for our needs, particularly for keychain interactions, which should keep us within the Rust ecosystem.

I'm keen to hear any other suggestions you might have to help move this PR forward. If there are specific areas you think need adjusting or additional features to consider, please let me know. I'm ready to make further modifications as needed.

**Comment by MGibson1** [comment]
Daniel, I'm sorry I haven't had a time to look too closely into the specifics so no comments on that front, yet, but we did do a little research into biometrics from native libraries a little more.

It appears there's no good way to link to an exposed C library, so objective C is definitely the way to go -- no swift, since that would involve shipping a runtime. I think tid-rs has the right of it, but I think we'd want to re-implement or fork so that we can maintain.

As for key storage, we should update to honor biometric-only and revoke on biometric change -- just like the ios application This does mean that existing keys need to be migrated to activate these flags on the key, though.

**Comment by micahblut** [comment]
HI @danielr18 , thank you for the contribution. We're about to embark in replacing the stack we use for biometrics on macOS, and as a result, I will need to close this PR. However, we will make sure to include the change, disallowing device password as a substitute for toughID, in the changes we implement.

**Pull request closed without merging**
