### PR TITLE
Conditionally display new copy under subscriptions table [AC-1657]

### PR DESCRIPTION
**Pull request by amorask-bitwarden**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

[JIRA Ticket](https://bitwarden.atlassian.net/browse/AC-1657)
The purpose of this PR is to consume newly added discount information from the Subscription API endpoints and use the existence of discounts to conditionally display new copy under the Subscriptions tables.

## Code changes

- **messages.json:** Add new translation entries used to build up the copy being added under the Subscriptions tables.

- **subscription.response.ts:** Add a new `BillingCustomerDiscount` class. Add it as a field to the `SubscriptionResponse`. Populate the discount using the `Discount` response property.

- **organization-subscription.response.ts:** Add the `BillingCustomerDiscount` as a field to the `OrganizationSubscriptionResponse` class. Populate the discount using the `Discount` response property.

- **user-subscription.component.ts:** Add a `discount` getter to retrieve the applied discount.

- **user-subscription.component.html:** Use the `discount` getter to check for the existence of a discount. If one exists, add another table row to the subscriptions table with the new copy.

- **organization-subscription-cloud.component.ts:** Add a `discount` getter to retrieve the applied discount.

- **organization-subscription-cloud.component.html:** Use the `discount` getter to check for the existence of a discount. If one exists, add another table row to the subscriptions table with the new copy.

Discounts being used are added to the API response as part of this PR: https://github.com/bitwarden/server/pull/3278

## Screenshots

Premium User:
image

Organization User:
image

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Review by djsmith85 — COMMENTED** [review]
@amorask-bitwarden: We should aim to not break-up sentences, as it makes it hard for translators to properly translate. They are unaware of the context and possibly the existence of the other sentence parts.

Please have a look at @shane-melton's approach with introducing a bit-i18n-component https://github.com/bitwarden/clients/pull/6302 and how it's used with https://github.com/bitwarden/clients/pull/6333

**Comment by amorask-bitwarden** [comment]
> @amorask-bitwarden: We should aim to not break-up sentences, as it makes it hard for translators to properly translate. They are unaware of the context and possibly the existence of the other sentence parts.
> 
> Please have a look at @shane-melton's approach with introducing a bit-i18n-component #6302 and how it's used with #6333

@djsmith85 Thanks! This is exactly what I was looking for.

**Review by cturnbull-bitwarden — APPROVED** [review]
👍

**Comment by amorask-bitwarden** [comment]
> @amorask-bitwarden: We should aim to not break-up sentences, as it makes it hard for translators to properly translate. They are unaware of the context and possibly the existence of the other sentence parts.
> 
> Please have a look at @shane-melton's approach with introducing a bit-i18n-component #6302 and how it's used with #6333

@djsmith85 For the sake of not blocking a Product feature, we're going to move ahead with this in the current state, but I've opened a tech debt ticket here: https://bitwarden.atlassian.net/browse/PM-4106 that I will try to get slated for the next sprint hopefully after this new component is merged.

**Review by djsmith85 — APPROVED** [review]
I'm okay with the proposed flow. Merging this now and following up with https://bitwarden.atlassian.net/browse/PM-4106.

**Pull request merged**
