### PR TITLE
[PM-3730] Master Password Re-prompt Enabled Items Invoke Popup Window Automatically When Autofill on Page Load is Enabled

### PR DESCRIPTION
**Pull request by cagonzalezcs**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When a vault item has master password re-prompt enabled, it is a jarring and intrusive experience to have the vault item attempt to autofill on page load. As a result, we are incorporating the default behavior where a vault item cannot be autofilled on load if it has a master password re-prompt setting enabled.

We're also ensuring that we disable this setting when a user is updating their vault item in the popup. If a user sets the vault item to have a master password re-prompt, we disable the dropdown for autofill on load and set the value to a "off" state. If the user unchecks the master password re-prompt setting, we set the autofill on load value to the default setting. In both of these instances, we are informing the user that a change has happened to their autofill on page load value using a toast message.

## Code changes

- **apps/browser/src/_locales/en/messages.json:** Added translations for toast message provided to users upon change of the master password reprompt setting.
- **apps/browser/src/autofill/services/autofill.service.ts:** Adds a check to identify the a cipher has reprompt in place while triggering the autofill `fromCommand`. That effectively checks if we are triggering autofill on page load with a cipher that has reprompt enabled. If so, we exit early.
- **apps/browser/src/vault/popup/components/vault/add-edit.component.html:** Adds a `disable` directive to the autofill on load setting that is set when the `reprompt` member property is enabled. This ensures users are not able to modify the autofill on load setting.
- **apps/browser/src/vault/popup/components/vault/add-edit.component.ts:** Adds a toast message to users as they toggle on/off the master password reprompt value. Set up within this component to ensure that the toast message only appears within the browser extension, as the setting for autofill on page load is not present in other client contexts.
- **libs/angular/src/vault/components/add-edit.component.ts:** Adds logic to conditionally enable/disable autofill on load when users are attempting to set a master password reprompt value on a vault item. 

## Screenshots

https://github.com/bitwarden/clients/assets/16629865/c417ceb3-843f-40f5-b001-b124f1a69cf3

https://github.com/bitwarden/clients/assets/16629865/faf76c68-e1c0-471a-a074-c09da0cc9488

### CODE REVIEW

**Comment by cagonzalezcs** [comment]
> These code changes look good; should there be some kind of indication to the user that the autofill on page load setting has changed when they check this box?

Hm, yeah I think it might be a good idea to incorporate. Let me see if I can add a toast message that informs the user.

**Review by differsthecat — DISMISSED** [review]
Thanks @cagonzalezcs , this looks good for Vault!

**Comment by danielleflinn** [comment]
@cagonzalezcs Suggested copy updates below:

`Items with master password re-prompt cannot be auto-filled on page load. Auto-fill on page load turned off.
`

Can we also add help text to the "auto-fill on page load" field? That way if the user returns to the item in the future they are reminded why the settings is disabled. I'd recommend the following:

`Turn off master password re-prompt to edit this field`

**Comment by cagonzalezcs** [comment]
@danielleflinn 

Sure, I've gone ahead and added the requested items in the following manner:

https://github.com/bitwarden/clients/assets/16629865/1bcb3a2c-94c0-4d3b-abbb-2a49248e545e

**Comment by danielleflinn** [comment]
Thanks @cagonzalezcs looks great!

**Review by jprusik — APPROVED** [review]
Code makes sense and LGTM.

Do we need to do any settings migrations for cases where users already have both page load autofill and reprompt on?

**Comment by cagonzalezcs** [comment]
@jprusik 

We don't need to do that :) 

I tackled this from the perspective of mitigating the behavior at the point where we are attempting to trigger autofill, rather than within the SettingsService or any other place where persistent data would be a concern. Effectively, everything implemented is cosmetic in nature, and even if a user has "Autofill On Load" present on a vault, with a master password reprompt, they will still not see the popup appear on load.

The rest is just UX changes to ensure users know why the master password reprompt didn't occur on load.

**Review by differsthecat — APPROVED** [review]
New changes look good!

**Review by Jingo88 — APPROVED** [review]

**Pull request merged**
