### PR TITLE
[PS-1181] Desktop: Accessibility - ARIA/structure fixes

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Currently, there are a few shortcomings and bugs in some of the left-hand navigation when it comes to screen reader support:

- in "My Vault":
    - the expand/collapse toggles are only announced as "Toggle Collapse", providing no context about what they're actually expanding/collapsing
    - "ALL VAULTS" does not announce whether it's pressed or not pressed
    - "TYPES" expand/collapse toggle has broken `aria-expanded` (has literal `!isCollapsed` value in the rendered markup, rather than `true`/`false`)
    - all the "TYPES" filter buttons have an incorrect `aria-pressed` that is always false (as it uses an old variable name)
-  in "Send":
    - "All Sends" does not announce whether it's pressed or not pressed
- invalid structure on some of the buttons, where there's an `<h2>` nested inside a `<button>`

This PR fixes the invalid structures, corrects the broken `aria-expanded` on "TYPES", corrects the `aria-pressed` on "ALL VAULTS" and "All Sends", wraps the expand/collapse buttons around their adjacent static text to provide more context and removes the unnecessary `appA11yTitle`, and for the expand/collapse controls that have a following button (where the text can't be wrapped inside the expand/collapse control) it expands the existing `appA11yTitle` to not just announced "Toggle Collapse" but to provide the context of what it is as part of it.

## Code changes

- **apps/desktop/src/app/modules/vault-filter/components/collection-filter.component.html**: fix `<button>`/`<h2>` nesting, remove `appA11yTitle`, wrap expand/collapse control around adjacent text, expand existing `appA11yTitle` with more context where needed
- **apps/desktop/src/app/modules/vault-filter/components/folder-filter.component.html**:  fix `<button>`/`<h2>` nesting,  expand existing `appA11yTitle` with more context where needed
- **apps/desktop/src/app/modules/vault-filter/components/organization-filter.component.html**: fix `<button>`/`<h2>` nesting,  expand existing `appA11yTitle` with more context where needed
- **apps/desktop/src/app/modules/vault-filter/components/type-filter.component.html**: fix broken `aria-expanded` on "TYPES", fix `<button>`/`<h2>` nesting, fix the broken `aria-pressed` that used the wrong variable name (`selectedType` vs `cipherType`)
- **apps/desktop/src/app/send/send.component.html**: fix broken `aria-pressed` (presumably it wasn't returning a real `true`/`false` return value? not sure why it wasn't working before, but it is now in any case)
- **apps/desktop/src/scss/left-nav.scss**: tweak styles to account for the different nesting of `<button>`/`<h2>` that was corrected

## Screenshots

Before/after video recording, using NVDA screen reader:

https://user-images.githubusercontent.com/895831/168503616-ca701a4e-41a3-49b3-8e39-95122023065e.mp4

- 0:00 - 1:00: current state of the native app; note how the collapse toggles lack any context, the "ALL VAULTS" doesn't announce its state, "TYPES" expand/collapse always announces as expanded even when it isn't (and doesn't announce any change dynamically), and the "All Sends" doesn't announce its state. (only later realised forgot to also record the issue with the "TYPES" always announcing as "not pressed" even when they were)
- 1:00 - 2:23: after the PR, all the above issues are tweaked. Note the expand/collapse controls now announce what they actually expand/collapse (either by just having their adjacent text now part of the button, e.g. "Types, collapsed" or, when they're a two-part expand/collapse with adjacent button, replicating the text of their adjacent button in their `aria-label`)

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by patrickhlauke** [comment]
not to hassle, but as I'm worried about too much divergence from main branch ... any chance this could be reviewed soon @djsmith85 ?

**Comment by djsmith85** [comment]
@patrickhlauke I know this is primarily for the desktop, but as it involves our newer filter components, would you mind also ensuring we have the same behaviour across web and desktop. I don't think browser is affected as filtering is implemented differently there.

**Comment by patrickhlauke** [comment]
@djsmith85 I had a quick look on the web version (admittedly, I never use the actual web interface itself). The web version is slightly different to this under the hood, but has similar (though not quite the same) problems. I can have a look at that next as a separate issue/PR - don't think it would make sense to cram this into this PR here

**Review by differsthecat — APPROVED** [review]
This looks good @patrickhlauke , thank you!

**Comment by patrickhlauke** [comment]
thanks @differsthecat

**Pull request merged**
