### PR TITLE
[PM-10730] Override FireFox extension styles for text alignment

### PR DESCRIPTION
**Pull request by nick-livefront**
## 🎟️ Tracking

[PM-10730](https://bitwarden.atlassian.net/browse/PM-10730)

## 📔 Objective

This one is probably worth discussing as it is a global change.

#### Issue

FireFox applies default styles to extensions, one of which is `text-align: start`. This causes some elements to not inherit the `text-align` property from their parent, as they would in other browser implementations.

You can see the conflicting styles [here](https://hg.mozilla.org/mozilla-central/file/tip/browser/components/extensions/extension.css#l36) and an explanation of the entire stylesheet [here](https://hg.mozilla.org/mozilla-central/file/tip/browser/components/extensions/extension.css#l8).

#### Fix

~~Rather than playing wack-a-mole with each implementation in the bug ticket, and any other future bug tickets for the same (like [PM-8626](https://bitwarden.atlassian.net/browse/PM-8626)). I applied a global style for the extension that will override the FF styles and force inheritance as the default behavior for the `text-align` property.~~
Edit: See Shane's comment below: https://github.com/bitwarden/clients/pull/10528#issuecomment-2291810631

The comment within the file also states that these styles will be going way for MV3. [PM-8317](https://bitwarden.atlassian.net/browse/PM-8317) is out there to do this work in the future.

Of course an option is to find each conflicting implementation and add `tw-text-center` but that isn't as future proof. I'm happy to do that, but wanted to start here first!

## 📸 Screenshots

|Before|After|
|-|-|
|Screenshot 2024-08-15 at 11 44 47 AM|Screenshot 2024-08-15 at 11 44 22 AM|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-10730]: https://bitwarden.atlassian.net/browse/PM-10730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PM-8626]: https://bitwarden.atlassian.net/browse/PM-8626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PM-8317]: https://bitwarden.atlassian.net/browse/PM-8317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nick-livefront** [comment]
@shane-melton @Jingo88 There doesn't appear to be code owners, feel free to add who you see fit!

**Comment by shane-melton** [comment]
Nice find on this! After looking into some more myself, I think we be able to just set `browser_styles: false` for the `sidebar_action` in our `manifest.json` and,[ according to the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles), this will prevent extra style sheet from being applied. (this seemed to work as expected based on some quick testing of my own)

It already [defaults to `false`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action) for the popup (`action`), it seems that only `sidebar_action` [is different](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) and defaults to `true`. 

I think this has the benefit of avoiding manually overriding the styles and having to track why its there (granted, your comment is very clear). It also moves us one small step closer to future MV3 defaults.

**Comment by nick-livefront** [comment]
> Nice find on this! After looking into some more myself, I think we be able to just set `browser_styles: false` for the `sidebar_action` in our `manifest.json` and,[ according to the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles), this will prevent extra style sheet from being applied. (this seemed to work as expected based on some quick testing of my own)

@shane-melton Nice find! I remember reading through that but I have no idea why I ruled it out in my head. Either way, tested and functions as we'd expect! 👏

**Review by justindbaur — APPROVED** [review]

**Review by Jingo88 — APPROVED** [review]

**Comment by nick-livefront** [comment]
QA Approval given on ticket 🥳

**Pull request merged**
