### PR TITLE
SM-904: Remove SecretsManagerBeta (Phase 2)

### PR DESCRIPTION
**Pull request by coltonhurst**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Remove the concept of SecretsManagerBeta from the clients repository.

This includes the SM Beta expiring banner that was added / edited in these PR's:
- https://github.com/bitwarden/clients/pull/5719
- https://github.com/bitwarden/clients/pull/5877
- https://github.com/bitwarden/clients/pull/6054

## Code changes

- **organization-subscription-cloud.component.html** & **organization-subscription-cloud.component.ts**: Remove the `bit-callout` and the SM Beta row on the billing / subscription tab
- **messages.json**: Remove the following keys: `secretsManagerBeta`, `secretsManagerSubscriptionDesc`, `secretsManagerEnable`, `smBetaEndedDesc`, `betaEnding`
- **organization-subscription.response.ts**: Remove `secretsManagerBeta` from the org subscription response model

## Screenshots

pic-without-sm-beta-expiring-banner

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by coltonhurst** [comment]
Added the "hold" label. This PR is ready for review but needs to wait until https://github.com/bitwarden/server/pull/3451 is merged and deployed. This can then follow in the subsequent release.

**Review by eliykat — DISMISSED** [review]

**Review by Thomas-Avery — APPROVED** [review]
Looks good, let's make sure to not merge it in prior to server release as mentioned.

**Review by cturnbull-bitwarden — APPROVED** [review]

**Comment by coltonhurst** [comment]
> Added the `hold` label. This PR is ready for review but needs to wait until [bitwarden/server#3451](https://github.com/bitwarden/server/pull/3451) is merged and deployed. This can then follow in the subsequent release.

[SM-1010](https://github.com/bitwarden/server/pull/3451) has been merged and released. Removing the hold label.

**Review by eliykat — APPROVED** [review]

**Review by Thomas-Avery — APPROVED** [review]
LGTM

**Review by cturnbull-bitwarden — APPROVED** [review]

**Pull request merged**
