### PR TITLE
[PM-4773] Google Passkey workarounds

### LINKED ISSUE #6764: Passkey not found
### Steps To Reproduce

1. Go to 'google.com'
2. Create and store a passkey in Bitwarden
3. Close the browser
4. Start the browser and go to 'google.com' and try to login
 with a passkey

### Expected Result

Passkey pops up in the plugin window

### Actual Result

Passkey is not found

### Screenshots or Videos

_No response_

### Additional Context

The passkey is visible in the vault.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Microsoft Edge

### Browser Version

118.0.2088.76

### Build Version

2013.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by limisk**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fixes #6764

## Code changes

When a WebAuthn request includes allowCredentials, Bitwarden currently does not search for credentials by relying party. This causes issues if allowCredentials does not contain the user's passkey. This is the case with Google, which does not send credentials with the transport "internal" on Windows.

However, there is a problem: Doing this would [violate the spec](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-allowcredentials).
> If not [empty](https://infra.spec.whatwg.org/#list-empty), the client MUST return an error if none of the listed credentials can be used.

Windows Hello seems to violate this part of the spec too.

An alternative to fix Google sign in is to set the transport to "usb" or something like that, which causes Google to send all credentials. That would also violate the spec, though :(

### CODE REVIEW

**Comment by limisk** [comment]
It also seems to work when using both internal and usb, which might be better?

**Comment by limisk** [comment]
One thing to investigate is why, according to some people, Windows Hello works, because it probably uses "internal" too (I don't know though).

**Comment by trmartin4** [comment]
@limisk, after discussing with Google, we would like to solve this with a temporary inclusion of the `usb` transport along with `internal`, preferably when just the `google.com` relying party is supplied in order to limit the scope of the workaround.  This will be temporary, as Google has assured us that they are fixing this more permanently on their end.

With that in mind, and in respect for the effort you've taken to propose a resolution to the problem, I wanted to offer the opportunity for you to revise your PR to meet these new requirements.  This should be reverting back to the approach taken in https://github.com/bitwarden/clients/pull/6847/commits/dd82606b658edbdf7e5d6f3ab67fc91456f0a2bb.  Would you be willing to make this change and open the PR for review?

**Comment by gbubemismith** [comment]
@limisk, thank you for your contribution! Your efforts are greatly appreciated. Could you kindly move this PR to the `Ready for Review` stage when you're comfortable with it? This would allow us to proceed with the next steps.

**Comment by gbubemismith** [comment]
@limisk, your contribution has successfully passed QA and will be included in our upcoming release. Thanks once again for helping out 🚀

**Pull request merged**
