### PR TITLE
[PM-11628] Fix set password when there is no key

### PR DESCRIPTION
**Pull request by Timshel**
## 📔 Objective

Fix set pasword form when no keys previously existed.

Since [userPublicKey$](https://github.com/bitwarden/clients/blob/77e03aee47071f7a4d41361c2be91012a639c7ea/libs/common/src/platform/services/crypto.service.ts#L942) derive the key from the private key it will fail when there is no private key.

Edit: It could make sense to directly call `derivePublicKey(UserPrivateKey)` instead of relying twice on `firstValueFrom`, but since it's `private` at the moment decided for the simplest fix.

### CODE REVIEW

**Comment by Timshel** [comment]
Hey anything I can/should do ?

**Comment by djsmith85** [comment]
> Hey anything I can/should do ?

@Timshel Other than staying an awesome member of the Bitwarden community, there's currently nothing to do from your side. @quexten has created a copy of your changes to execute all the build pipelines and as long as @bitwarden/team-auth-dev doesn't have any feedback for you, this will likely get reviewed and moved over to QA for testing.

Thank you for your contribution!

**Comment by quexten** [comment]
Hi @Timshel, apologies for not getting back earlier on this one. Thank you for the swift fix for this issue! It did fix the issue in internal testing. However, as you pointed out this really should be fixed in the cryptoservice. The documentation of cryptoservice's abstract methods was out of sync with what they actually implemented. So we've decided to fix this in cryptoservice directly: https://github.com/bitwarden/clients/pull/10882

This has been merged to main and still needs QA testing, but I do think it supersedes this PR. I will update this PR once the QA testing is done.

Again, thank you for the contribution!

**Comment by Timshel** [comment]
With the merge I believe this become unnecessary, so I will close :).

On a different subject, and probably not the best place to ask ^^ but since it's slightly related; I wrote some Playwright integration tests against `Vaulwarden`.

A good chunk of the tests themselves should be compatible against Bitwarden web client. If there is any interest they can be found [here](https://github.com/Timshel/vaultwarden/tree/main/playwright) :)

**Pull request closed without merging**
