### PR TITLE
[EC-1028] [Design feedback] There is no way to close the multi-select with the keyboard when it is in a modal

### PR DESCRIPTION
**Pull request by coroiu**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

`Enter` key should close dropdown according to handover documents.

## Screenshots

:shrug:

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by danielleflinn** [comment]
@coroiu There should be a way for a user to cancel selecting items from the dropdown without having to use a mouse. 
Perhaps  the "Esc" key could close the dropdown without submitting selected items?

**Comment by coroiu** [comment]
@danielleflinn Oh right 🤦‍♂️ I think I looked too much at the "Desired behavior" section in Jira! I'll fix, thanks!

**Comment by coroiu** [comment]
@danielleflinn I've reopened this issue and implemented the following logic, please let me know if you think I should modify remove anything!

- If dropdown is open, `Enter` closes the dropdown and adds all the selected items to the list
- If dropdown is closed, `Enter` submits the form

- If dropdown is open, `Escape` closes the dropdown and does not add any items to the list (basically cancel)
- If dropdown is closed, `Escape` closes the modal like specified by the aria role=dialog rules

**Review by danielleflinn — APPROVED** [review]
This looks great! Thanks @coroiu

**Review by vincentsalucci — APPROVED** [review]

**Pull request merged**
