### PR TITLE
[PS-1030] Desktop: suppress `user-select` for most interface elements

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

This is potentially controversial, but for a native-like experience, it would make sense to suppress user selection/highlighting for most of the interface (with the exception of text/content that a user may wish to actually select and copy).

Currently, most of the interface is selectable. A few examples:

login screen with most content selected and highlighted

lock screen login with all content selected and highlighted

main initial app window, with 'My Vault', 'Sends', and the bitwarden logo selected and highlighted

generator popup, with most content selected and highlighted

While this makes sense for a website, it does feel slightly unpolished for an app. This PR rather brutally (and admittedly a bit clumsily) suppresses `user-select` for most interface text/components, leaving only things like the actual bits of data (when viewing a cipher, for instance) as selectable.

I understand this will need some further discussions with design/UI team. Take it as a suggestion though. However, if accepted, I'll also propose a matching change for the browser extension's popup.

## Code changes

- **/apps/desktop/src/scss/misc.scss:** added `user-select:none` targeting a series of (generic, all the way to very specific) selectors

## Screenshots

Examples after this PR:

lock screen login, with only the typed-in master password highlighted

item/cipher view, showing only the data parts selected and highlighted - labels, headings, etc are left unselected

## Testing requirements

- select using either the mouse, or just hitting Ctrl+A, to see all the content that is and isn't selected/highlighted

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

Linting appears to be broken at the moment? running `npm run lint` just errors out ` Missing script: "lint"`. I do see workflow/build errors following the push here, but can't work out what the actual problems are since I can't lint locally

### CODE REVIEW

**Review by danielleflinn — APPROVED** [review]
Design approves this change. Thanks @patrickhlauke and @djsmith85

**Comment by patrickhlauke** [comment]
thanks @danielleflinn

**Comment by patrickhlauke** [comment]
sorry, pushed another commit as there was a cleaner way to handle the `.box-footer`. It doesn't change the design/look, just a more robust set of CSS selectors

**Review by djsmith85 — APPROVED** [review]
@patrickhlauke This is looking good. Thank you again for your contributions

**Pull request merged**
