### PR TITLE
[EC-417] Extracting the app name from the Android user item on CSV import

### PR DESCRIPTION
**Pull request by r-tome**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Currently if a user has any Android items on their Chrome passwords list and they export it to CSV this results in these items appearing with the name “--” on the Bitwarden vault items list.

These changes will fill out the item name with the app name from the username value.

## Code changes

- **libs/common/spec/importers/chromeCsvImporter.spec.ts:** ChromeCsvImporter unit tests using test data
- **libs/common/spec/importers/testData/chromeCsv/androidData.csv.ts:** Android CSV android test data
- **libs/common/spec/importers/testData/chromeCsv/simplePasswordData.csv.ts:** Simple CSV chrome test data
- **libs/common/src/importers/chromeCsvImporter.ts:** Added a RegEx check to get the app name from the Android format in case the "name" value is empty on the CSV.

## Screenshots

Currently:
image

Solution:
image

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Review by jlf0dev — COMMENTED** [review]
Nice catch! It looks good to me but can you take the time while you're here to add some tests? 

([Obligatory disclaimer about regex](https://regexlicensing.org/))

**Comment by eliykat** [comment]
Just want to +1 the request for unit tests, our importers are pretty well tested (which we want to maintain), and regex's are the perfect candidate for unit tests.

**Comment by r-tome** [comment]
@jlf0dev I see how RegEx can be painful but how else could we do this?
I'll be sure to add unit tests very soon!

**Comment by jlf0dev** [comment]
> @jlf0dev I see how RegEx can be painful but how else could we do this? I'll be sure to add unit tests very soon!

No way I can think of, it's necessary sometimes

**Review by jlf0dev — APPROVED** [review]
Nice!

**Pull request merged**
