### PR TITLE
[AC-1084] Don't copy hidden spaces when selecting password

### PR DESCRIPTION
**Pull request by eliykat**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix the following bug: When selecting and copying a password displayed using the `ColorPasswordComponent`, the copied selection included hidden whitespace.

Thanks to @coroiu for this fix, I'm just doing the Jira/Github admin.

## Code changes

* use `span` elements instead of `div`, to avoid invisible whitespace
* move `tw-inline-flex` to the "count" display only, it's not required for the normal display and interferes with Chrome

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by coroiu — DISMISSED** [review]
Feels weird to approve my own changes but 🤷 😄

**Comment by eliykat** [comment]
I've approved them by opening the PR ;)

**Review by eliykat — COMMENTED** [review]
I opened the PR so I can only comment, not approve. But this change looks good to me - I didn't know of that option! Much better than trying to manage it ourselves in how the template is formatted.

**Review by coroiu — APPROVED** [review]
oh yeah, forgot to approve 😅

**Pull request merged**
