### PR TITLE
[PS-1754] Update search cancel button to be visible in all themes

### PR DESCRIPTION
**Pull request by scottmondo**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Ensure search clear/cancel button is be visible in all themes

## Code changes

- white close "x" svg added to browser app
- code to overwrite current x image with a themed color svg

## Screenshots
image
image
image
image

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by scottmondo** [comment]
If successful would it be possible to get the `hacktoberfest-accepted` label added to the pr. Thank you :)

**Review by cd-bitwarden — APPROVED** [review]
Everything looks good, great job Scottmondo!

**Comment by djsmith85** [comment]
Hi @scottmondo
Thank you so much for your contribution. This is looking great.

We had actually internally discussed joining in on Hacktoberfest this year, but we did not get everything ready for it, in time.
@cd-bitwarden has been so kind to review your work and, as it's looking good, it has been passed on to QA.

We'd still like you to get credited for your work for Hacktoberfest. So I've have added the label `hacktoberfest-accepted`. 
I cannot promise that this will get tested and merged by Monday, but we will do our best.

Kind regards,
Daniel

**Comment by scottmondo** [comment]
@djsmith85 Thank you :D I appreciate the effort your putting in.

**Pull request merged**
