### PR TITLE
[SG-165] Desktop login flow changes

### PR DESCRIPTION
**Pull request by differsthecat**
## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implement two step login flow updates for desktop.

## Code changes

- **apps/desktop/src/app/accounts/login.component.html:** Update template with two step login UI changes
- **apps/desktop/src/app/accounts/login.component.ts:** Add methods to support two step login flow
- **apps/desktop/src/app/layout/account-switcher.component.html:** Remove routerLink and use router in .ts file. Router link fires before click handler methods, so rememberedEmail would not clear
- **apps/desktop/src/app/layout/account-switcher.component.ts:** Clear rememberedEmail when switching accounts
- **libs/angular/src/components/login.component.ts:** Made toggleValidateEmail public in base class so I could use it in Desktop login component file.
- **libs/common/src/services/api.service.ts:** Add missing leading `/` on knowDevice api route.

## Screenshots

https://user-images.githubusercontent.com/8926729/196282230-b2c9c9d0-a765-4434-bf7e-6a1e2c466182.mov

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by differsthecat** [comment]
Putting as ready to review, will probably hold off on merging this until https://github.com/bitwarden/clients/pull/3793 is merged as there may be some small changes affecting this.

**Review by gbubemismith — COMMENTED** [review]
Excellent job, @differsthecat. However, could you get the `login with device` button to show ?

**Comment by differsthecat** [comment]
> Excellent job, @differsthecat. However, could you get the `login with device` button to show ?

Thanks @gbubemismith ! Yes I can add that, I was going to add it in [SG-171](https://bitwarden.atlassian.net/jira/software/c/projects/SG/boards/71?modal=detail&selectedIssue=SG-171), but I can at least add the UI for the button here

**Review by gbubemismith — APPROVED** [review]
This looks good!

**Pull request merged**
