### PR TITLE
[PM-3326] [CLI] Add minNumber, minSpecial and ambiguous password generation options

### PR DESCRIPTION
**Pull request by jomifepe**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR aims to add missing password generation options to the CLI. Options like **Minimum numbers**, **Minimum special**, and **Avoid ambiguous characters** are present in clients like `desktop` and `browser`, but not in the `cli`.

## Code changes

Since the options are already accepted by the `password-generation` service, the only changes made were in the following files:

- `program.ts` - Accept the `minNumber`, `minSpecial`, and `ambiguous` options in the CLI
- `generate.command.ts` - Accept and validate the options passed to the program and forward them to the `generatePassword` function from the `password-generation` service.
- `utils.ts` - Also took the chance to extract two new utils - `convertNumberOption` and `convertStringOption` to use when parsing the input options.

## Screenshots

Screenshot 2023-08-06 at 21 46 41

Screenshot 2023-08-06 at 22 26 06

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

### CODE REVIEW

**Comment by jomifepe** [comment]
Resolved one of the issues pointed out by CodeScene, to fix the remaining one I would need to break up the whole file.

**Review by djsmith85 — APPROVED** [review]
@jomifepe Thanks you for your contributions I'm sure the Bitwarden and Raycast users using Bitwarden CLI appreciate this.

Passing this on to QA and once they have approved this will get merged for an upcoming release.

**Comment by djsmith85** [comment]
@jomifepe Your changes have passed QA and are ready to get merged. Your work will be included in the upcoming `2023.9`release.

Thanks again for your contribution!

**Comment by jomifepe** [comment]
> @jomifepe Your changes have passed QA and are ready to get merged. Your work will be included in the upcoming `2023.9`release.
> 
> Thanks again for your contribution!

That's great! Thank you for the review and QA 🚀

**Pull request merged**
