### PR TITLE
[PS-1383] fix typo: 'salted hashtag' to 'salted hashing'

### PR DESCRIPTION
**Pull request by alkeldi**
## Type of change
Unless I am completely mistaken and there exist something called `salted hashtag`, I think there's a typo in the clients' description such that `salted hashtag` should be replaced with `salted hashing`.

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x ] Other
```

## Objective

Fix a typo

## Code changes

- multiple **copy.resx** files: replace 'salted hashtag' with 'salted hashing'
## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Comment by djsmith85** [comment]
Hi @alkeldi, thanks for submitting a PR.

We use a translation tool called Crowdin to help manage our localization efforts across many different languages. Our translations can only be updated using Crowdin.

If you are interested in helping translate a Bitwarden client into another language (or make a translation correction), please register an account at Crowdin and join our project here: https://crowdin.com/project/bitwarden-browser

If the language that you are interested in translating is not already listed, create a new account on Crowdin, join the project, and contact one of the project managers.

You can read Crowdin's getting started guide for translators here: https://support.crowdin.com/crowdin-intro/

If the translations on Crowdin do not match the translations on Github, please let us know and we will investigate.

**Comment by djsmith85** [comment]
Could you please remove all changes, besides the ones in the English (en) files, which we use as a source for Crowdin.

**Review by djsmith85 — CHANGES_REQUESTED** [review]
Could you please remove all changes, besides the ones in the English (en) file, which we use as a source for Crowdin.

**Comment by alkeldi** [comment]
@djsmith85 Thanks for the info (done).

**Review by djsmith85 — APPROVED** [review]
@alkeldi Thanks again for your contribution 🎉

**Pull request merged**
